Repository openedx/frontend-app-authoring, pull requests merged in 2023-10, with the labels that each got.

#610 fix: await async saveSetting func to remove unwanted err msg
  src/pages-and-resources/progress/Settings.jsx
Labels: open-source-contribution

#622 Taxonomy list page [FC-0036]
  .env
  .env.development
  .env.test
  .github/workflows/commitlint.yml
  Makefile
  codecov.yml
  package-lock.json
  package.json
  src/generic/sub-header/SubHeader.jsx
  src/index.jsx
  src/taxonomy/TaxonomyCard.jsx
  src/taxonomy/TaxonomyCard.scss
  src/taxonomy/TaxonomyCard.test.jsx
  src/taxonomy/TaxonomyListPage.jsx
  src/taxonomy/TaxonomyListPage.test.jsx
  src/taxonomy/api/hooks/api.js
  src/taxonomy/api/hooks/api.test.js
  src/taxonomy/api/hooks/selectors.js
  src/taxonomy/api/hooks/selectors.test.js
  src/taxonomy/api/types.mjs
  src/taxonomy/index.js
  src/taxonomy/messages.js
  tsconfig.json
Labels: open-source-contribution

#634 fix: Missed favicon in Safari (backport from master)
  public/index.html
Labels: open-source-contribution, backport

#633 fix: Missed favicon in Safari
  public/index.html
Labels: open-source-contribution, waiting for eng review
