Repository openedx/frontend-app-authoring, pull requests merged in 2023-12, with the labels that each got.

#704 [FC-0036] feat: Add content tags tree state + editing
  src/content-tags-drawer/ContentTagsCollapsible.jsx
  src/content-tags-drawer/ContentTagsCollapsible.scss
  src/content-tags-drawer/ContentTagsCollapsible.test.jsx
  src/content-tags-drawer/ContentTagsCollapsibleHelper.jsx
  src/content-tags-drawer/ContentTagsDrawer.jsx
  src/content-tags-drawer/ContentTagsDrawer.test.jsx
  src/content-tags-drawer/ContentTagsDropDownSelector.jsx
  src/content-tags-drawer/ContentTagsDropDownSelector.scss
  src/content-tags-drawer/ContentTagsDropDownSelector.test.jsx
  src/content-tags-drawer/ContentTagsTree.jsx
  src/content-tags-drawer/ContentTagsTree.test.jsx
  src/content-tags-drawer/TagBubble.jsx
  src/content-tags-drawer/TagBubble.scss
  src/content-tags-drawer/TagBubble.test.jsx
  src/content-tags-drawer/TagOutlineIcon.jsx
  src/content-tags-drawer/__mocks__/index.js
  src/content-tags-drawer/__mocks__/updateContentTaxonomyTagsMock.js
  src/content-tags-drawer/data/api.js
  src/content-tags-drawer/data/api.test.js
  src/content-tags-drawer/data/apiHooks.jsx
  src/content-tags-drawer/data/apiHooks.test.jsx
  src/content-tags-drawer/messages.js
Labels: open-source-contribution

#747 [BD-46] feat: added start:with-theme script
  package.json
Labels: blended

#737 [FC-0036] feat: Search Content Tags
  package-lock.json
  package.json
  src/content-tags-drawer/ContentTagsCollapsible.jsx
  src/content-tags-drawer/ContentTagsCollapsible.scss
  src/content-tags-drawer/ContentTagsCollapsible.test.jsx
  src/content-tags-drawer/ContentTagsCollapsibleHelper.jsx
  src/content-tags-drawer/ContentTagsDrawer.jsx
  src/content-tags-drawer/ContentTagsDrawer.test.jsx
  src/content-tags-drawer/ContentTagsDropDownSelector.jsx
  src/content-tags-drawer/ContentTagsDropDownSelector.scss
  src/content-tags-drawer/ContentTagsDropDownSelector.test.jsx
  src/content-tags-drawer/ContentTagsTree.jsx
  src/content-tags-drawer/TagBubble.test.jsx
  src/content-tags-drawer/data/api.js
  src/content-tags-drawer/data/api.test.js
  src/content-tags-drawer/data/apiHooks.jsx
  src/content-tags-drawer/data/apiHooks.test.jsx
  src/content-tags-drawer/data/types.mjs
  src/content-tags-drawer/messages.js
  src/taxonomy/data/types.mjs
  src/taxonomy/tag-list/data/api.js
  src/taxonomy/tag-list/data/types.mjs
  src/taxonomy/taxonomy-detail/data/api.js
  src/taxonomy/taxonomy-detail/data/apiHooks.jsx
  src/taxonomy/taxonomy-detail/data/types.mjs
Labels: open-source-contribution

#674 feat: add download template button to taxonomy list [FC-0036]
  src/taxonomy/TaxonomyListPage.jsx
  src/taxonomy/TaxonomyListPage.test.jsx
  src/taxonomy/data/api.js
  src/taxonomy/data/api.test.js
  src/taxonomy/messages.js
Labels: open-source-contribution, jira:2u

#723 style: UX Refinements on taxonomy pages [FC-0036]
  src/assets/scss/_utilities.scss
  src/generic/sub-header/SubHeader.jsx
  src/index.jsx
  src/taxonomy/TaxonomyLayout.jsx
  src/taxonomy/TaxonomyLayout.test.jsx
  src/taxonomy/TaxonomyListPage.jsx
  src/taxonomy/export-modal/ExportModal.scss
  src/taxonomy/export-modal/index.jsx
  src/taxonomy/index.scss
  src/taxonomy/system-defined-badge/SystemDefinedBadge.scss
  src/taxonomy/system-defined-badge/index.jsx
  src/taxonomy/system-defined-badge/messages.js
  src/taxonomy/tag-list/TagListTable.jsx
  src/taxonomy/tag-list/TagListTable.test.jsx
  src/taxonomy/tag-list/messages.js
  src/taxonomy/taxonomy-card/TaxonomyCard.scss
  src/taxonomy/taxonomy-card/index.jsx
  src/taxonomy/taxonomy-card/messages.js
  src/taxonomy/taxonomy-detail/TaxonomyDetailPage.jsx
  src/taxonomy/taxonomy-detail/TaxonomyDetailPage.test.jsx
Labels: open-source-contribution
