Repository openedx/frontend-app-authoring, pull requests merged in 2023-11, with the labels that each got.

#635 fix: Missed favicon in Safari (backport from master)
  public/index.html
Labels: open-source-contribution, waiting for eng review

#645 feat: Taxonomy export menu [FC-0036]
  README.rst
  docs/readme-images/feature-tagging-taxonomy-pages.png
  src/index.scss
  src/taxonomy/TaxonomyCard.jsx
  src/taxonomy/TaxonomyListPage.jsx
  src/taxonomy/TaxonomyListPage.test.jsx
  src/taxonomy/__mocks__/index.js
  src/taxonomy/__mocks__/taxonomyListMock.js
  src/taxonomy/api/hooks/api.js
  src/taxonomy/api/hooks/api.test.js
  src/taxonomy/api/hooks/selectors.js
  src/taxonomy/data/api.js
  src/taxonomy/data/api.test.js
  src/taxonomy/data/apiHooks.jsx
  src/taxonomy/data/apiHooks.test.jsx
  src/taxonomy/data/types.mjs
  src/taxonomy/export-modal/index.jsx
  src/taxonomy/export-modal/messages.js
  src/taxonomy/messages.js
  src/taxonomy/taxonomy-card/TaxonomyCard.scss
  src/taxonomy/taxonomy-card/TaxonomyCard.test.jsx
  src/taxonomy/taxonomy-card/TaxonomyCardMenu.jsx
  src/taxonomy/taxonomy-card/index.jsx
  src/taxonomy/taxonomy-card/messages.js
Labels: open-source-contribution

#553 feat: Persian language support added
  Makefile
  src/advanced-settings/AdvancedSettings.jsx
  src/custom-pages/CustomPageCard.jsx
  src/custom-pages/CustomPageCard.test.jsx
  src/custom-pages/CustomPages.jsx
  src/custom-pages/factories/mockApiResponses.jsx
  src/files-and-videos/files-page/data/thunks.js
  src/header/messages.js
  src/i18n/index.js
  src/i18n/messages/fa_IR.json
  src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-restrictions/RestrictDatesInput.jsx
  src/pages-and-resources/discussions/app-list/AppList.jsx
  src/pages-and-resources/xpert-unit-summary/XpertUnitSummarySettings.test.jsx
  src/utils.js
Labels: open-source-contribution

#654 [FC-0036] feat: Add ContentTagsDrawer widget
  src/content-tags-drawer/ContentTagsCollapsible.jsx
  src/content-tags-drawer/ContentTagsCollapsible.scss
  src/content-tags-drawer/ContentTagsCollapsible.test.jsx
  src/content-tags-drawer/ContentTagsDrawer.jsx
  src/content-tags-drawer/ContentTagsDrawer.test.jsx
  src/content-tags-drawer/ContentTagsDropDownSelector.jsx
  src/content-tags-drawer/ContentTagsDropDownSelector.scss
  src/content-tags-drawer/ContentTagsDropDownSelector.test.jsx
  src/content-tags-drawer/ContentTagsTree.jsx
  src/content-tags-drawer/ContentTagsTree.test.jsx
  src/content-tags-drawer/TagBubble.jsx
  src/content-tags-drawer/TagBubble.scss
  src/content-tags-drawer/TagBubble.test.jsx
  src/content-tags-drawer/TagOutlineIcon.jsx
  src/content-tags-drawer/__mocks__/contentDataMock.js
  src/content-tags-drawer/__mocks__/contentTaxonomyTagsMock.js
  src/content-tags-drawer/__mocks__/index.js
  src/content-tags-drawer/__mocks__/taxonomyTagsMock.js
  src/content-tags-drawer/data/api.js
  src/content-tags-drawer/data/api.test.js
  src/content-tags-drawer/data/apiHooks.jsx
  src/content-tags-drawer/data/apiHooks.test.jsx
  src/content-tags-drawer/data/types.mjs
  src/content-tags-drawer/index.js
  src/content-tags-drawer/messages.js
  src/content-tags-drawer/utils.js
  src/index.jsx
  src/index.scss
  src/taxonomy/data/api.js
  src/taxonomy/data/api.test.js
  src/taxonomy/data/apiHooks.jsx
  src/taxonomy/data/types.mjs
Labels: open-source-contribution

#655 feat: bare bones taxonomy detail page [FC-0036]
  src/index.jsx
  src/taxonomy/TaxonomyLayout.jsx
  src/taxonomy/TaxonomyLayout.test.jsx
  src/taxonomy/TaxonomyListPage.jsx
  src/taxonomy/export-modal/index.jsx
  src/taxonomy/index.js
  src/taxonomy/tag-list/TagListTable.jsx
  src/taxonomy/tag-list/TagListTable.test.jsx
  src/taxonomy/tag-list/data/api.js
  src/taxonomy/tag-list/data/api.test.js
  src/taxonomy/tag-list/data/apiHooks.jsx
  src/taxonomy/tag-list/data/apiHooks.test.jsx
  src/taxonomy/tag-list/data/types.mjs
  src/taxonomy/tag-list/index.js
  src/taxonomy/tag-list/messages.js
  src/taxonomy/taxonomy-card/TaxonomyCard.test.jsx
  src/taxonomy/taxonomy-card/TaxonomyCardMenu.jsx
  src/taxonomy/taxonomy-card/index.jsx
  src/taxonomy/taxonomy-detail/TaxonomyDetailMenu.jsx
  src/taxonomy/taxonomy-detail/TaxonomyDetailPage.jsx
  src/taxonomy/taxonomy-detail/TaxonomyDetailPage.test.jsx
  src/taxonomy/taxonomy-detail/TaxonomyDetailSideCard.jsx
  src/taxonomy/taxonomy-detail/TaxonomyDetailSideCard.test.jsx
  src/taxonomy/taxonomy-detail/data/api.js
  src/taxonomy/taxonomy-detail/data/api.test.js
  src/taxonomy/taxonomy-detail/data/apiHooks.jsx
  src/taxonomy/taxonomy-detail/data/apiHooks.test.jsx
  src/taxonomy/taxonomy-detail/data/types.mjs
  src/taxonomy/taxonomy-detail/index.js
  src/taxonomy/taxonomy-detail/messages.js
Labels: open-source-contribution

#703 feat: display all child tags in the "bare bones" taxonomy detail page [FAL-3529] [FC-0036]
  src/generic/Loading.jsx
  src/generic/utils.js
  src/taxonomy/TaxonomyListPage.jsx
  src/taxonomy/data/api.js
  src/taxonomy/tag-list/TagListTable.jsx
  src/taxonomy/tag-list/TagListTable.test.jsx
  src/taxonomy/tag-list/data/api.js
  src/taxonomy/tag-list/messages.js
  src/taxonomy/taxonomy-detail/TaxonomyDetailPage.jsx
Labels: open-source-contribution

#687 fix: remove unnecessary course-v1 from courseId string
  src/header/utils.js
Labels: open-source-contribution, jira:2u
