Repository openedx/frontend-app-authoring, pull requests merged in 2024-08, with the labels that each got.

#1198 [FC-0059] UI fixes on create content
  src/library-authoring/EmptyStates.tsx
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/components/LibraryComponents.test.tsx
  src/library-authoring/components/LibraryComponents.tsx
  src/library-authoring/messages.ts
Labels: open-source-contribution, FC

#1197 [FC-0059] feat: add copy to clipboard feature to library authoring
  src/library-authoring/components/ComponentCard.test.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/messages.ts
  src/search-manager/data/api.ts
Labels: open-source-contribution, FC

#1187 feat: Library Home - Paste Content [FC-0059]
  src/generic/clipboard/hooks/useCopyToClipboard.js
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/add-content/AddContentContainer.test.tsx
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/add-content/messages.ts
  src/library-authoring/components/ComponentCard.test.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/LibraryComponents.test.tsx
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
Labels: open-source-contribution, FC

#1215 fix: dropdown checkbox click area [FC-0059]
  src/search-manager/FilterByBlockType.tsx
  src/search-manager/FilterByTags.tsx
Labels: open-source-contribution

#1214 fix: discard button [FC-0062]
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/library-info/LibraryInfo.test.tsx
  src/library-authoring/library-info/LibraryPublishStatus.tsx
Labels: open-source-contribution, create-sandbox, FC

#1223 feat: customize the certificate link in header
  .env
  .env.development
  .env.test
  src/CourseAuthoringRoutes.jsx
  src/header/utils.js
  src/header/utils.test.js
  src/index.jsx
Labels: open-source-contribution

#1225 Backport feat: customize the certificate link in header (#1223)
  .env
  .env.development
  .env.test
  src/CourseAuthoringRoutes.jsx
  src/header/utils.js
  src/header/utils.test.js
  src/index.jsx
Labels: open-source-contribution

#1211 refactor: change toast component [FC-0059]
  src/generic/processing-notification/index.jsx
  src/generic/toast-context/index.test.tsx
  src/generic/toast-context/index.tsx
Labels: open-source-contribution, create-sandbox, FC

#1222 UI fixes for Sort Library Component [FC-0059]
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/search-manager/SearchManager.ts
  src/search-manager/SearchSortWidget.tsx
  src/search-manager/messages.ts
Labels: open-source-contribution, create-sandbox, FC

#1226 Library info sidebar UI fixes
  src/library-authoring/LibraryAuthoringPage.scss
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/index.scss
  src/library-authoring/library-info/LibraryInfoHeader.tsx
  src/library-authoring/library-sidebar/LibrarySidebar.tsx
Labels: open-source-contribution, create-sandbox

#1207 feat: Capa problem types submenu [FC-0059]
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/search-manager/FilterBy.scss
  src/search-manager/FilterByBlockType.tsx
  src/search-manager/SearchManager.ts
  src/search-manager/data/api.ts
  src/search-manager/data/apiHooks.ts
  src/search-manager/messages.ts
  src/search-modal/SearchUI.test.tsx
  src/search-modal/__mocks__/search-result.json
Labels: open-source-contribution, FC
