Repository openedx/frontend-app-authoring, pull requests merged in 2024-09, with the labels that each got.

#1246 fix: FilterItem key warning
  src/search-manager/FilterByBlockType.tsx
Labels: open-source-contribution

#1253 style: Nits on Library Info Sidebar [FC-0059]
  src/library-authoring/library-info/LibraryInfoHeader.tsx
  src/library-authoring/library-sidebar/LibrarySidebar.tsx
Labels: open-source-contribution

#1154 feat: fixed height for prerequisite course dropdown list
  src/schedule-and-details/requirements-section/RequirementsSection.scss
Labels: open-source-contribution

#1216 feat: remove new library button if user does not have create access for v1 libraries
  src/studio-home/StudioHome.jsx
  src/studio-home/StudioHome.test.jsx
Labels: open-source-contribution

#1255 Clean up dependencies [FC-0062]
  package-lock.json
  package.json
Labels: open-source-contribution, FC

#1251 feat: Add type stubs for frontend-platform/i18n [FC-0062]
  src/frontend-platform.d.ts
  src/library-authoring/add-content/messages.ts
  src/library-authoring/component-info/messages.ts
  src/library-authoring/components/messages.ts
  src/library-authoring/library-info/LibraryInfo.tsx
  src/library-authoring/library-info/LibraryPublishStatus.tsx
  src/library-authoring/messages.ts
  src/search-manager/messages.ts
  src/search-modal/messages.ts
  src/studio-home/card-item/index.jsx
  src/studio-home/tabs-section/libraries-v2-tab/libraries-v2-filters/libraries-v2-order-filter-menu/messages.ts
Labels: open-source-contribution, FC

#1262 fix: no validation for combined length of org, number, run
  src/data/constants.js
  src/generic/create-or-rerun-course/CreateOrRerunCourseForm.jsx
  src/generic/create-or-rerun-course/CreateOrRerunCourseForm.test.jsx
  src/generic/create-or-rerun-course/hooks.jsx
  src/generic/create-or-rerun-course/messages.js
Labels: bug, open-source-contribution

#1261 fix: no validation for combined length of org, course number and course run for Redwood
  src/data/constants.js
  src/generic/create-or-rerun-course/CreateOrRerunCourseForm.jsx
  src/generic/create-or-rerun-course/CreateOrRerunCourseForm.test.jsx
  src/generic/create-or-rerun-course/hooks.jsx
  src/generic/create-or-rerun-course/messages.js
Labels: open-source-contribution, backport

#1263 test: refactor and fix flakiness of LibraryAuthoringTest [FC-0062]
  .eslintrc.js
  src/header/Header.tsx
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/__mocks__/index.ts
  src/library-authoring/__mocks__/library-search.json
  src/library-authoring/__mocks__/libraryComponentsMock.ts
  src/library-authoring/common/context.tsx
  src/library-authoring/component-info/ComponentInfoHeader.test.tsx
  src/library-authoring/components/LibrarySection.tsx
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/api.test.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
  src/search-manager/ClearFiltersButton.tsx
  src/search-manager/FilterByTags.tsx
  src/search-manager/SearchKeywordsField.tsx
  src/search-manager/SearchManager.ts
  src/search-modal/SearchModal.tsx
  src/search-modal/SearchUI.tsx
  src/studio-home/card-item/index.jsx
  src/studio-home/tabs-section/libraries-v2-tab/libraries-v2-filters/index.tsx
  src/taxonomy/taxonomy-menu/TaxonomyMenu.test.tsx
  src/testUtils.tsx
Labels: open-source-contribution, FC

#1276 fix: create course button inactive after using org drop-down
  src/generic/create-or-rerun-course/hooks.jsx
Labels: bug, open-source-contribution

#1252 Hide "Advanced Settings" settings item [BB-9081]
  src/CourseAuthoringPage.jsx
  src/header/Header.tsx
  src/header/hooks.js
  src/header/hooks.test.js
Labels: open-source-contribution

#1257 feat: collections tab [FC-0062]
  src/generic/block-type-utils/constants.ts
  src/hooks.js
  src/hooks.ts
  src/library-authoring/EmptyStates.tsx
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/LibraryCollections.tsx
  src/library-authoring/LibraryHome.tsx
  src/library-authoring/LibraryRecentlyModified.tsx
  src/library-authoring/__mocks__/library-search.json
  src/library-authoring/components/BaseComponentCard.tsx
  src/library-authoring/components/CollectionCard.test.tsx
  src/library-authoring/components/CollectionCard.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/LibraryComponents.tsx
  src/library-authoring/components/messages.ts
  src/library-authoring/messages.ts
  src/search-manager/SearchManager.ts
  src/search-manager/data/api.ts
  src/search-manager/data/apiHooks.ts
  src/search-manager/index.ts
  src/search-modal/SearchUI.test.tsx
  src/search-modal/__mocks__/empty-search-result.json
  src/search-modal/__mocks__/search-result.json
Labels: open-source-contribution, FC

#1240 feat: edit Text components within content libraries [FC-0062]
  src/CourseAuthoringRoutes.jsx
  src/editors/EditorContainer.jsx
  src/editors/EditorContainer.test.jsx
  src/editors/EditorContainer.tsx
  src/editors/containers/EditorContainer/__snapshots__/index.test.jsx.snap
  src/editors/containers/EditorContainer/index.jsx
  src/editors/containers/EditorContainer/messages.js
  src/editors/containers/TextEditor/__snapshots__/index.test.jsx.snap
  src/editors/containers/TextEditor/index.jsx
  src/editors/data/redux/app/selectors.js
  src/editors/data/redux/app/selectors.test.js
  src/editors/data/redux/thunkActions/app.js
  src/editors/data/redux/thunkActions/app.test.js
  src/editors/data/services/cms/urls.js
  src/editors/data/services/cms/urls.test.js
  src/generic/data/api.mock.ts
  src/generic/data/api.ts
  src/generic/toast-context/index.tsx
  src/library-authoring/LibraryAuthoringPage.scss
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/LibraryLayout.tsx
  src/library-authoring/add-content/AddContentContainer.test.tsx
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/add-content/AddContentWorkflow.test.tsx
  src/library-authoring/component-info/ComponentDeveloperInfo.tsx
  src/library-authoring/component-info/ComponentInfo.tsx
  src/library-authoring/component-info/ComponentInfoHeader.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/utils.test.ts
  src/library-authoring/components/utils.ts
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
  src/search-manager/data/api.mock.ts
  src/testUtils.tsx
Labels: open-source-contribution, FC

#1259 feat: Create collection Modal [FC-0062]
  src/generic/FormikControl.tsx
  src/library-authoring/EmptyStates.tsx
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryLayout.tsx
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/common/context.tsx
  src/library-authoring/create-collection/CreateCollectionModal.tsx
  src/library-authoring/create-collection/index.tsx
  src/library-authoring/create-collection/messages.ts
  src/library-authoring/data/api.test.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.test.tsx
  src/library-authoring/data/apiHooks.ts
Labels: open-source-contribution, FC

#1242 feat: add component preview to library authoring [FC-0062]
  src/assets/scss/_utilities.scss
  src/library-authoring/LibraryBlock/LibraryBlock.tsx
  src/library-authoring/LibraryBlock/index.ts
  src/library-authoring/LibraryBlock/messages.ts
  src/library-authoring/component-info/ComponentInfo.tsx
  src/library-authoring/component-info/ComponentPreview.scss
  src/library-authoring/component-info/ComponentPreview.tsx
  src/library-authoring/component-info/messages.ts
  src/library-authoring/data/api.ts
  src/library-authoring/index.scss
Labels: open-source-contribution

#1241 refactor: remove thumbnail for non-edX videos & allow removing fallback URLs
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/__snapshots__/index.test.jsx.snap
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/index.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/hooks.jsx
Labels: open-source-contribution

#1275 feat: add component sidebar manage tab [FC-0062]
  src/library-authoring/component-info/ComponentInfo.tsx
  src/library-authoring/component-info/ComponentInfoHeader.test.tsx
  src/library-authoring/component-info/ComponentManagement.test.tsx
  src/library-authoring/component-info/ComponentManagement.tsx
  src/library-authoring/component-info/messages.ts
  src/library-authoring/components/LibraryComponents.test.tsx
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/generic/index.scss
  src/library-authoring/generic/status-widget/StatusWidget.scss
  src/library-authoring/generic/status-widget/index.tsx
  src/library-authoring/generic/status-widget/messages.ts
  src/library-authoring/index.scss
  src/library-authoring/library-info/LibraryPublishStatus.tsx
  src/library-authoring/library-info/messages.ts
  src/library-authoring/library-sidebar/LibrarySidebar.tsx
Labels: open-source-contribution

#1291 fix: Fix content overflow in the Overwrite Files modal window
  src/files-and-videos/files-page/FileValidationModal.jsx
Labels: open-source-contribution

#1292 fix: Fix content overflow in the Overwrite Files modal window
  src/files-and-videos/files-page/FileValidationModal.jsx
Labels: open-source-contribution

#1297 fix: Add missed translation for Lock File tooltip
  src/files-and-videos/files-page/messages.js
Labels: open-source-contribution

#1280 Fix warnings in Problem Editor [FC-0062]
  src/custom.d.ts
  src/editors/Editor.tsx
  src/editors/EditorComponent.ts
  src/editors/containers/EditorContainer/messages.ts
  src/editors/containers/ProblemEditor/__snapshots__/index.test.tsx.snap
  src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/SelectTypeFooter.jsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/SelectTypeFooter.test.jsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/__snapshots__/index.test.jsx.snap
  src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/index.jsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/index.test.jsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/messages.ts
  src/editors/containers/ProblemEditor/components/SelectTypeModal/__snapshots__/index.test.jsx.snap
  src/editors/containers/ProblemEditor/components/SelectTypeModal/content/AdvanceTypeSelect.test.tsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/content/AdvanceTypeSelect.tsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/content/ProblemTypeSelect.test.tsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/content/ProblemTypeSelect.tsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/content/__snapshots__/AdvanceTypeSelect.test.tsx.snap
  src/editors/containers/ProblemEditor/components/SelectTypeModal/content/__snapshots__/ProblemTypeSelect.test.tsx.snap
  src/editors/containers/ProblemEditor/components/SelectTypeModal/content/messages.ts
  src/editors/containers/ProblemEditor/components/SelectTypeModal/hooks.js
  src/editors/containers/ProblemEditor/components/SelectTypeModal/hooks.test.js
  src/editors/containers/ProblemEditor/components/SelectTypeModal/index.test.jsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/index.test.tsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/index.tsx
  src/editors/containers/ProblemEditor/index.test.tsx
  src/editors/containers/ProblemEditor/index.tsx
  src/editors/data/constants/problem.ts
  src/editors/data/redux/index.js
  src/editors/setupEditorTest.js
  src/editors/supportedEditors.ts
  src/editors/utils/StrictDict.ts
  src/testUtils.tsx
Labels: open-source-contribution, FC

#1290 Enable capa problem editor for components in libraries [FC-0062]
  src/editors/EditorContainer.tsx
  src/editors/data/constants/requests.ts
  src/editors/data/redux/app/selectors.js
  src/editors/data/redux/thunkActions/app.js
  src/editors/data/redux/thunkActions/problem.test.ts
  src/editors/data/redux/thunkActions/problem.ts
  src/editors/data/services/cms/api.test.ts
  src/editors/data/services/cms/api.ts
  src/editors/data/services/cms/mockApi.js
  src/editors/data/services/cms/types.ts
  src/editors/data/services/cms/urls.test.ts
  src/editors/data/services/cms/urls.ts
  src/editors/data/services/cms/utils.test.ts
  src/editors/data/services/cms/utils.ts
  src/editors/sharedComponents/ErrorBoundary/ErrorPage.jsx
  src/editors/utils/index.ts
  src/generic/key-utils.test.ts
  src/generic/key-utils.ts
  src/library-authoring/LibraryLayout.tsx
  src/library-authoring/__mocks__/libraryComponentsMock.ts
  src/library-authoring/add-content/AddContentWorkflow.test.tsx
  src/library-authoring/components/ComponentCard.test.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/LibraryComponents.test.tsx
  src/library-authoring/components/utils.test.ts
  src/library-authoring/components/utils.ts
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/apiHooks.ts
  src/search-modal/SearchResult.tsx
Labels: open-source-contribution, FC

#1293 fix: responsiveness on library authoring sidebar [FC-0062]
  src/index.scss
  src/library-authoring/LibraryAuthoringPage.scss
  src/library-authoring/LibraryCollections.tsx
  src/library-authoring/component-info/ComponentInfoHeader.tsx
  src/library-authoring/components/ComponentCard.scss
  src/library-authoring/components/LibraryComponents.tsx
  src/library-authoring/index.scss
Labels: open-source-contribution, FC

#1294 fix: inconsistency with the select all functionality [FC-0059]
  src/search-manager/FilterByBlockType.tsx
Labels: open-source-contribution

#1282 feat: remove new library button if user does not have create access for v1 libraries (#1216)
  src/studio-home/StudioHome.jsx
  src/studio-home/StudioHome.test.jsx
Labels: open-source-contribution

#1298 feat: show children count in collection card
  src/library-authoring/components/CollectionCard.test.tsx
  src/library-authoring/components/CollectionCard.tsx
  src/library-authoring/components/messages.ts
  src/search-manager/data/api.ts
Labels: open-source-contribution

#1302 fix: Fix content overflow in the Pages & Resources modal windows
  src/pages-and-resources/app-settings-modal/AppSettingsModalBase.jsx
Labels: open-source-contribution

#1301 fix: Fix content overflow in the Pages & Resources modal windows
  src/pages-and-resources/app-settings-modal/AppSettingsModalBase.jsx
Labels: open-source-contribution

#1305 Display library title in browser tab [FC-0062]
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
Labels: open-source-contribution

#1281 feat: collections page [FC-0062]
  src/editors/EditorContainer.test.jsx
  src/editors/EditorContainer.tsx
  src/generic/block-type-utils/index.scss
  src/library-authoring/EmptyStates.tsx
  src/library-authoring/LibraryAuthoringPage.scss
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/LibraryHome.tsx
  src/library-authoring/LibraryLayout.tsx
  src/library-authoring/__mocks__/collection-search.json
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/add-content/messages.ts
  src/library-authoring/collections/CollectionInfo.tsx
  src/library-authoring/collections/CollectionInfoHeader.tsx
  src/library-authoring/collections/LibraryCollectionComponents.tsx
  src/library-authoring/collections/LibraryCollectionPage.test.tsx
  src/library-authoring/collections/LibraryCollectionPage.tsx
  src/library-authoring/collections/LibraryCollections.tsx
  src/library-authoring/collections/index.tsx
  src/library-authoring/collections/messages.ts
  src/library-authoring/common/context.tsx
  src/library-authoring/components/LibraryComponents.tsx
  src/library-authoring/create-collection/CreateCollectionModal.tsx
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.test.tsx
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/library-sidebar/LibrarySidebar.tsx
  src/library-authoring/messages.ts
  src/search-manager/SearchKeywordsField.tsx
  src/search-manager/SearchManager.ts
  src/search-manager/data/api.ts
  src/search-manager/data/apiHooks.ts
Labels: open-source-contribution, FC

#1318 Cleanups for the video editor [FC-0062]
  src/editors/containers/VideoEditor/__snapshots__/index.test.jsx.snap
  src/editors/containers/VideoEditor/__snapshots__/index.test.tsx.snap
  src/editors/containers/VideoEditor/components/VideoEditorModal.tsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/ErrorSummary.test.tsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/ErrorSummary.tsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/__snapshots__/ErrorSummary.test.tsx.snap
  src/editors/containers/VideoEditor/components/VideoSettingsModal/index.tsx
  src/editors/containers/VideoEditor/hooks.test.ts
  src/editors/containers/VideoEditor/hooks.ts
  src/editors/containers/VideoEditor/index.test.tsx
  src/editors/containers/VideoEditor/index.tsx
  src/editors/containers/VideoEditor/messages.ts
Labels: open-source-contribution, FC

#1319 feat: Enable the Video editor in content libraries [FC-0062]
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/__snapshots__/index.test.jsx.snap
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/index.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/index.test.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/index.tsx
  src/library-authoring/add-content/AddContentWorkflow.test.tsx
  src/library-authoring/components/utils.test.ts
  src/library-authoring/components/utils.ts
  src/library-authoring/data/api.mocks.ts
Labels: open-source-contribution

#1058 fix: layout responsive for edit page
  src/editors/EditorContainer.scss
  src/index.scss
Labels: open-source-contribution, backport, needs reviewer assigned

#1303 feat: add component Details sidebar [FC-0062]
  src/library-authoring/component-info/ComponentDetails.test.tsx
  src/library-authoring/component-info/ComponentDetails.tsx
  src/library-authoring/component-info/ComponentDeveloperInfo.tsx
  src/library-authoring/component-info/ComponentInfo.tsx
  src/library-authoring/component-info/ComponentManagement.test.tsx
  src/library-authoring/component-info/ComponentManagement.tsx
  src/library-authoring/component-info/messages.ts
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/generic/history-widget/HistoryWidget.scss
  src/library-authoring/generic/history-widget/index.tsx
  src/library-authoring/generic/history-widget/messages.ts
  src/library-authoring/generic/index.scss
Labels: open-source-contribution, FC

#1309 fix: library metadata times are actually displayed in local time
  src/library-authoring/component-info/ComponentManagement.test.tsx
  src/library-authoring/generic/status-widget/messages.ts
Labels: open-source-contribution, FC

#1327 Remove support for the (deprecated) library authoring MFE [FC-0062]
  src/editors/data/services/cms/api.test.ts
  src/editors/data/services/cms/api.ts
  src/search-modal/SearchResult.tsx
  src/search-modal/SearchUI.test.tsx
  src/studio-home/StudioHome.test.jsx
  src/studio-home/StudioHome.tsx
  src/studio-home/__mocks__/studioHomeMock.js
  src/studio-home/card-item/index.tsx
  src/studio-home/factories/mockApiResponses.jsx
  src/studio-home/tabs-section/TabsSection.test.tsx
  src/studio-home/tabs-section/index.tsx
  src/studio-home/tabs-section/libraries-v2-tab/index.tsx
  src/utils.js
  src/utils.test.js
Labels: open-source-contribution, FC

#1299 feat: Add tags to info sidebar of library component [FC-0062]
  src/content-tags-drawer/ContentTagsDrawer.jsx
  src/content-tags-drawer/ContentTagsDrawer.test.jsx
  src/content-tags-drawer/ContentTagsDrawer.tsx
  src/content-tags-drawer/data/api.mocks.ts
  src/content-tags-drawer/data/apiHooks.jsx
  src/library-authoring/component-info/ComponentManagement.test.tsx
  src/library-authoring/component-info/ComponentManagement.tsx
  src/library-authoring/component-info/messages.ts
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/apiHooks.ts
Labels: open-source-contribution, FC

#1320 feat: improve collection sidebar
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/__mocks__/collection-search.json
  src/library-authoring/__mocks__/library-search.json
  src/library-authoring/collections/CollectionDetails.test.tsx
  src/library-authoring/collections/CollectionDetails.tsx
  src/library-authoring/collections/CollectionInfo.tsx
  src/library-authoring/collections/CollectionInfoHeader.test.tsx
  src/library-authoring/collections/CollectionInfoHeader.tsx
  src/library-authoring/collections/LibraryCollectionPage.test.tsx
  src/library-authoring/collections/LibraryCollectionPage.tsx
  src/library-authoring/collections/messages.ts
  src/library-authoring/common/context.tsx
  src/library-authoring/components/CollectionCard.test.tsx
  src/library-authoring/components/CollectionCard.tsx
  src/library-authoring/components/messages.ts
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.test.tsx
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/generic/history-widget/index.tsx
  src/library-authoring/generic/index.scss
  src/library-authoring/library-sidebar/LibrarySidebar.tsx
  src/search-manager/SearchManager.ts
  src/search-manager/data/__mocks__/block-types.json
  src/search-manager/data/api.mock.ts
  src/search-manager/data/api.ts
  src/search-manager/data/apiHooks.test.tsx
  src/search-manager/data/apiHooks.ts
  src/search-manager/index.ts
Labels: open-source-contribution, FC
