Repository openedx/frontend-app-authoring, pull requests merged in 2024-07, with the labels that each got.

#1146 Version bump for Paragon to 22.6.1, with stricter typing
  package-lock.json
  src/content-tags-drawer/ContentTagsCollapsible.jsx
  src/content-tags-drawer/ContentTagsDrawer.jsx
  src/content-tags-drawer/ContentTagsDropDownSelector.jsx
  src/files-and-videos/videos-page/VideoThumbnail.jsx
  src/generic/clipboard/paste-component/components/WhatsInClipboard.jsx
  src/generic/clipboard/paste-component/index.jsx
  src/search-modal/SearchFilterWidget.tsx
  src/search-modal/SearchResult.tsx
Labels: open-source-contribution

#1032 Remove core-js
  package-lock.json
  package.json
  src/index.jsx
  src/setupTest.js
Labels: open-source-contribution

#1076 feat: library home page bare bones [FC-0059]
  src/CourseAuthoringPage.jsx
  src/header/Header.tsx
  src/index.jsx
  src/library-authoring/CreateLibrary.tsx
  src/library-authoring/EmptyStates.tsx
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/LibraryCollections.tsx
  src/library-authoring/LibraryComponents.tsx
  src/library-authoring/LibraryHome.tsx
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHook.ts
  src/library-authoring/index.ts
  src/library-authoring/messages.ts
  src/search-modal/SearchModal.tsx
  src/search-modal/SearchResult.tsx
  src/search-modal/SearchUI.test.tsx
  src/search-modal/SearchUI.tsx
  src/search-modal/data/apiHooks.ts
  src/search-modal/index.ts
  src/studio-home/StudioHome.jsx
  src/studio-home/StudioHome.test.jsx
  src/studio-home/tabs-section/LibraryV2Placeholder.jsx
Labels: open-source-contribution

#1148 fix: only show course blocks in the search modal
  src/search-modal/SearchUI.test.tsx
  src/search-modal/SearchUI.tsx
Labels: open-source-contribution

#1149 chore: remove unused Font Awesome dependencies
  package-lock.json
  package.json
Labels: open-source-contribution

#1150 fix: source map warning seen during build
  src/grading-settings/grading-scale/react-ranger.js
Labels: open-source-contribution

#1116 feat: create library form [FC-0059]
  src/constants.js
  src/generic/alert-error/AlertError.test.tsx
  src/generic/alert-error/index.tsx
  src/generic/create-or-rerun-course/hooks.jsx
  src/generic/data/apiHooks.js
  src/library-authoring/CreateLibrary.tsx
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/LibraryComponents.tsx
  src/library-authoring/LibraryHome.tsx
  src/library-authoring/__mocks__/contentLibrariesListV2.js
  src/library-authoring/create-library/CreateLibrary.test.tsx
  src/library-authoring/create-library/CreateLibrary.tsx
  src/library-authoring/create-library/data/api.ts
  src/library-authoring/create-library/data/apiHooks.ts
  src/library-authoring/create-library/index.ts
  src/library-authoring/create-library/messages.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/index.ts
  src/library-authoring/messages.ts
  src/library/data/api.ts
  src/studio-home/__mocks__/index.js
  src/studio-home/data/api.test.js
  src/studio-home/data/apiHooks.ts
  src/studio-home/tabs-section/TabsSection.test.jsx
  src/studio-home/tabs-section/libraries-v2-tab/index.tsx
Labels: open-source-contribution

#1065 [FC-0059] feat: Add content sidebar in library home
  src/generic/toast-context/index.test.tsx
  src/generic/toast-context/index.tsx
  src/index.jsx
  src/library-authoring/EmptyStates.tsx
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/LibraryLayout.tsx
  src/library-authoring/add-content/AddContentContainer.test.tsx
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/add-content/index.ts
  src/library-authoring/add-content/messages.ts
  src/library-authoring/common/context.tsx
  src/library-authoring/data/api.test.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.test.tsx
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/index.ts
  src/library-authoring/library-sidebar/LibrarySidebar.tsx
  src/library-authoring/library-sidebar/index.ts
  src/library-authoring/messages.ts
Labels: open-source-contribution, create-sandbox

#1109 [FC-0059] Components tab
  src/course-unit/add-component/AddComponent.jsx
  src/course-unit/add-component/AddComponent.test.jsx
  src/course-unit/add-component/add-component-btn/AddComponentIcon.jsx
  src/course-unit/constants.js
  src/course-unit/course-sequence/sequence-navigation/UnitIcon.jsx
  src/course-unit/course-xblock/CourseXBlock.jsx
  src/course-unit/course-xblock/CourseXBlock.test.jsx
  src/generic/block-type-utils/constants.ts
  src/generic/block-type-utils/index.scss
  src/generic/block-type-utils/index.tsx
  src/generic/styles.scss
  src/index.scss
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/LibraryComponents.tsx
  src/library-authoring/LibraryHome.tsx
  src/library-authoring/__mocks__/index.js
  src/library-authoring/__mocks__/libraryComponentsMock.js
  src/library-authoring/components/ComponentCard.scss
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/LibraryComponents.test.tsx
  src/library-authoring/components/LibraryComponents.tsx
  src/library-authoring/components/index.ts
  src/library-authoring/components/messages.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/index.scss
  src/library-authoring/messages.ts
  src/search-modal/SearchResult.tsx
  webpack.dev-tutor.config.js
Labels: open-source-contribution

#1174 fix: bump frontend-lib-content-components to 2.5.1
  package-lock.json
  package.json
  src/course-updates/update-form/UpdateForm.test.jsx
  src/generic/WysiwygEditor.jsx
Labels: create-sandbox

#1141 feat: adds filter by tags and contentType to library home [FC-0059]
  src/index.scss
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/LibraryHome.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/LibraryComponents.test.tsx
  src/library-authoring/components/LibraryComponents.tsx
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/index.tsx
  src/search-manager/BlockTypeLabel.tsx
  src/search-manager/ClearFiltersButton.tsx
  src/search-manager/FilterBy.scss
  src/search-manager/FilterByBlockType.tsx
  src/search-manager/FilterByTags.tsx
  src/search-manager/Highlight.tsx
  src/search-manager/SearchFilterWidget.tsx
  src/search-manager/SearchKeywordsField.tsx
  src/search-manager/SearchManager.ts
  src/search-manager/Stats.tsx
  src/search-manager/data/api.ts
  src/search-manager/data/apiHooks.ts
  src/search-manager/index.scss
  src/search-manager/index.ts
  src/search-manager/messages.ts
  src/search-modal/EmptyStates.tsx
  src/search-modal/SearchModal.scss
  src/search-modal/SearchModal.test.tsx
  src/search-modal/SearchResult.tsx
  src/search-modal/SearchResults.tsx
  src/search-modal/SearchUI.test.tsx
  src/search-modal/SearchUI.tsx
  src/search-modal/index.scss
  src/search-modal/index.ts
  src/search-modal/messages.ts
Labels: open-source-contribution

#1155 fix: add ts* files to cov report
  package-lock.json
  package.json
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/create-library/CreateLibrary.test.tsx
Labels: open-source-contribution

#1182 feat: Add cancel create library button
  src/library-authoring/create-library/CreateLibrary.test.tsx
  src/library-authoring/create-library/CreateLibrary.tsx
  src/library-authoring/create-library/messages.ts
Labels: open-source-contribution

#1147 feat: adds sort widget to search manager and library component page [FC-0059]
  src/library-authoring/EmptyStates.tsx
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/LibraryHome.tsx
  src/library-authoring/LibraryRecentlyModified.tsx
  src/library-authoring/components/LibraryComponents.test.tsx
  src/library-authoring/components/LibraryComponents.tsx
  src/library-authoring/components/LibrarySection.tsx
  src/library-authoring/messages.ts
  src/search-manager/ClearFiltersButton.tsx
  src/search-manager/SearchManager.ts
  src/search-manager/SearchSortWidget.tsx
  src/search-manager/data/api.ts
  src/search-manager/data/apiHooks.ts
  src/search-manager/index.ts
  src/search-manager/messages.ts
Labels: open-source-contribution, create-sandbox

#1193 test: fix flaky library-authoring test [FC-0059]
  src/library-authoring/LibraryAuthoringPage.test.tsx
Labels: open-source-contribution, FC
