Repository openedx/frontend-app-authoring, pull requests merged in 2024-10, with the labels that each got.

#1348 fix: component preview modal overflow [FC-0062]
  src/library-authoring/component-info/ComponentPreview.tsx
Labels: open-source-contribution

#1258 feat: allow full width content in library authoring [FC-0062]
  package-lock.json
  package.json
  src/header/Header.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/LibraryRecentlyModified.tsx
  src/library-authoring/components/ComponentCard.scss
  src/search-manager/data/api.ts
Labels: open-source-contribution, FC

#1355 fix: upload codecov report as a separate workflow step
  .github/workflows/validate.yml
Labels: open-source-contribution

#1359 "Other" (e.g Surveys) components should use grey (background: #646464) in the card title bar, not white [FC-0062]
  src/generic/block-type-utils/constants.ts
  src/generic/block-type-utils/index.tsx
Labels: open-source-contribution

#1345 Improve LibraryContext, convert tests to testUtils [FC-0062]
  src/library-authoring/EmptyStates.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/LibraryHome.tsx
  src/library-authoring/LibraryLayout.tsx
  src/library-authoring/LibraryRecentlyModified.tsx
  src/library-authoring/add-content/AddContentContainer.test.tsx
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/collections/LibraryCollectionComponents.tsx
  src/library-authoring/collections/LibraryCollectionPage.tsx
  src/library-authoring/collections/LibraryCollections.tsx
  src/library-authoring/common/context.tsx
  src/library-authoring/components/CollectionCard.test.tsx
  src/library-authoring/components/CollectionCard.tsx
  src/library-authoring/components/ComponentCard.test.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/LibraryComponents.test.tsx
  src/library-authoring/components/LibraryComponents.tsx
  src/library-authoring/create-collection/CreateCollectionModal.tsx
  src/library-authoring/library-sidebar/LibrarySidebar.tsx
  src/testUtils.tsx
Labels: open-source-contribution, FC

#1331 Show spinner while loading library components [FC-0062]
  src/editors/containers/ProblemEditor/components/EditProblemView/ExplanationWidget/__snapshots__/index.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/ExplanationWidget/messages.js
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryHome.tsx
  src/library-authoring/collections/LibraryCollectionPage.test.tsx
  src/library-authoring/collections/LibraryCollections.test.tsx
  src/library-authoring/collections/LibraryCollections.tsx
  src/library-authoring/collections/messages.ts
  src/library-authoring/components/LibraryComponents.test.tsx
  src/library-authoring/components/LibraryComponents.tsx
  src/library-authoring/data/api.mocks.ts
  src/search-manager/SearchManager.ts
  src/search-manager/data/apiHooks.ts
Labels: open-source-contribution, FC

#1361 Use block type label instead of Library block_types REST API [FC-0062]
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryRecentlyModified.tsx
  src/library-authoring/add-content/AddContentWorkflow.test.tsx
  src/library-authoring/collections/CollectionDetails.tsx
  src/library-authoring/collections/LibraryCollectionPage.test.tsx
  src/library-authoring/components/BaseComponentCard.tsx
  src/library-authoring/components/CollectionCard.tsx
  src/library-authoring/components/ComponentCard.test.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/LibraryComponents.test.tsx
  src/library-authoring/components/LibraryComponents.tsx
  src/library-authoring/components/messages.ts
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
  src/search-manager/BlockTypeLabel.test.tsx
  src/search-manager/BlockTypeLabel.tsx
  src/search-manager/FilterByBlockType.tsx
  src/search-manager/messages.ts
Labels: open-source-contribution

#1357 Open Editors in a Modal (library components only) [FC-0062]
  src/content-tags-drawer/ContentTagsDrawer.test.jsx
  src/editors/Editor.test.jsx
  src/editors/Editor.tsx
  src/editors/EditorContext.tsx
  src/editors/EditorPage.jsx
  src/editors/EditorPage.test.jsx
  src/editors/EditorPage.test.tsx
  src/editors/EditorPage.tsx
  src/editors/__snapshots__/Editor.test.jsx.snap
  src/editors/__snapshots__/EditorPage.test.jsx.snap
  src/editors/containers/EditorContainer/__snapshots__/index.test.jsx.snap
  src/editors/containers/EditorContainer/components/EditorFooter/__snapshots__/index.test.jsx.snap
  src/editors/containers/EditorContainer/components/EditorFooter/index.jsx
  src/editors/containers/EditorContainer/components/EditorFooter/index.test.jsx
  src/editors/containers/EditorContainer/components/EditorFooter/messages.js
  src/editors/containers/EditorContainer/hooks.test.jsx
  src/editors/containers/EditorContainer/hooks.ts
  src/editors/containers/EditorContainer/index.jsx
  src/editors/containers/EditorContainer/index.test.jsx
  src/editors/containers/EditorContainer/index.test.tsx
  src/editors/containers/EditorContainer/index.tsx
  src/editors/containers/EditorContainer/messages.ts
  src/editors/containers/ProblemEditor/components/EditProblemView/__snapshots__/index.test.jsx.snap
  src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/SelectTypeFooter.jsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/SelectTypeFooter.test.jsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/__snapshots__/SelectTypeFooter.test.jsx.snap
  src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/__snapshots__/index.test.jsx.snap
  src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/__snapshots__/index.test.tsx.snap
  src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/index.jsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/index.test.tsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/index.tsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/index.test.tsx
  src/editors/data/services/cms/api.ts
  src/editors/hooks.ts
  src/editors/messages.ts
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryLayout.tsx
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/collections/CollectionDetails.test.tsx
  src/library-authoring/collections/LibraryCollectionPage.test.tsx
  src/library-authoring/common/context.tsx
  src/library-authoring/component-info/ComponentInfo.test.tsx
  src/library-authoring/component-info/ComponentInfo.tsx
  src/library-authoring/components/CollectionCard.test.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/ComponentEditorModal.tsx
  src/library-authoring/components/LibraryComponents.test.tsx
  src/library-authoring/components/utils.test.ts
  src/library-authoring/components/utils.ts
  src/library-authoring/data/api.mocks.ts
  src/testUtils.tsx
Labels: open-source-contribution, FC

#1363 fix: change collection stats component slots [FC-0062]
  src/library-authoring/collections/CollectionDetails.test.tsx
  src/library-authoring/collections/CollectionDetails.tsx
  src/search-manager/data/api.mock.ts
Labels: open-source-contribution

#1346 Content Libraries: Advanced Component Info & OLX Editor [FC-0062]
  src/generic/CodeEditor.tsx
  src/library-authoring/component-info/ComponentAdvancedInfo.test.tsx
  src/library-authoring/component-info/ComponentAdvancedInfo.tsx
  src/library-authoring/component-info/ComponentDetails.test.tsx
  src/library-authoring/component-info/ComponentDetails.tsx
  src/library-authoring/component-info/ComponentDeveloperInfo.tsx
  src/library-authoring/component-info/ComponentPreview.test.tsx
  src/library-authoring/component-info/ComponentPreview.tsx
  src/library-authoring/component-info/messages.ts
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
Labels: open-source-contribution, FC

#1333 feat: delete collection [FC-0062]
  src/course-outline/CourseOutline.test.jsx
  src/course-unit/CourseUnit.test.jsx
  src/generic/delete-modal/DeleteModal.jsx
  src/generic/delete-modal/messages.js
  src/generic/processing-notification/ProccessingNotification.scss
  src/generic/processing-notification/ProcessingNotification.test.jsx
  src/generic/processing-notification/index.jsx
  src/generic/toast-context/index.tsx
  src/library-authoring/components/CollectionCard.test.tsx
  src/library-authoring/components/CollectionCard.tsx
  src/library-authoring/components/messages.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
  src/testUtils.tsx
Labels: open-source-contribution

#1245 feat: save discussion alert dismissal
  src/course-outline/page-alerts/PageAlerts.jsx
  src/course-outline/page-alerts/PageAlerts.test.jsx
Labels: open-source-contribution

#1364 docs: update the README with an easy way to run the MFE with Tutor (on your host)
  .env
  .env.development
  .env.test
  README.rst
  package.json
Labels: open-source-contribution

#1378 feat: add an allowlist of for supported blocks in library [FC-0062]
  .env
  .env.development
  .env.test
  src/generic/data/api.mock.ts
  src/index.jsx
  src/library-authoring/add-content/AddContentContainer.test.tsx
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/add-content/messages.ts
  src/setupTest.js
Labels: open-source-contribution

#1373 feat: manage collections in component sidebar [FC-0062]
  src/library-authoring/__mocks__/collection-search.json
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/collections/LibraryCollectionPage.test.tsx
  src/library-authoring/common/context.tsx
  src/library-authoring/component-info/ComponentManagement.test.tsx
  src/library-authoring/component-info/ComponentManagement.tsx
  src/library-authoring/component-info/ManageCollections.test.tsx
  src/library-authoring/component-info/ManageCollections.tsx
  src/library-authoring/component-info/messages.ts
  src/library-authoring/components/ComponentCard.test.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/messages.ts
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.test.tsx
  src/library-authoring/data/apiHooks.ts
  src/search-manager/SearchManager.ts
  src/search-manager/SearchSortWidget.tsx
  src/search-manager/data/api.ts
Labels: open-source-contribution, FC

#1365 fix: Calendar icon over datepicker modal
  src/assets/scss/_form.scss
Labels: open-source-contribution

#1366 fix: Calendar icon over datepicker modal
  src/assets/scss/_form.scss
Labels: open-source-contribution, create-sandbox

#1307 refactor!: turn on homepage course API V2 consumption by default
  .env
  .env.development
  src/studio-home/hooks.jsx
Labels: open-source-contribution, create-sandbox

#1356 feat: add library component picker
  src/content-tags-drawer/ContentTagsDrawer.test.jsx
  src/content-tags-drawer/ContentTagsDrawer.tsx
  src/content-tags-drawer/ContentTagsDrawerSheet.jsx
  src/course-outline/page-alerts/PageAlerts.test.jsx
  src/generic/block-type-utils/index.scss
  src/index.jsx
  src/library-authoring/EmptyStates.tsx
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/LibraryLayout.tsx
  src/library-authoring/collections/CollectionDetails.test.tsx
  src/library-authoring/collections/CollectionDetails.tsx
  src/library-authoring/collections/CollectionInfo.tsx
  src/library-authoring/collections/CollectionInfoHeader.test.tsx
  src/library-authoring/collections/CollectionInfoHeader.tsx
  src/library-authoring/collections/LibraryCollectionPage.tsx
  src/library-authoring/collections/messages.ts
  src/library-authoring/common/context.tsx
  src/library-authoring/component-info/ComponentAdvancedInfo.test.tsx
  src/library-authoring/component-info/ComponentAdvancedInfo.tsx
  src/library-authoring/component-info/ComponentDetails.test.tsx
  src/library-authoring/component-info/ComponentDetails.tsx
  src/library-authoring/component-info/ComponentInfo.test.tsx
  src/library-authoring/component-info/ComponentInfo.tsx
  src/library-authoring/component-info/ComponentInfoHeader.test.tsx
  src/library-authoring/component-info/ComponentInfoHeader.tsx
  src/library-authoring/component-info/ComponentManagement.test.tsx
  src/library-authoring/component-info/ComponentManagement.tsx
  src/library-authoring/component-info/ComponentPreview.test.tsx
  src/library-authoring/component-info/ComponentPreview.tsx
  src/library-authoring/component-info/ManageCollections.test.tsx
  src/library-authoring/component-info/ManageCollections.tsx
  src/library-authoring/component-info/messages.ts
  src/library-authoring/component-picker/ComponentPicker.test.tsx
  src/library-authoring/component-picker/ComponentPicker.tsx
  src/library-authoring/component-picker/SelectLibrary.test.tsx
  src/library-authoring/component-picker/SelectLibrary.tsx
  src/library-authoring/component-picker/index.ts
  src/library-authoring/component-picker/messages.ts
  src/library-authoring/components/BaseComponentCard.tsx
  src/library-authoring/components/CollectionCard.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/messages.ts
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/index.tsx
  src/library-authoring/library-info/LibraryInfo.test.tsx
  src/library-authoring/library-info/LibraryInfo.tsx
  src/library-authoring/library-info/LibraryInfoHeader.test.tsx
  src/library-authoring/library-info/LibraryInfoHeader.tsx
  src/library-authoring/library-info/LibraryPublishStatus.tsx
  src/library-authoring/library-sidebar/LibrarySidebar.tsx
  src/library-authoring/library-team/LibraryTeam.test.tsx
  src/library-authoring/messages.ts
Labels: open-source-contribution

#1379 feat: add tags to collections [FC-0062]
  src/content-tags-drawer/ContentTagsDrawerHelper.jsx
  src/content-tags-drawer/data/api.js
  src/content-tags-drawer/data/apiHooks.jsx
  src/generic/key-utils.test.ts
  src/generic/key-utils.ts
  src/library-authoring/collections/CollectionInfo.tsx
  src/library-authoring/collections/LibraryCollectionPage.test.tsx
Labels: open-source-contribution

#1393 View for comparing published version of library block to previous [FC-0062]
  src/index.jsx
  src/library-authoring/LibraryBlock/LibraryBlock.tsx
  src/library-authoring/LibraryBlock/index.ts
  src/library-authoring/component-comparison/CompareChangesWidget.test.tsx
  src/library-authoring/component-comparison/CompareChangesWidget.tsx
  src/library-authoring/component-comparison/messages.ts
  src/library-authoring/index.tsx
  src/library-authoring/legacy-integration/PreviewChangesEmbed.test.tsx
  src/library-authoring/legacy-integration/PreviewChangesEmbed.tsx
  src/library-authoring/library-info/LibraryInfoHeader.test.tsx
Labels: open-source-contribution

#1329 Let Studio Home REST API determine if libraries v1 and/or v2 are enabled [FC-0062]
  .env
  .env.development
  .env.test
  README.rst
  src/index.jsx
  src/library-authoring/__mocks__/contentLibrariesListV2.js
  src/setupTest.js
  src/studio-home/StudioHome.test.jsx
  src/studio-home/StudioHome.tsx
  src/studio-home/__mocks__/studioHomeMock.js
  src/studio-home/factories/mockApiResponses.jsx
  src/studio-home/hooks.jsx
  src/studio-home/tabs-section/TabsSection.test.tsx
  src/studio-home/tabs-section/index.tsx
  src/studio-home/tabs-section/libraries-v2-tab/index.tsx
  src/studio-home/tabs-section/messages.ts
  src/studio-home/tabs-section/utils.js
Labels: open-source-contribution, FC

#1402 fix: set original value for TypeaheadDropdown component
  src/editors/sharedComponents/TypeaheadDropdown/index.jsx
Labels: open-source-contribution

#1401 refactor: picker component to only post message with block info [FC-0062]
  src/library-authoring/component-info/ComponentInfo.tsx
  src/library-authoring/component-picker/ComponentPicker.test.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
Labels: open-source-contribution, FC

#1410 chore(deps): update @edx/frontend-lib-content-components to v2.5.3
  package-lock.json
  package.json
Labels: open-source-contribution

#1412 refactor: remove parentLocator and next button from component picker [FC-0062]
  src/library-authoring/common/context.tsx
  src/library-authoring/component-info/ComponentInfo.tsx
  src/library-authoring/component-picker/ComponentPicker.test.tsx
  src/library-authoring/component-picker/ComponentPicker.tsx
  src/library-authoring/component-picker/SelectLibrary.test.tsx
  src/library-authoring/component-picker/SelectLibrary.tsx
  src/library-authoring/components/ComponentCard.tsx
Labels: open-source-contribution

#1409 perf: don't load advanced info details before they're needed [FC-0062]
  src/library-authoring/component-info/ComponentAdvancedInfo.tsx
Labels: open-source-contribution, FC

#1413 feat: add to collection menu item functionality [FC-0062]
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/collections/CollectionDetails.test.tsx
  src/library-authoring/collections/CollectionDetails.tsx
  src/library-authoring/collections/CollectionInfo.tsx
  src/library-authoring/collections/CollectionInfoHeader.test.tsx
  src/library-authoring/collections/CollectionInfoHeader.tsx
  src/library-authoring/collections/LibraryCollectionPage.tsx
  src/library-authoring/common/context.tsx
  src/library-authoring/component-info/ComponentAdvancedInfo.test.tsx
  src/library-authoring/component-info/ComponentAdvancedInfo.tsx
  src/library-authoring/component-info/ComponentDetails.test.tsx
  src/library-authoring/component-info/ComponentDetails.tsx
  src/library-authoring/component-info/ComponentInfo.test.tsx
  src/library-authoring/component-info/ComponentInfo.tsx
  src/library-authoring/component-info/ComponentInfoHeader.test.tsx
  src/library-authoring/component-info/ComponentInfoHeader.tsx
  src/library-authoring/component-info/ComponentManagement.test.tsx
  src/library-authoring/component-info/ComponentManagement.tsx
  src/library-authoring/component-info/ComponentPreview.test.tsx
  src/library-authoring/component-info/ComponentPreview.tsx
  src/library-authoring/component-info/ManageCollections.tsx
  src/library-authoring/component-picker/ComponentPicker.test.tsx
  src/library-authoring/components/CollectionCard.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/ComponentDeleter.tsx
  src/library-authoring/library-sidebar/LibrarySidebar.tsx
Labels: open-source-contribution, FC

#1419 fix: this repo has been renamed to frontend-app-authoring
  .env
  .env.development
  .env.test
  CODEOWNERS
  README.rst
  catalog-info.yaml
  package-lock.json
  package.json
  plugins/course-apps/calculator/package.json
  plugins/course-apps/edxnotes/package.json
  plugins/course-apps/learning_assistant/package.json
  plugins/course-apps/live/package.json
  plugins/course-apps/ora_settings/package.json
  plugins/course-apps/proctoring/package.json
  plugins/course-apps/progress/package.json
  plugins/course-apps/teams/package.json
  plugins/course-apps/wiki/package.json
  plugins/course-apps/xpert_unit_summary/package.json
Labels: open-source-contribution

#1407 feat: publish single library component
  README.rst
  src/library-authoring/component-info/ComponentInfo.test.tsx
  src/library-authoring/component-info/ComponentInfo.tsx
  src/library-authoring/component-info/messages.ts
  src/library-authoring/components/ComponentEditorModal.tsx
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
Labels: open-source-contribution

#1420 feat: Show published components on content picker
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/LibraryRecentlyModified.tsx
  src/library-authoring/__mocks__/collection-search.json
  src/library-authoring/__mocks__/library-search.json
  src/library-authoring/__mocks__/libraryComponentsMock.ts
  src/library-authoring/collections/LibraryCollectionPage.tsx
  src/library-authoring/common/context.tsx
  src/library-authoring/component-info/ComponentInfoHeader.test.tsx
  src/library-authoring/component-info/ComponentInfoHeader.tsx
  src/library-authoring/component-info/ComponentPreview.tsx
  src/library-authoring/component-picker/ComponentPicker.test.tsx
  src/library-authoring/component-picker/ComponentPicker.tsx
  src/library-authoring/components/ComponentCard.test.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
  src/search-manager/data/api.ts
Labels: open-source-contribution

#1424 feat(deps): update header to 5.6.0
  package-lock.json
  package.json
Labels: create-sandbox

#1417 feat: add onComponentSelected callback function and componentPickerMode types [FC-0062]
  src/index.jsx
  src/library-authoring/common/context.tsx
  src/library-authoring/component-info/ComponentInfo.tsx
  src/library-authoring/component-info/messages.ts
  src/library-authoring/component-picker/ComponentPicker.test.tsx
  src/library-authoring/component-picker/ComponentPicker.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/messages.ts
Labels: open-source-contribution

#1392 feat: direct link to single block in library [FC-0062]
  src/editors/EditorContainer.test.jsx
  src/editors/EditorContainer.tsx
  src/editors/__snapshots__/EditorContainer.test.jsx.snap
  src/editors/messages.ts
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/components/LibraryComponents.tsx
  src/search-manager/SearchKeywordsField.tsx
  src/search-manager/SearchManager.ts
  src/search-manager/messages.ts
Labels: open-source-contribution, FC

#1428 feat: show confirmation dialog before discarding library changes [FC-0062]
  src/generic/delete-modal/DeleteModal.jsx
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/library-info/LibraryInfo.test.tsx
  src/library-authoring/library-info/LibraryPublishStatus.tsx
  src/library-authoring/library-info/messages.ts
Labels: open-source-contribution

#1416 feat: add existing content to a collection [FC-0062]
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/LibraryLayout.tsx
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/add-content/PickLibraryContentModal.test.tsx
  src/library-authoring/add-content/PickLibraryContentModal.tsx
  src/library-authoring/add-content/index.ts
  src/library-authoring/add-content/messages.ts
  src/library-authoring/common/context.tsx
  src/library-authoring/component-picker/ComponentPicker.test.tsx
  src/library-authoring/component-picker/ComponentPicker.tsx
  src/library-authoring/component-picker/ComponentPickerModal.tsx
  src/library-authoring/component-picker/index.ts
Labels: open-source-contribution

#1403 fix: allow to preview images
  src/editors/containers/TextEditor/index.jsx
  src/editors/containers/TextEditor/index.test.jsx
  src/editors/data/redux/app/reducer.js
  src/editors/data/redux/app/reducer.test.js
  src/editors/sharedComponents/TinyMceWidget/__snapshots__/index.test.jsx.snap
  src/editors/sharedComponents/TinyMceWidget/hooks.js
  src/editors/sharedComponents/TinyMceWidget/index.jsx
Labels: open-source-contribution

#1432 fix: use absolute URL for Export Tags menu item
  src/course-outline/CourseOutline.jsx
  src/header/hooks.js
Labels: open-source-contribution

#1227 feat: Use configured DEFAULT_GRADE_DESIGNATIONS
  src/grading-settings/GradingSettings.jsx
  src/grading-settings/GradingSettings.test.jsx
  src/grading-settings/data/apiHooks.ts
  src/grading-settings/data/selectors.js
  src/grading-settings/data/slice.js
  src/grading-settings/data/thunks.js
  src/grading-settings/grading-scale/GradingScale.jsx
  src/grading-settings/grading-scale/GradingScale.scss
  src/grading-settings/grading-scale/GradingScale.test.jsx
  src/grading-settings/grading-scale/components/GradingScaleSegment.jsx
  src/grading-settings/grading-scale/components/GradingScaleSegment.tsx
  src/store.js
Labels: open-source-contribution

#1439 [sumac] fix: use absolute URL for Export Tags menu item
  src/course-outline/CourseOutline.jsx
  src/header/hooks.js
Labels: open-source-contribution

#1440 fix: empty state for library selection on component picker [FC-0062]
  src/library-authoring/component-picker/SelectLibrary.test.tsx
  src/library-authoring/component-picker/SelectLibrary.tsx
  src/library-authoring/component-picker/messages.ts
Labels: open-source-contribution, FC

#1441 [sumac] fix: empty state for library selection on component picker [FC-0062]
  src/library-authoring/component-picker/SelectLibrary.test.tsx
  src/library-authoring/component-picker/SelectLibrary.tsx
  src/library-authoring/component-picker/messages.ts
Labels: open-source-contribution, backport, FC

#1442 [sumac] fix: Library Preview Expand button covers dropdown
  src/library-authoring/LibraryAuthoringPage.scss
  src/library-authoring/component-info/ComponentPreview.tsx
Labels: open-source-contribution, backport

#1450 fix: add component to collection on paste [FC-0062]
  src/library-authoring/add-content/AddContentContainer.test.tsx
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/add-content/messages.ts
Labels: open-source-contribution, FC
