Repository openedx/frontend-app-authoring, pull requests merged in 2024-04, with the labels that each got.

#910 fix: content tags drawer width [FC-0036]
  src/content-tags-drawer/ContentTagsDrawer.jsx
  src/content-tags-drawer/ContentTagsDrawer.scss
  src/content-tags-drawer/index.scss
Labels: open-source-contribution

#912 feat: [FC-0044] Unit page - make xblock edit functional
  src/course-unit/CourseUnit.jsx
  src/course-unit/course-xblock/CourseXBlock.jsx
  src/course-unit/course-xblock/CourseXBlock.test.jsx
Labels: open-source-contribution, create-sandbox

#825 feat: pagination studio home for courses
  .env
  .env.development
  .env.test
  src/index.jsx
  src/studio-home/StudioHome.jsx
  src/studio-home/__mocks__/studioHomeMock.js
  src/studio-home/card-item/CardItem.test.jsx
  src/studio-home/card-item/index.jsx
  src/studio-home/data/api.js
  src/studio-home/data/api.test.js
  src/studio-home/data/selectors.js
  src/studio-home/data/slice.js
  src/studio-home/data/slice.test.js
  src/studio-home/data/thunks.js
  src/studio-home/factories/mockApiResponses.jsx
  src/studio-home/hooks.jsx
  src/studio-home/tabs-section/TabsSection.test.jsx
  src/studio-home/tabs-section/courses-tab/index.jsx
  src/studio-home/tabs-section/index.jsx
  src/studio-home/tabs-section/messages.js
Labels: open-source-contribution

#923 feat: Add taxonomies tab in home page
  src/studio-home/tabs-section/TabsSection.test.jsx
  src/studio-home/tabs-section/index.jsx
  src/studio-home/tabs-section/messages.js
Labels: open-source-contribution

#913 feat: [FC-0044] Unit page - display component support label
  src/course-unit/add-component/AddComponent.jsx
  src/course-unit/add-component/AddComponent.test.jsx
  src/course-unit/add-component/add-component-btn/AddComponentIcon.jsx
  src/course-unit/add-component/add-component-modals/ComponentModalView.jsx
  src/course-unit/add-component/messages.js
  src/course-unit/constants.js
  src/course-unit/course-xblock/CourseXBlock.jsx
  src/course-unit/course-xblock/CourseXBlock.test.jsx
Labels: open-source-contribution, create-sandbox

#937 feat: Put Taxonomies tab behind flag
  src/studio-home/tabs-section/TabsSection.test.jsx
  src/studio-home/tabs-section/index.jsx
Labels: open-source-contribution

#924 fix: message case for `Manage tags` and `Unit tags` strings [FC-0053]
  src/content-tags-drawer/messages.js
Labels: open-source-contribution

#930 Fix the TaxonomyMenu test, which wasn't getting run at all
  src/taxonomy/taxonomy-menu/TaxonomyMenu.jsx
  src/taxonomy/taxonomy-menu/TaxonomyMenu.test.jsx
Labels: open-source-contribution

#915 fix: incorrect redirection link to Pages&Resources from Custom Pages to Quince
  src/custom-pages/CustomPages.jsx
Labels: open-source-contribution, backport

#916 fix: incorrect redirection link to Pages&Resources from Custom Pages
  src/custom-pages/CustomPages.jsx
Labels: open-source-contribution

#928 feat: add content search modal [FC-0040]
  package-lock.json
  package.json
  src/header/Header.jsx
  src/hooks.js
  src/search-modal/SearchModal.jsx
  src/search-modal/SearchModal.test.jsx
  src/search-modal/SearchResult.jsx
  src/search-modal/SearchUI.jsx
  src/search-modal/data/api.js
  src/search-modal/data/apiHooks.js
  src/search-modal/messages.js
Labels: open-source-contribution

#918 Content Search Modal: Filters [FC-0040]
  package-lock.json
  package.json
  src/content-tags-drawer/ContentTagsDropDownSelector.jsx
  src/header/Header.jsx
  src/index.scss
  src/search-modal/BlockTypeLabel.jsx
  src/search-modal/ClearFiltersButton.jsx
  src/search-modal/EmptyStates.jsx
  src/search-modal/FilterByBlockType.jsx
  src/search-modal/FilterByTags.jsx
  src/search-modal/SearchEndpointLoader.jsx
  src/search-modal/SearchFilterWidget.jsx
  src/search-modal/SearchKeywordsField.jsx
  src/search-modal/SearchModal.jsx
  src/search-modal/SearchModal.scss
  src/search-modal/SearchModal.test.jsx
  src/search-modal/SearchResult.jsx
  src/search-modal/SearchUI.jsx
  src/search-modal/SearchUI.test.jsx
  src/search-modal/Stats.jsx
  src/search-modal/__mocks__/search-result.json
  src/search-modal/data/apiHooks.js
  src/search-modal/messages.js
  src/taxonomy/manage-orgs/ManageOrgsModal.jsx
Labels: open-source-contribution

#846 feat: home studio search filters
  src/generic/Loading.jsx
  src/studio-home/StudioHome.jsx
  src/studio-home/__mocks__/studioHomeMock.js
  src/studio-home/card-item/CardItem.test.jsx
  src/studio-home/card-item/index.jsx
  src/studio-home/data/api.js
  src/studio-home/data/slice.js
  src/studio-home/data/slice.test.js
  src/studio-home/factories/mockApiResponses.jsx
  src/studio-home/hooks.jsx
  src/studio-home/processing-courses/index.jsx
  src/studio-home/tabs-section/TabsSection.test.jsx
  src/studio-home/tabs-section/courses-tab/courses-filters/__snapshots__/index.test.jsx.snap
  src/studio-home/tabs-section/courses-tab/courses-filters/courses-filter-menu/__snapshots__/index.test.jsx.snap
  src/studio-home/tabs-section/courses-tab/courses-filters/courses-filter-menu/index.jsx
  src/studio-home/tabs-section/courses-tab/courses-filters/courses-filter-menu/index.test.jsx
  src/studio-home/tabs-section/courses-tab/courses-filters/courses-order-filter-menu/__snapshots__/index.test.jsx.snap
  src/studio-home/tabs-section/courses-tab/courses-filters/courses-order-filter-menu/index.jsx
  src/studio-home/tabs-section/courses-tab/courses-filters/courses-order-filter-menu/index.test.jsx
  src/studio-home/tabs-section/courses-tab/courses-filters/courses-order-filter-menu/messages.js
  src/studio-home/tabs-section/courses-tab/courses-filters/courses-types-filter-menu/__snapshots__/index.test.jsx.snap
  src/studio-home/tabs-section/courses-tab/courses-filters/courses-types-filter-menu/index.jsx
  src/studio-home/tabs-section/courses-tab/courses-filters/courses-types-filter-menu/index.test.jsx
  src/studio-home/tabs-section/courses-tab/courses-filters/courses-types-filter-menu/messages.js
  src/studio-home/tabs-section/courses-tab/courses-filters/index.jsx
  src/studio-home/tabs-section/courses-tab/courses-filters/index.scss
  src/studio-home/tabs-section/courses-tab/courses-filters/index.test.jsx
  src/studio-home/tabs-section/courses-tab/index.jsx
  src/studio-home/tabs-section/courses-tab/index.scss
  src/studio-home/tabs-section/courses-tab/index.test.jsx
  src/studio-home/tabs-section/messages.js
Labels: open-source-contribution, product review

#933 Bump Paragon to v22.2.1, fix some bugs that turned up
  package-lock.json
  package.json
  src/files-and-videos/generic/table-components/FilterStatus.jsx
  src/files-and-videos/videos-page/VideosPage.test.jsx
  src/studio-home/tabs-section/courses-tab/courses-filters/__snapshots__/index.test.jsx.snap
  src/taxonomy/manage-orgs/ManageOrgsModal.jsx
  src/taxonomy/manage-orgs/ManageOrgsModal.test.jsx
  src/taxonomy/manage-orgs/messages.js
Labels: open-source-contribution, waiting for eng review

#946 feat: improve search modal results [FC-0040]
  src/course-outline/CourseOutline.scss
  src/course-outline/section-card/SectionCard.jsx
  src/course-outline/subsection-card/SubsectionCard.jsx
  src/course-outline/unit-card/UnitCard.jsx
  src/custom.d.ts
  src/search-modal/EmptyStates.jsx
  src/search-modal/SearchEndpointLoader.jsx
  src/search-modal/SearchModal.jsx
  src/search-modal/SearchModal.scss
  src/search-modal/SearchModal.test.jsx
  src/search-modal/SearchResult.jsx
  src/search-modal/SearchUI.jsx
  src/search-modal/SearchUI.test.jsx
  src/search-modal/__mocks__/empty-search-result.json
  src/search-modal/__mocks__/search-result.json
  src/search-modal/images/empty-search.svg
  src/search-modal/images/no-results.svg
  src/search-modal/messages.js
Labels: open-source-contribution

#947 [FC-0036] Refined tag drawer UI style
  src/content-tags-drawer/ContentTagsCollapsible.jsx
  src/content-tags-drawer/ContentTagsCollapsible.scss
  src/content-tags-drawer/ContentTagsCollapsible.test.jsx
  src/content-tags-drawer/ContentTagsDrawer.jsx
  src/content-tags-drawer/ContentTagsDrawer.test.jsx
  src/course-outline/card-header/CardHeader.test.jsx
Labels: open-source-contribution

#949 [FC-0036] feat: Sort taxonomies
  src/content-tags-drawer/ContentTagsDrawer.jsx
  src/content-tags-drawer/ContentTagsDrawer.test.jsx
Labels: open-source-contribution

#901 feat: [FC-0044] Unit page - Manage access modal (unit & xblocks)
  src/constants.js
  src/course-outline/CourseOutline.jsx
  src/course-outline/CourseOutline.scss
  src/course-outline/CourseOutline.test.jsx
  src/course-unit/CourseUnit.jsx
  src/course-unit/CourseUnit.scss
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/__mocks__/courseVerticalChildren.js
  src/course-unit/course-xblock/CourseXBlock.jsx
  src/course-unit/course-xblock/CourseXBlock.scss
  src/course-unit/course-xblock/CourseXBlock.test.jsx
  src/course-unit/course-xblock/constants.js
  src/course-unit/course-xblock/messages.js
  src/course-unit/course-xblock/xblock-messages/XBlockMessages.jsx
  src/course-unit/course-xblock/xblock-messages/XBlockMessages.test.jsx
  src/course-unit/course-xblock/xblock-messages/utils.js
  src/course-unit/course-xblock/xblock-messages/utils.test.js
  src/course-unit/data/api.js
  src/course-unit/data/slice.js
  src/course-unit/data/thunk.js
  src/course-unit/data/utils.js
  src/course-unit/header-title/HeaderTitle.jsx
  src/course-unit/header-title/HeaderTitle.scss
  src/course-unit/header-title/HeaderTitle.test.jsx
  src/course-unit/header-title/messages.js
  src/course-unit/hooks.jsx
  src/generic/configure-modal/AdvancedTab.jsx
  src/generic/configure-modal/BasicTab.jsx
  src/generic/configure-modal/ConfigureModal.jsx
  src/generic/configure-modal/ConfigureModal.scss
  src/generic/configure-modal/ConfigureModal.test.jsx
  src/generic/configure-modal/PrereqSettings.jsx
  src/generic/configure-modal/UnitTab.jsx
  src/generic/configure-modal/VisibilityTab.jsx
  src/generic/configure-modal/__mocks__/index.js
  src/generic/configure-modal/messages.js
  src/generic/styles.scss
Labels: open-source-contribution, create-sandbox

#945 feat: Allow filtering by multiple tags [FC-0040]
  package-lock.json
  package.json
  src/search-modal/ClearFiltersButton.jsx
  src/search-modal/EmptyStates.jsx
  src/search-modal/FilterByBlockType.jsx
  src/search-modal/FilterByTags.jsx
  src/search-modal/Highlight.jsx
  src/search-modal/SearchEndpointLoader.jsx
  src/search-modal/SearchKeywordsField.jsx
  src/search-modal/SearchModal.jsx
  src/search-modal/SearchModal.scss
  src/search-modal/SearchModal.test.jsx
  src/search-modal/SearchResult.jsx
  src/search-modal/SearchResults.jsx
  src/search-modal/SearchUI.jsx
  src/search-modal/SearchUI.test.jsx
  src/search-modal/Stats.jsx
  src/search-modal/__mocks__/empty-search-result.json
  src/search-modal/__mocks__/facet-search-level0.json
  src/search-modal/__mocks__/facet-search-level1.json
  src/search-modal/__mocks__/facet-search.json
  src/search-modal/__mocks__/search-result.json
  src/search-modal/__mocks__/tags-keyword-search.json
  src/search-modal/data/api.js
  src/search-modal/data/apiHooks.js
  src/search-modal/manager/SearchManager.js
  src/search-modal/messages.js
Labels: open-source-contribution

#951 fix: removing ENABLE_NEW_EDITOR_PAGES flag
  .env
  .env.development
  .env.test
  README.rst
  src/CourseAuthoringRoutes.jsx
  src/index.jsx
Labels: open-source-contribution

#939 [FC-0036] Refined tag drawer
  src/content-tags-drawer/ContentTagsCollapsible.jsx
  src/content-tags-drawer/ContentTagsCollapsible.scss
  src/content-tags-drawer/ContentTagsCollapsible.test.jsx
  src/content-tags-drawer/ContentTagsCollapsibleHelper.jsx
  src/content-tags-drawer/ContentTagsDrawer.jsx
  src/content-tags-drawer/ContentTagsDrawer.scss
  src/content-tags-drawer/ContentTagsDrawer.test.jsx
  src/content-tags-drawer/ContentTagsDrawerHelper.jsx
  src/content-tags-drawer/ContentTagsTree.jsx
  src/content-tags-drawer/ContentTagsTree.test.jsx
  src/content-tags-drawer/TagBubble.jsx
  src/content-tags-drawer/TagBubble.scss
  src/content-tags-drawer/TagBubble.test.jsx
  src/content-tags-drawer/TagsTree.jsx
  src/content-tags-drawer/TagsTree.scss
  src/content-tags-drawer/TagsTree.test.jsx
  src/content-tags-drawer/__mocks__/contentTaxonomyTagsTreeMock.js
  src/content-tags-drawer/common/context.js
  src/content-tags-drawer/data/api.js
  src/content-tags-drawer/data/api.test.js
  src/content-tags-drawer/data/apiHooks.jsx
  src/content-tags-drawer/data/apiHooks.test.jsx
  src/content-tags-drawer/data/types.mjs
  src/content-tags-drawer/index.scss
  src/content-tags-drawer/messages.js
  src/content-tags-drawer/tags-sidebar-controls/TagsSidebarBody.jsx
  src/content-tags-drawer/tags-sidebar-controls/TagsTree.jsx
  src/content-tags-drawer/tags-sidebar-controls/TagsTree.test.jsx
Labels: open-source-contribution

#957 feat: redirect to unit page if the hit or its parent is a unit
  src/course-outline/CourseOutline.scss
  src/course-unit/course-xblock/CourseXBlock.jsx
  src/course-unit/hooks.jsx
  src/custom.d.ts
  src/index.scss
  src/search-modal/SearchResult.jsx
  src/search-modal/SearchUI.test.jsx
  src/search-modal/__mocks__/search-result.json
  src/search-modal/data/api.js
Labels: open-source-contribution

#908 feat: [FC-0044] Course unit - Drag and drop for xblocks
  src/course-outline/CourseOutline.jsx
  src/course-outline/CourseOutline.scss
  src/course-outline/CourseOutline.test.jsx
  src/course-outline/section-card/SectionCard.jsx
  src/course-outline/subsection-card/SubsectionCard.jsx
  src/course-outline/unit-card/UnitCard.jsx
  src/course-unit/CourseUnit.jsx
  src/course-unit/CourseUnit.scss
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/clipboard/paste-notification/index.jsx
  src/course-unit/course-xblock/CourseXBlock.jsx
  src/course-unit/course-xblock/CourseXBlock.scss
  src/course-unit/data/api.js
  src/course-unit/data/selectors.js
  src/course-unit/data/slice.js
  src/course-unit/data/thunk.js
  src/course-unit/data/utils.js
  src/course-unit/hooks.jsx
  src/generic/drag-helper/DragContextProvider.jsx
  src/generic/drag-helper/DraggableList.jsx
  src/generic/drag-helper/SortableItem.jsx
  src/generic/drag-helper/SortableItem.scss
  src/generic/drag-helper/messages.js
  src/generic/drag-helper/utils.js
  src/generic/styles.scss
Labels: open-source-contribution, create-sandbox

#890 feat: [FC-0044] Textbooks Page
  src/CourseAuthoringRoutes.jsx
  src/constants.js
  src/generic/FormikControl.jsx
  src/generic/delete-modal/DeleteModal.jsx
  src/generic/delete-modal/DeleteModal.test.jsx
  src/generic/modal-dropzone/ModalDropzone.jsx
  src/generic/modal-dropzone/ModalDropzone.test.jsx
  src/generic/modal-dropzone/messages.js
  src/generic/modal-dropzone/useModalDropzone.jsx
  src/generic/promptIfDirty/PromptIfDirty.jsx
  src/generic/promptIfDirty/PromtIfDirty.test.jsx
  src/index.scss
  src/store.js
  src/textbooks/Textbook.test.jsx
  src/textbooks/Textbooks.jsx
  src/textbooks/Textbooks.scss
  src/textbooks/__mocks__/index.js
  src/textbooks/__mocks__/textbooksMock.js
  src/textbooks/data/api.js
  src/textbooks/data/api.test.js
  src/textbooks/data/selectors.js
  src/textbooks/data/slice.js
  src/textbooks/data/slice.test.jsx
  src/textbooks/data/thunk.js
  src/textbooks/data/thunk.test.js
  src/textbooks/empty-placeholder/EmptyPlaceholder.jsx
  src/textbooks/empty-placeholder/EmptyPlaceholder.scss
  src/textbooks/empty-placeholder/EmptyPlaceholder.test.jsx
  src/textbooks/empty-placeholder/messages.js
  src/textbooks/hooks.jsx
  src/textbooks/index.js
  src/textbooks/messages.js
  src/textbooks/textbook-card/TextbookCard.scss
  src/textbooks/textbook-card/TextbooksCard.jsx
  src/textbooks/textbook-card/TextbooksCard.test.jsx
  src/textbooks/textbook-card/messages.js
  src/textbooks/textbook-form/TextbookForm.jsx
  src/textbooks/textbook-form/TextbookForm.scss
  src/textbooks/textbook-form/TextbookForm.test.jsx
  src/textbooks/textbook-form/messages.js
  src/textbooks/textbook-form/validations.js
  src/textbooks/textbook-sidebar/TextbookSidebar.jsx
  src/textbooks/textbook-sidebar/TextbookSidebar.test.jsx
  src/textbooks/textbook-sidebar/messages.js
  src/textbooks/utils.js
Labels: open-source-contribution, create-sandbox
