Repository openedx/frontend-app-authoring, pull requests merged in 2024-03, with the labels that each got.

#863 fix: Paragon stepper fix inside discussions settings
  src/export-page/CourseExportPage.scss
  src/export-page/export-stepper/ExportStepper.scss
Labels: open-source-contribution

#869 fix: Incorrect redirect link to Pages & Resources from pages within Course Authoring MFE
  src/utils.js
Labels: open-source-contribution

#864 fix: Incorrect redirect link to Pages & Resources from pages within Course Authoring MFE
  src/utils.js
Labels: open-source-contribution

#855 [UU-58] Implement tagging & taxonomy feature in outline
  src/content-tags-drawer/ContentTagsDrawer.jsx
  src/content-tags-drawer/ContentTagsDrawer.test.jsx
  src/content-tags-drawer/data/apiHooks.jsx
  src/course-outline/CourseOutline.jsx
  src/course-outline/CourseOutline.test.jsx
  src/course-outline/__mocks__/contentTagsCount.js
  src/course-outline/__mocks__/index.js
  src/course-outline/card-header/CardHeader.jsx
  src/course-outline/card-header/CardHeader.test.jsx
  src/course-outline/card-header/messages.js
  src/course-outline/data/api.js
  src/course-outline/data/api.test.js
  src/course-outline/data/apiHooks.jsx
  src/course-outline/data/apiHooks.test.jsx
  src/course-outline/unit-card/UnitCard.jsx
  src/generic/tag-count/TagCount.scss
  src/generic/tag-count/TagCount.test.jsx
  src/generic/tag-count/index.jsx
Labels: open-source-contribution, jira:2u

#857 feat: [FC-0044] Unit page - display xblock components
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/course-xblock/messages.js
  src/course-unit/header-title/HeaderTitle.jsx
Labels: open-source-contribution, create-sandbox

#834 [FC-0036] feat: New "Add Tags" widget
  package-lock.json
  package.json
  src/content-tags-drawer/ContentTagsCollapsible.d.ts
  src/content-tags-drawer/ContentTagsCollapsible.jsx
  src/content-tags-drawer/ContentTagsCollapsible.scss
  src/content-tags-drawer/ContentTagsCollapsible.test.jsx
  src/content-tags-drawer/ContentTagsCollapsibleHelper.jsx
  src/content-tags-drawer/ContentTagsDrawer.jsx
  src/content-tags-drawer/ContentTagsDrawer.test.jsx
  src/content-tags-drawer/ContentTagsDropDownSelector.jsx
  src/content-tags-drawer/ContentTagsDropDownSelector.scss
  src/content-tags-drawer/ContentTagsDropDownSelector.test.jsx
  src/content-tags-drawer/TagBubble.jsx
  src/content-tags-drawer/messages.js
  src/index.scss
Labels: open-source-contribution

#852 [FC-0036] Tags Sidebar
  package-lock.json
  src/content-tags-drawer/ContentTagsDrawer.jsx
  src/content-tags-drawer/__mocks__/contentTaxonomyTagsCountMock.js
  src/content-tags-drawer/__mocks__/contentTaxonomyTagsTreeMock.js
  src/content-tags-drawer/__mocks__/index.js
  src/content-tags-drawer/data/api.js
  src/content-tags-drawer/data/api.test.js
  src/content-tags-drawer/data/apiHooks.jsx
  src/content-tags-drawer/data/apiHooks.test.jsx
  src/content-tags-drawer/index.scss
  src/content-tags-drawer/messages.js
  src/content-tags-drawer/tags-sidebar-controls/TagsSidebarBody.jsx
  src/content-tags-drawer/tags-sidebar-controls/TagsSidebarBody.test.jsx
  src/content-tags-drawer/tags-sidebar-controls/TagsSidebarControls.scss
  src/content-tags-drawer/tags-sidebar-controls/TagsSidebarHeader.jsx
  src/content-tags-drawer/tags-sidebar-controls/TagsSidebarHeader.test.jsx
  src/content-tags-drawer/tags-sidebar-controls/TagsTree.jsx
  src/content-tags-drawer/tags-sidebar-controls/TagsTree.test.jsx
  src/content-tags-drawer/tags-sidebar-controls/index.jsx
  src/course-unit/CourseUnit.jsx
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/course-sequence/sequence-navigation/SequenceNavigationTabs.jsx
  src/course-unit/sidebar/LocationInfo.jsx
  src/course-unit/sidebar/PublishControls.jsx
  src/course-unit/sidebar/Sidebar.scss
  src/course-unit/sidebar/components/SidebarBody.jsx
  src/course-unit/sidebar/index.jsx
  src/generic/styles.scss
  src/index.scss
Labels: open-source-contribution

#627 feat!: remove Transifex calls for OEP-58 | FC-0012
  .gitignore
  .tx/config
  Makefile
  src/i18n/index.js
  src/i18n/messages/ar.json
  src/i18n/messages/de.json
  src/i18n/messages/de_DE.json
  src/i18n/messages/es_419.json
  src/i18n/messages/fa_IR.json
  src/i18n/messages/fr.json
  src/i18n/messages/fr_CA.json
  src/i18n/messages/hi.json
  src/i18n/messages/it.json
  src/i18n/messages/it_IT.json
  src/i18n/messages/pt.json
  src/i18n/messages/pt_PT.json
  src/i18n/messages/ru.json
  src/i18n/messages/uk.json
  src/i18n/messages/zh_CN.json
Labels: open-source-contribution

#859 feat: allow dragging blocks across parents in outline
  .env
  .env.development
  .env.test
  package-lock.json
  package.json
  src/course-outline/CourseOutline.jsx
  src/course-outline/CourseOutline.scss
  src/course-outline/CourseOutline.test.jsx
  src/course-outline/__mocks__/courseOutlineIndex.js
  src/course-outline/card-header/CardHeader.jsx
  src/course-outline/card-header/StatusBadge.jsx
  src/course-outline/constants.js
  src/course-outline/data/api.js
  src/course-outline/data/selectors.js
  src/course-outline/data/slice.js
  src/course-outline/data/thunk.js
  src/course-outline/drag-helper/ConditionalSortableElement.jsx
  src/course-outline/drag-helper/DragContextProvider.jsx
  src/course-outline/drag-helper/DraggableList.jsx
  src/course-outline/drag-helper/SortableItem.jsx
  src/course-outline/drag-helper/SortableItem.scss
  src/course-outline/drag-helper/messages.js
  src/course-outline/drag-helper/utils.js
  src/course-outline/hooks.jsx
  src/course-outline/page-alerts/PageAlerts.jsx
  src/course-outline/page-alerts/PageAlerts.test.jsx
  src/course-outline/page-alerts/messages.js
  src/course-outline/section-card/SectionCard.jsx
  src/course-outline/section-card/SectionCard.test.jsx
  src/course-outline/subsection-card/SubsectionCard.jsx
  src/course-outline/subsection-card/SubsectionCard.test.jsx
  src/course-outline/unit-card/UnitCard.jsx
  src/course-outline/unit-card/UnitCard.test.jsx
  src/course-outline/utils.jsx
  src/course-outline/xblock-status/GradingPolicyAlert.jsx
  src/course-outline/xblock-status/ReleaseStatus.jsx
  src/course-outline/xblock-status/StatusMessages.jsx
  src/course-outline/xblock-status/XBlockStatus.jsx
  src/data/constants.js
  src/generic/DraftIcon.jsx
  src/index.jsx
Labels: open-source-contribution, create-sandbox

#850 Clean up Taxonomy API files/hooks/queries [FC-0036]
  src/content-tags-drawer/ContentTagsDrawer.jsx
  src/content-tags-drawer/ContentTagsDrawer.test.jsx
  src/taxonomy/TaxonomyListPage.jsx
  src/taxonomy/TaxonomyListPage.test.jsx
  src/taxonomy/data/api.js
  src/taxonomy/data/api.test.js
  src/taxonomy/data/apiHooks.js
  src/taxonomy/data/apiHooks.jsx
  src/taxonomy/data/apiHooks.test.jsx
  src/taxonomy/data/types.mjs
  src/taxonomy/export-modal/index.jsx
  src/taxonomy/import-tags/ImportTagsWizard.jsx
  src/taxonomy/import-tags/ImportTagsWizard.test.jsx
  src/taxonomy/import-tags/__mocks__/index.js
  src/taxonomy/import-tags/__mocks__/taxonomyImportMock.js
  src/taxonomy/import-tags/data/api.js
  src/taxonomy/import-tags/data/api.test.jsx
  src/taxonomy/import-tags/index.js
  src/taxonomy/import-tags/utils.js
  src/taxonomy/manage-orgs/ManageOrgsModal.jsx
  src/taxonomy/tag-list/TagListTable.jsx
  src/taxonomy/tag-list/data/api.js
  src/taxonomy/tag-list/data/api.test.js
  src/taxonomy/tag-list/data/apiHooks.js
  src/taxonomy/tag-list/data/apiHooks.jsx
  src/taxonomy/tag-list/data/apiHooks.test.jsx
  src/taxonomy/taxonomy-detail/TaxonomyDetailPage.jsx
  src/taxonomy/taxonomy-detail/TaxonomyDetailPage.test.jsx
Labels: open-source-contribution

#853 fix: use styles from frontend-content-header
  src/header/header.scss
  src/index.scss
Labels: open-source-contribution, waiting for eng review

#900 [FC-0036] feat: Make tags widget keyboard accessible
  src/content-tags-drawer/ContentTagsCollapsible.d.ts
  src/content-tags-drawer/ContentTagsCollapsible.jsx
  src/content-tags-drawer/ContentTagsCollapsible.test.jsx
  src/content-tags-drawer/ContentTagsDropDownSelector.jsx
  src/content-tags-drawer/ContentTagsDropDownSelector.scss
  src/content-tags-drawer/ContentTagsDropDownSelector.test.jsx
  src/content-tags-drawer/messages.js
Labels: open-source-contribution, waiting for eng review

#879 feat: tag sections, subsections, and the whole course (FC-0053)
  src/content-tags-drawer/ContentTagsDrawer.jsx
  src/content-tags-drawer/data/api.js
  src/content-tags-drawer/data/apiHooks.jsx
  src/content-tags-drawer/data/apiHooks.test.jsx
  src/content-tags-drawer/data/types.mjs
  src/content-tags-drawer/tags-sidebar-controls/TagsSidebarHeader.jsx
  src/content-tags-drawer/tags-sidebar-controls/TagsSidebarHeader.test.jsx
  src/course-outline/CourseOutline.jsx
  src/course-outline/CourseOutline.test.jsx
  src/course-outline/__mocks__/index.js
  src/course-outline/card-header/CardHeader.jsx
  src/course-outline/card-header/CardHeader.test.jsx
  src/course-outline/data/api.js
  src/course-outline/data/api.test.js
  src/course-outline/data/apiHooks.jsx
  src/course-outline/drag-helper/DragContextProvider.jsx
  src/course-outline/section-card/SectionCard.jsx
  src/course-outline/section-card/SectionCard.test.jsx
  src/course-outline/status-bar/StatusBar.jsx
  src/course-outline/status-bar/StatusBar.test.jsx
  src/course-outline/status-bar/messages.js
  src/course-outline/subsection-card/SubsectionCard.jsx
  src/course-outline/subsection-card/SubsectionCard.test.jsx
  src/course-outline/unit-card/UnitCard.jsx
  src/course-outline/unit-card/UnitCard.test.jsx
  src/course-unit/CourseUnit.test.jsx
  src/generic/__mocks__/contentTagsCount.js
  src/generic/__mocks__/index.js
  src/generic/data/api.js
  src/generic/data/api.test.js
  src/generic/data/apiHooks.js
  src/generic/data/apiHooks.test.js
Labels: open-source-contribution
