Repository openedx/frontend-app-authoring, pull requests merged in 2024-11, with the labels that each got.

#1446 fix: enable publish button on library after component edit [FC-0062]
  src/library-authoring/data/apiHooks.ts
Labels: open-source-contribution, FC

#1447 fix: enable publish button on library after component edit [sumac] [FC-0062]
  src/library-authoring/data/apiHooks.ts
Labels: open-source-contribution, backport, FC

#1444 feat: handle unsaved changes in text & problem editors
  package-lock.json
  package.json
  src/course-unit/course-xblock/CourseXBlock.jsx
  src/course-unit/course-xblock/CourseXBlock.test.jsx
  src/editors/containers/EditorContainer/index.test.tsx
  src/editors/containers/EditorContainer/index.tsx
  src/editors/containers/ProblemEditor/components/EditProblemView/__snapshots__/index.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/hooks.js
  src/editors/containers/ProblemEditor/components/EditProblemView/hooks.test.js
  src/editors/containers/ProblemEditor/components/EditProblemView/index.jsx
  src/editors/containers/TextEditor/__snapshots__/index.test.jsx.snap
  src/editors/containers/TextEditor/hooks.js
  src/editors/containers/TextEditor/hooks.test.jsx
  src/editors/containers/TextEditor/index.jsx
  src/editors/containers/TextEditor/index.test.jsx
  src/editors/containers/VideoEditor/__snapshots__/index.test.tsx.snap
  src/editors/containers/VideoEditor/index.tsx
  src/editors/data/redux/problem/reducers.js
  src/editors/data/redux/problem/reducers.test.js
  src/editors/data/redux/problem/selectors.js
  src/generic/promptIfDirty/usePromptIfDirty.test.jsx
  src/generic/promptIfDirty/usePromptIfDirty.ts
  src/textbooks/textbook-form/TextbookForm.jsx
Labels: open-source-contribution

#1459 chore: hide transcripts in video preview for library
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoPreviewWidget/index.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoPreviewWidget/index.test.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/index.tsx
Labels: open-source-contribution

#1473 [sumac] Hide / error on Libraries v2 pages if !librariesV2Enabled [FC-0062]
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/add-content/AddContentWorkflow.test.tsx
  src/library-authoring/add-content/PickLibraryContentModal.test.tsx
  src/library-authoring/component-picker/ComponentPicker.test.tsx
  src/library-authoring/messages.ts
  src/studio-home/StudioHome.tsx
  src/studio-home/hooks.jsx
Labels: open-source-contribution

#1471 [sumac] feat: handle unsaved changes in text & problem editors (#1444)
  package-lock.json
  package.json
  src/course-unit/course-xblock/CourseXBlock.jsx
  src/course-unit/course-xblock/CourseXBlock.test.jsx
  src/editors/containers/EditorContainer/index.test.tsx
  src/editors/containers/EditorContainer/index.tsx
  src/editors/containers/ProblemEditor/components/EditProblemView/__snapshots__/index.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/hooks.js
  src/editors/containers/ProblemEditor/components/EditProblemView/hooks.test.js
  src/editors/containers/ProblemEditor/components/EditProblemView/index.jsx
  src/editors/containers/TextEditor/__snapshots__/index.test.jsx.snap
  src/editors/containers/TextEditor/hooks.js
  src/editors/containers/TextEditor/hooks.test.jsx
  src/editors/containers/TextEditor/index.jsx
  src/editors/containers/TextEditor/index.test.jsx
  src/editors/containers/VideoEditor/__snapshots__/index.test.tsx.snap
  src/editors/containers/VideoEditor/index.tsx
  src/editors/data/redux/problem/reducers.js
  src/editors/data/redux/problem/reducers.test.js
  src/editors/data/redux/problem/selectors.js
  src/generic/promptIfDirty/usePromptIfDirty.test.jsx
  src/generic/promptIfDirty/usePromptIfDirty.ts
  src/textbooks/textbook-form/TextbookForm.jsx
Labels: open-source-contribution

#1468 fix: show a more detailed error on Bad Request
  src/library-authoring/add-content/AddContentContainer.test.tsx
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/add-content/messages.ts
Labels: open-source-contribution

#1472 [sumac] fix: add component to collection on paste [FC-0062] (#1450)
  src/library-authoring/add-content/AddContentContainer.test.tsx
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/add-content/messages.ts
Labels: open-source-contribution

#1461 fix: add spacing to searchbar and simplify render conditions [FC-0062]
  src/library-authoring/component-picker/SelectLibrary.tsx
Labels: open-source-contribution

#1476 [sumac] fix: add spacing to searchbar and simplify render conditions [FC-0062]
  src/library-authoring/component-picker/SelectLibrary.tsx
Labels: open-source-contribution

#1478 [sumac] fix: show a more detailed error on Bad Request [FC-0062]
  src/library-authoring/add-content/AddContentContainer.test.tsx
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/add-content/messages.ts
Labels: open-source-contribution

#1443 feat: simplify library home [FC-0062]
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/LibraryContent.test.tsx
  src/library-authoring/LibraryContent.tsx
  src/library-authoring/LibraryHome.tsx
  src/library-authoring/LibraryRecentlyModified.tsx
  src/library-authoring/__mocks__/collection-search.json
  src/library-authoring/__mocks__/library-search.json
  src/library-authoring/collections/LibraryCollectionComponents.tsx
  src/library-authoring/collections/LibraryCollectionPage.test.tsx
  src/library-authoring/collections/LibraryCollectionPage.tsx
  src/library-authoring/collections/LibraryCollections.tsx
  src/library-authoring/collections/messages.ts
  src/library-authoring/component-info/ComponentInfo.tsx
  src/library-authoring/component-info/ManageCollections.test.tsx
  src/library-authoring/component-info/ManageCollections.tsx
  src/library-authoring/component-picker/ComponentPicker.test.tsx
  src/library-authoring/components/LibraryComponents.test.tsx
  src/library-authoring/components/LibraryComponents.tsx
  src/library-authoring/components/LibrarySection.tsx
  src/library-authoring/components/index.ts
  src/library-authoring/messages.ts
  src/search-manager/SearchManager.ts
  src/search-manager/data/api.ts
  src/search-manager/data/apiHooks.ts
  src/search-modal/SearchResults.tsx
  src/search-modal/SearchUI.test.tsx
  src/search-modal/__mocks__/empty-search-result.json
Labels: open-source-contribution, FC

#1372 chore: [FC-0070] Remove backend redirects (use SPA functionality)
  package-lock.json
  package.json
  src/CourseAuthoringPage.jsx
  src/CourseAuthoringPage.test.jsx
  src/CourseAuthoringRoutes.test.jsx
  src/course-checklist/ChecklistSection/ChecklistItemBody.jsx
  src/course-checklist/ChecklistSection/ChecklistItemComment.jsx
  src/course-checklist/ChecklistSection/ChecklistSection.jsx
  src/course-checklist/ChecklistSection/ChecklistSection.test.jsx
  src/course-checklist/CourseChecklist.jsx
  src/course-checklist/utils.js
  src/course-outline/hooks.jsx
  src/course-outline/status-bar/StatusBar.jsx
  src/course-unit/breadcrumbs/Breadcrumbs.jsx
  src/course-unit/breadcrumbs/Breadcrumbs.test.jsx
  src/custom-pages/CustomPages.jsx
  src/custom-pages/CustomPages.test.jsx
  src/data/api.js
  src/data/selectors.js
  src/data/slice.js
  src/data/thunks.js
  src/generic/help-sidebar/HelpSidebar.jsx
  src/generic/help-sidebar/HelpSidebarLink.jsx
  src/generic/help-sidebar/HelpSidebarLink.test.jsx
  src/grading-settings/grading-sidebar/GradingSidebar.test.jsx
  src/group-configurations/experiment-configurations-section/ExperimentConfigurationsSection.test.jsx
  src/group-configurations/experiment-configurations-section/index.jsx
  src/group-configurations/index.jsx
  src/header/Header.tsx
  src/header/hooks.js
  src/hooks.test.ts
  src/hooks.ts
  src/pages-and-resources/PagesAndResources.jsx
  src/pages-and-resources/pages/PageCard.jsx
  src/pages-and-resources/pages/PageCard.test.jsx
  src/pages-and-resources/pages/PageGrid.jsx
  src/pages-and-resources/pages/PageSettingButton.jsx
  src/pages-and-resources/pages/PageSettingButton.test.jsx
  src/studio-home/StudioHome.test.jsx
  src/studio-home/card-item/CardItem.test.tsx
  src/studio-home/card-item/index.tsx
  src/studio-home/hooks.jsx
  src/studio-home/verify-email-layout/VerifyEmailLayout.test.jsx
  src/textbooks/Textbooks.jsx
  src/textbooks/hooks.jsx
  src/utils.js
  src/utils.test.js
Labels: open-source-contribution, create-sandbox, FC

#1375 feat: [FC-0070] render iframe with xblocks
  src/course-unit/CourseUnit.jsx
  src/course-unit/CourseUnit.scss
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/constants.js
  src/course-unit/course-sequence/hooks.test.js
  src/course-unit/course-xblock/CourseXBlock.jsx
  src/course-unit/course-xblock/CourseXBlock.scss
  src/course-unit/course-xblock/CourseXBlock.test.jsx
  src/course-unit/course-xblock/constants.js
  src/course-unit/course-xblock/messages.js
  src/course-unit/course-xblock/xblock-messages/XBlockMessages.jsx
  src/course-unit/course-xblock/xblock-messages/XBlockMessages.test.jsx
  src/course-unit/course-xblock/xblock-messages/utils.js
  src/course-unit/course-xblock/xblock-messages/utils.test.js
  src/course-unit/data/api.js
  src/course-unit/data/slice.js
  src/course-unit/data/thunk.js
  src/course-unit/hooks.jsx
  src/course-unit/xblock-container-iframe/hooks.tsx
  src/course-unit/xblock-container-iframe/index.tsx
  src/course-unit/xblock-container-iframe/messages.ts
  src/course-unit/xblock-container-iframe/tests/XblockContainerIframe.test.tsx
  src/course-unit/xblock-container-iframe/tests/hooks.test.tsx
  src/generic/hooks/index.tsx
  src/generic/hooks/tests/useEventListener.test.tsx
  src/generic/hooks/useEventListener.tsx
Labels: open-source-contribution, create-sandbox, FC

#1483 fix: infinite scroll bug on library page [FC-0062]
  src/hooks.ts
Labels: open-source-contribution

#1493 fix: [FC-0070] fixing broken tests
  src/hooks.test.ts
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/add-content/AddContentWorkflow.test.tsx
  src/library-authoring/add-content/PickLibraryContentModal.test.tsx
Labels: open-source-contribution

#1498 feat: show info banner in component picker [FC-0062]
  src/library-authoring/component-picker/ComponentPicker.test.tsx
  src/library-authoring/component-picker/ComponentPicker.tsx
  src/library-authoring/component-picker/messages.ts
Labels: open-source-contribution

#1501 [sumac] feat: show info banner in component picker (#1498)
  src/library-authoring/component-picker/ComponentPicker.test.tsx
  src/library-authoring/component-picker/ComponentPicker.tsx
  src/library-authoring/component-picker/messages.ts
Labels: open-source-contribution

#1490 fix: remove unnecessary toast notification on adding component
  src/hooks.test.ts
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/add-content/AddContentContainer.test.tsx
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/add-content/AddContentWorkflow.test.tsx
  src/library-authoring/add-content/PickLibraryContentModal.test.tsx
  src/library-authoring/add-content/messages.ts
  src/library-authoring/common/context.tsx
  src/library-authoring/components/ComponentEditorModal.tsx
  src/testUtils.tsx
Labels: open-source-contribution

#1480 feat: enable problem bank button functionality [FC-0062]
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/__mocks__/courseSectionVertical.js
  src/course-unit/add-component/AddComponent.jsx
  src/course-unit/add-component/AddComponent.test.jsx
  src/course-unit/add-component/add-component-btn/index.jsx
  src/course-unit/add-component/add-component-modals/ComponentModalView.jsx
  src/course-unit/data/api.js
  src/generic/NewsstandIcon.tsx
  src/generic/block-type-utils/constants.ts
  src/library-authoring/LibraryLayout.tsx
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/add-content/PickLibraryContentModal.test.tsx
  src/library-authoring/add-content/PickLibraryContentModal.tsx
  src/library-authoring/common/context.tsx
  src/library-authoring/component-picker/ComponentPicker.tsx
  src/library-authoring/component-picker/ComponentPickerModal.tsx
  src/library-authoring/component-picker/index.ts
Labels: open-source-contribution

#1382 [BB-9078] Adjust styling when title is truncated
  src/course-outline/card-header/CardHeader.scss
Labels: open-source-contribution

#1504 docs: minor README improvements
  README.rst
Labels: open-source-contribution

#1079 fix: error handling
  src/course-checklist/CourseChecklist.jsx
  src/course-checklist/CourseChecklist.test.jsx
  src/course-checklist/data/thunks.js
  src/course-outline/CourseOutline.jsx
  src/course-outline/CourseOutline.test.jsx
  src/course-outline/data/thunk.js
  src/course-outline/hooks.jsx
  src/course-team/CourseTeam.jsx
  src/course-team/CourseTeam.test.jsx
  src/course-team/data/thunk.js
  src/course-team/hooks.jsx
  src/course-updates/CourseUpdates.jsx
  src/course-updates/CourseUpdates.test.jsx
  src/course-updates/data/thunk.js
  src/export-page/CourseExportPage.jsx
  src/export-page/CourseExportPage.test.jsx
  src/export-page/data/thunks.js
  src/grading-settings/GradingSettings.jsx
  src/grading-settings/GradingSettings.test.jsx
  src/group-configurations/GroupConfigurations.test.jsx
  src/group-configurations/data/thunk.js
  src/group-configurations/hooks.jsx
  src/group-configurations/index.jsx
  src/import-page/CourseImportPage.jsx
  src/import-page/CourseImportPage.test.jsx
  src/import-page/data/thunks.js
  src/textbooks/Textbook.test.jsx
  src/textbooks/Textbooks.jsx
  src/textbooks/hooks.jsx
Labels: open-source-contribution, create-sandbox

#1495 [sumac] fix: simplify Library Home Page (v2)
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/LibraryContent.test.tsx
  src/library-authoring/LibraryContent.tsx
  src/library-authoring/LibraryHome.tsx
  src/library-authoring/LibraryRecentlyModified.tsx
  src/library-authoring/__mocks__/collection-search.json
  src/library-authoring/__mocks__/library-search.json
  src/library-authoring/collections/LibraryCollectionComponents.tsx
  src/library-authoring/collections/LibraryCollectionPage.test.tsx
  src/library-authoring/collections/LibraryCollectionPage.tsx
  src/library-authoring/collections/LibraryCollections.tsx
  src/library-authoring/collections/messages.ts
  src/library-authoring/component-info/ComponentInfo.tsx
  src/library-authoring/component-info/ManageCollections.test.tsx
  src/library-authoring/component-info/ManageCollections.tsx
  src/library-authoring/component-picker/ComponentPicker.test.tsx
  src/library-authoring/components/LibraryComponents.test.tsx
  src/library-authoring/components/LibraryComponents.tsx
  src/library-authoring/components/LibrarySection.tsx
  src/library-authoring/components/index.ts
  src/library-authoring/messages.ts
  src/search-manager/SearchManager.ts
  src/search-manager/data/api.ts
  src/search-manager/data/apiHooks.ts
  src/search-modal/SearchResults.tsx
  src/search-modal/SearchUI.test.tsx
  src/search-modal/__mocks__/empty-search-result.json
Labels: open-source-contribution

#1516 test: fix contentContainer test
  src/library-authoring/add-content/AddContentContainer.test.tsx
Labels: open-source-contribution

#1500 fix: TinyMce aux modal issues in text editors [FC-0062]
  src/editors/sharedComponents/TinyMceWidget/hooks.js
Labels: open-source-contribution

#1481 fix: Show published count component in library content picker [FC-0062]
  src/library-authoring/components/CollectionCard.test.tsx
  src/library-authoring/components/CollectionCard.tsx
  src/search-manager/data/api.ts
Labels: open-source-contribution

#1520 [sumac] fix: TinyMce aux modal issues in text editors [FC-0062] (#1500)
  src/editors/sharedComponents/TinyMceWidget/hooks.js
Labels: open-source-contribution

#1422 feat: [FC-0070] implement move xblock modal
  src/CourseAuthoringRoutes.jsx
  src/constants.js
  src/course-unit/CourseUnit.jsx
  src/course-unit/CourseUnit.scss
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/__mocks__/courseOutlineInfo.js
  src/course-unit/__mocks__/index.js
  src/course-unit/constants.js
  src/course-unit/context/hooks.test.tsx
  src/course-unit/context/hooks.tsx
  src/course-unit/context/iFrameContext.tsx
  src/course-unit/data/api.js
  src/course-unit/data/selectors.js
  src/course-unit/data/slice.js
  src/course-unit/data/thunk.js
  src/course-unit/header-title/HeaderTitle.jsx
  src/course-unit/hooks.jsx
  src/course-unit/index.js
  src/course-unit/messages.js
  src/course-unit/move-modal/components/CategoryIndicator.tsx
  src/course-unit/move-modal/components/EmptyMessage.tsx
  src/course-unit/move-modal/components/ModalLoader.tsx
  src/course-unit/move-modal/components/index.ts
  src/course-unit/move-modal/constants.ts
  src/course-unit/move-modal/hooks.tsx
  src/course-unit/move-modal/index.scss
  src/course-unit/move-modal/index.tsx
  src/course-unit/move-modal/interfaces.ts
  src/course-unit/move-modal/messages.ts
  src/course-unit/move-modal/moveModal.test.tsx
  src/course-unit/move-modal/utils.test.ts
  src/course-unit/move-modal/utils.ts
  src/course-unit/xblock-container-iframe/index.tsx
  src/course-unit/xblock-container-iframe/tests/XblockContainerIframe.test.tsx
Labels: open-source-contribution, create-sandbox, FC

#1521 [sumac] fix: Show published count component in library content picker (#1481)
  src/library-authoring/components/CollectionCard.test.tsx
  src/library-authoring/components/CollectionCard.tsx
  src/search-manager/data/api.ts
Labels: open-source-contribution, backport

#1528 [sumac] fix: remove unnecessary toast notification on adding component (#1490)
  src/library-authoring/add-content/AddContentContainer.test.tsx
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/add-content/messages.ts
  src/library-authoring/common/context.tsx
  src/library-authoring/components/ComponentEditorModal.tsx
  src/testUtils.tsx
Labels: open-source-contribution

#1527 fix: map image upload feature with enableImageUpload prop in TinyMceWidget
  src/editors/containers/ProblemEditor/components/EditProblemView/ExplanationWidget/__snapshots__/index.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/QuestionWidget/__snapshots__/index.test.jsx.snap
  src/editors/containers/TextEditor/__snapshots__/index.test.jsx.snap
  src/editors/sharedComponents/TinyMceWidget/__snapshots__/index.test.jsx.snap
  src/editors/sharedComponents/TinyMceWidget/hooks.js
  src/editors/sharedComponents/TinyMceWidget/index.jsx
  src/editors/sharedComponents/TinyMceWidget/index.test.jsx
  src/editors/sharedComponents/TinyMceWidget/pluginConfig.js
  src/generic/WysiwygEditor.jsx
Labels: open-source-contribution

#1506 feat: preview library block changes in course unit [FC-0062]
  src/course-outline/CourseOutline.test.jsx
  src/course-unit/CourseUnit.jsx
  src/course-unit/CourseUnit.scss
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/constants.js
  src/course-unit/data/api.js
  src/course-unit/data/apiHooks.ts
  src/course-unit/preview-changes/index.scss
  src/course-unit/preview-changes/index.test.tsx
  src/course-unit/preview-changes/index.tsx
  src/course-unit/preview-changes/messages.ts
  src/generic/delete-modal/DeleteModal.jsx
  src/library-authoring/LibraryBlock/LibraryBlock.tsx
  src/library-authoring/component-info/ComponentAdvancedAssets.tsx
  src/library-authoring/components/CollectionCard.tsx
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/library-info/LibraryPublishStatus.tsx
Labels: open-source-contribution

#1522 feat: show problem bank component picker on window msg [FC-0062]
  src/course-unit/add-component/AddComponent.jsx
  src/course-unit/add-component/AddComponent.test.jsx
  src/course-unit/add-component/messages.js
  src/course-unit/constants.js
Labels: open-source-contribution

#1529 fix: editor flicker after creating xblock
  src/editors/hooks.test.jsx
  src/editors/hooks.ts
Labels: open-source-contribution, backport

#1532 refactor: Convert more Taxonomy code to TypeScript
  src/content-tags-drawer/ContentTagsCollapsible.jsx
  src/content-tags-drawer/ContentTagsCollapsibleHelper.jsx
  src/content-tags-drawer/ContentTagsDrawer.tsx
  src/content-tags-drawer/ContentTagsDrawerHelper.jsx
  src/content-tags-drawer/TagOutlineIcon.tsx
  src/content-tags-drawer/common/context.js
  src/content-tags-drawer/common/context.ts
  src/content-tags-drawer/data/api.js
  src/content-tags-drawer/data/apiHooks.jsx
  src/content-tags-drawer/data/types.mjs
  src/content-tags-drawer/data/types.ts
  src/content-tags-drawer/messages.ts
  src/content-tags-drawer/utils.js
  src/content-tags-drawer/utils.ts
  src/taxonomy/common/context.js
  src/taxonomy/common/context.ts
  src/taxonomy/data/api.js
  src/taxonomy/data/apiHooks.js
  src/taxonomy/data/types.mjs
  src/taxonomy/data/types.ts
  src/taxonomy/tag-list/TagListTable.jsx
  src/taxonomy/tag-list/data/apiHooks.js
  src/taxonomy/tag-list/data/types.mjs
  src/taxonomy/tag-list/index.ts
  src/taxonomy/tag-list/messages.ts
  src/taxonomy/taxonomy-menu/TaxonomyMenu.jsx
Labels: open-source-contribution
