Repository openedx/frontend-app-authoring, pull requests merged in 2024-12, with the labels that each got.

#1536 refactor: Convert more Taxonomy code to TypeScript (2)
  src/taxonomy/TaxonomyLayout.test.tsx
  src/taxonomy/TaxonomyLayout.tsx
  src/taxonomy/TaxonomyListPage.test.tsx
  src/taxonomy/TaxonomyListPage.tsx
  src/taxonomy/data/api.test.ts
  src/taxonomy/data/api.ts
  src/taxonomy/data/apiHooks.ts
  src/taxonomy/delete-dialog/messages.ts
  src/taxonomy/export-modal/messages.ts
  src/taxonomy/import-tags/ImportTagsWizard.jsx
  src/taxonomy/import-tags/ImportTagsWizard.test.jsx
  src/taxonomy/import-tags/index.js
  src/taxonomy/import-tags/index.ts
  src/taxonomy/import-tags/messages.ts
  src/taxonomy/index.js
  src/taxonomy/index.ts
  src/taxonomy/manage-orgs/index.ts
  src/taxonomy/manage-orgs/messages.ts
  src/taxonomy/messages.ts
  src/taxonomy/system-defined-badge/messages.ts
  src/taxonomy/taxonomy-card/messages.ts
  src/taxonomy/taxonomy-detail/index.ts
  src/taxonomy/taxonomy-detail/messages.ts
  src/taxonomy/taxonomy-menu/index.ts
  src/taxonomy/taxonomy-menu/messages.ts
Labels: open-source-contribution

#1535 feat: preserve library sidebar tab while switching items
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/collections/CollectionInfo.tsx
  src/library-authoring/common/context.tsx
  src/library-authoring/component-info/ComponentInfo.tsx
Labels: open-source-contribution

#1537 refactor: Add TypeScript types for the Editors' Redux state
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/Tolerance/constants.ts
  src/editors/containers/ProblemEditor/index.test.tsx
  src/editors/containers/ProblemEditor/index.tsx
  src/editors/data/redux/app/index.ts
  src/editors/data/redux/app/reducer.ts
  src/editors/data/redux/app/selectors.test.ts
  src/editors/data/redux/app/selectors.ts
  src/editors/data/redux/index.js
  src/editors/data/redux/index.ts
  src/editors/data/redux/problem/index.ts
  src/editors/data/redux/problem/reducers.test.ts
  src/editors/data/redux/problem/reducers.ts
  src/editors/data/redux/problem/selectors.test.ts
  src/editors/data/redux/problem/selectors.ts
  src/editors/data/redux/thunkActions/problem.test.ts
  src/editors/data/store.ts
  src/editors/utils/keyStore.ts
  src/generic/key-utils.ts
Labels: open-source-contribution

#1534 fix: Show published OLX in Library Content Picker [FC-0062]
  src/library-authoring/component-info/ComponentAdvancedInfo.test.tsx
  src/library-authoring/component-info/ComponentAdvancedInfo.tsx
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
Labels: open-source-contribution, FC

#1545 fix: content libraries permission [FC-0062]
  src/studio-home/StudioHome.tsx
  src/studio-home/__mocks__/studioHomeMock.js
  src/studio-home/factories/mockApiResponses.jsx
Labels: open-source-contribution, FC

#1548 fix: legacy library link
  src/studio-home/card-item/index.tsx
Labels: open-source-contribution

#1546 [sumac] fix: Show published OLX in Library Content Picker [FC-0062] (#1534)
  src/library-authoring/component-info/ComponentAdvancedInfo.test.tsx
  src/library-authoring/component-info/ComponentAdvancedInfo.tsx
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
Labels: open-source-contribution, backport, FC

#1543 fix: Update error messages when adding user to library [FC-0062]
  src/generic/processing-notification/ProcessingNotification.test.jsx
  src/generic/processing-notification/index.jsx
  src/generic/toast-context/index.test.tsx
  src/library-authoring/library-team/LibraryTeam.test.tsx
  src/library-authoring/library-team/LibraryTeam.tsx
  src/library-authoring/library-team/messages.ts
Labels: open-source-contribution, FC

#1530 fix: avoid changing url when removing filters
  src/library-authoring/LibraryAuthoringPage.tsx
  src/search-manager/SearchManager.ts
Labels: open-source-contribution

#1551 fix: avoid changing url when removing filters (#1530)
  src/library-authoring/LibraryAuthoringPage.tsx
  src/search-manager/SearchManager.ts
Labels: open-source-contribution

#1550 [sumac] fix: Update error messages when adding user to library [FC-0062] (#1543)
  src/generic/processing-notification/ProcessingNotification.test.jsx
  src/generic/processing-notification/index.jsx
  src/generic/toast-context/index.test.tsx
  src/library-authoring/library-team/LibraryTeam.test.tsx
  src/library-authoring/library-team/LibraryTeam.tsx
  src/library-authoring/library-team/messages.ts
Labels: open-source-contribution, FC

#1497 fix: fetch proper courses when keyword searching with applied filters
  src/studio-home/tabs-section/courses-tab/courses-filters/index.jsx
Labels: open-source-contribution

#1539 refactor: split up library context
  src/library-authoring/EmptyStates.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/LibraryContent.test.tsx
  src/library-authoring/LibraryContent.tsx
  src/library-authoring/LibraryLayout.tsx
  src/library-authoring/add-content/AddContentContainer.test.tsx
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/add-content/PickLibraryContentModal.test.tsx
  src/library-authoring/add-content/PickLibraryContentModal.tsx
  src/library-authoring/collections/CollectionDetails.test.tsx
  src/library-authoring/collections/CollectionDetails.tsx
  src/library-authoring/collections/CollectionInfo.tsx
  src/library-authoring/collections/CollectionInfoHeader.test.tsx
  src/library-authoring/collections/CollectionInfoHeader.tsx
  src/library-authoring/collections/LibraryCollectionComponents.tsx
  src/library-authoring/collections/LibraryCollectionPage.tsx
  src/library-authoring/common/context.tsx
  src/library-authoring/common/context/ComponentPickerContext.tsx
  src/library-authoring/common/context/LibraryContext.tsx
  src/library-authoring/common/context/SidebarContext.tsx
  src/library-authoring/component-info/ComponentAdvancedAssets.tsx
  src/library-authoring/component-info/ComponentAdvancedInfo.test.tsx
  src/library-authoring/component-info/ComponentAdvancedInfo.tsx
  src/library-authoring/component-info/ComponentDetails.test.tsx
  src/library-authoring/component-info/ComponentDetails.tsx
  src/library-authoring/component-info/ComponentInfo.test.tsx
  src/library-authoring/component-info/ComponentInfo.tsx
  src/library-authoring/component-info/ComponentInfoHeader.test.tsx
  src/library-authoring/component-info/ComponentInfoHeader.tsx
  src/library-authoring/component-info/ComponentManagement.test.tsx
  src/library-authoring/component-info/ComponentManagement.tsx
  src/library-authoring/component-info/ComponentPreview.test.tsx
  src/library-authoring/component-info/ComponentPreview.tsx
  src/library-authoring/component-info/ManageCollections.test.tsx
  src/library-authoring/component-info/ManageCollections.tsx
  src/library-authoring/component-picker/ComponentPicker.tsx
  src/library-authoring/components/CollectionCard.test.tsx
  src/library-authoring/components/CollectionCard.tsx
  src/library-authoring/components/ComponentCard.test.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/ComponentDeleter.test.tsx
  src/library-authoring/components/ComponentDeleter.tsx
  src/library-authoring/components/ComponentEditorModal.tsx
  src/library-authoring/create-collection/CreateCollectionModal.tsx
  src/library-authoring/legacy-integration/PreviewChangesEmbed.tsx
  src/library-authoring/library-info/LibraryInfo.test.tsx
  src/library-authoring/library-info/LibraryInfo.tsx
  src/library-authoring/library-info/LibraryInfoHeader.test.tsx
  src/library-authoring/library-info/LibraryInfoHeader.tsx
  src/library-authoring/library-info/LibraryPublishStatus.tsx
  src/library-authoring/library-sidebar/LibrarySidebar.tsx
  src/library-authoring/library-team/LibraryTeam.test.tsx
  src/library-authoring/library-team/LibraryTeam.tsx
  src/library-authoring/library-team/LibraryTeamModal.tsx
Labels: open-source-contribution

#1556 feat: undo component delete [FC-0076]
  src/generic/delete-modal/DeleteModal.jsx
  src/library-authoring/components/ComponentDeleter.test.tsx
  src/library-authoring/components/ComponentDeleter.tsx
  src/library-authoring/components/messages.ts
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/api.test.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
Labels: open-source-contribution

#1573 refactor: improve library sub header
  src/hooks.ts
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/collections/LibraryCollectionPage.test.tsx
  src/library-authoring/collections/LibraryCollectionPage.tsx
  src/library-authoring/collections/messages.ts
  src/search-manager/FilterByBlockType.tsx
Labels: open-source-contribution

#1576 fix: disable filter by block on collections tab [FC-0076]
  src/library-authoring/LibraryAuthoringPage.tsx
  src/search-manager/FilterByBlockType.tsx
Labels: open-source-contribution, FC
