Repository openedx/frontend-app-authoring, pull requests merged in 2025-09, with the labels that each got.

#2412 feat: add legacy library alert
  src/studio-home/tabs-section/libraries-tab/MigrateLegacyLibrariesAlert.tsx
  src/studio-home/tabs-section/libraries-tab/index.jsx
  src/studio-home/tabs-section/libraries-tab/index.tsx
  src/studio-home/tabs-section/messages.ts
Labels: open-source-contribution

#2399 feat: Secondary publish workflow for components [FC-0097]
  src/library-authoring/LibraryAuthoringPage.scss
  src/library-authoring/common/context/SidebarContext.tsx
  src/library-authoring/component-info/ComponentInfo.test.tsx
  src/library-authoring/component-info/ComponentInfo.tsx
  src/library-authoring/component-info/ComponentPublisher.tsx
  src/library-authoring/component-info/ComponentUsageTab.test.tsx
  src/library-authoring/component-info/ComponentUsageTab.tsx
  src/library-authoring/component-info/messages.ts
  src/library-authoring/components/ComponentMenu.tsx
  src/library-authoring/components/PublishConfirmationModal.tsx
  src/library-authoring/containers/ContainerInfo.tsx
  src/library-authoring/containers/ContainerPublishStatus.tsx
  src/library-authoring/containers/ContainerPublisher.tsx
  src/library-authoring/containers/ContainerUsage.tsx
  src/library-authoring/containers/index.scss
  src/library-authoring/containers/index.tsx
  src/library-authoring/containers/messages.ts
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.test.tsx
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/generic/index.scss
  src/library-authoring/generic/publish-status-buttons/PublishDraftButton.tsx
  src/library-authoring/generic/publish-status-buttons/PublishedChip.tsx
  src/library-authoring/generic/publish-status-buttons/index.scss
  src/library-authoring/generic/publish-status-buttons/index.tsx
  src/library-authoring/generic/publish-status-buttons/messages.ts
  src/library-authoring/hierarchy/ItemHierarchy.tsx
  src/library-authoring/hierarchy/ItemHierarchyPublisher.tsx
  src/library-authoring/hierarchy/index.scss
  src/library-authoring/hierarchy/messages.ts
  src/library-authoring/index.scss
  src/library-authoring/section-subsections/LibraryContainerChildren.tsx
  src/library-authoring/section-subsections/messages.ts
Labels: open-source-contribution, FC

#2434 [backport] fix: allow thumbnail upload on Videos page if no thumbnail (#2388)
  src/files-and-videos/videos-page/VideoThumbnail.jsx
  src/files-and-videos/videos-page/VideoThumbnail.test.jsx
Labels: open-source-contribution

#2302 feat: `add-to-cc-board` Github action created.
  .github/workflows/add-to-cc-board.yml
Labels: open-source-contribution

#2443 test: Add Node 24 to CI matrix
  .github/workflows/validate.yml
  src/library-authoring/component-info/ComponentManagement.test.tsx
Labels: open-source-contribution

#2417 feat: show migration status in libraries list [FC-0097]
  src/generic/key-utils.ts
  src/studio-home/card-item/index.tsx
  src/studio-home/data/api.ts
  src/studio-home/data/apiHooks.ts
  src/studio-home/data/thunks.js
  src/studio-home/factories/mockApiResponses.tsx
  src/studio-home/messages.ts
  src/studio-home/scss/StudioHome.scss
  src/studio-home/tabs-section/TabsSection.test.tsx
  src/studio-home/tabs-section/index.tsx
  src/studio-home/tabs-section/libraries-tab/index.tsx
Labels: open-source-contribution, core contributor, FC

#2464 feat: container library-course sync diff prevew [FC-0097]
  src/container-comparison/ChildrenPreview.tsx
  src/container-comparison/CompareContainersWidget.test.tsx
  src/container-comparison/CompareContainersWidget.tsx
  src/container-comparison/ContainerRow.test.tsx
  src/container-comparison/ContainerRow.tsx
  src/container-comparison/data/api.mock.ts
  src/container-comparison/data/apiHooks.ts
  src/container-comparison/messages.ts
  src/container-comparison/types.ts
  src/container-comparison/utils.test.ts
  src/container-comparison/utils.ts
  src/course-outline/data/apiHooks.ts
  src/course-outline/hooks.jsx
  src/course-outline/section-card/SectionCard.test.tsx
  src/course-outline/subsection-card/SubsectionCard.test.tsx
  src/course-outline/unit-card/UnitCard.test.tsx
  src/course-unit/data/api.ts
  src/course-unit/data/thunk.js
  src/course-unit/data/types.ts
  src/course-unit/preview-changes/index.test.tsx
  src/course-unit/preview-changes/index.tsx
  src/data/types.ts
  src/generic/key-utils.test.ts
  src/generic/key-utils.ts
  src/library-authoring/component-comparison/CompareChangesWidget.tsx
  src/library-authoring/component-comparison/messages.ts
  src/library-authoring/data/api.mocks.ts
Labels: open-source-contribution, core contributor, FC

#2449 feat: New modal to sync changes for standalone text components [FC-0097]
  src/course-libraries/CourseLibraries.test.tsx
  src/course-libraries/ReviewTabContent.tsx
  src/course-libraries/__mocks__/publishableEntityLinks.json
  src/course-libraries/data/api.ts
  src/course-unit/data/api.ts
  src/course-unit/preview-changes/index.scss
  src/course-unit/preview-changes/index.test.tsx
  src/course-unit/preview-changes/index.tsx
  src/course-unit/preview-changes/messages.ts
  src/generic/key-utils.ts
  src/library-authoring/LibraryBlock/LibraryBlock.tsx
  src/library-authoring/component-comparison/CompareChangesWidget.tsx
  src/library-authoring/component-comparison/messages.ts
Labels: open-source-contribution
