Repository openedx/frontend-app-authoring, pull requests merged in 2025-07, with the labels that each got.

#2224 fix: Update add existing content icons in section/subsection pages
  src/library-authoring/add-content/AddContent.tsx
Labels: open-source-contribution

#2247 fix: increase sidebar width to prevent menu overflow
  src/library-authoring/LibraryAuthoringPage.scss
Labels: open-source-contribution

#2256 fix: open component with keyboard within unit page
  src/library-authoring/units/LibraryUnitBlocks.tsx
Labels: open-source-contribution

#2248 test: replacing snapshot tests with rtl tests part 15
  src/editors/containers/ProblemEditor/components/EditProblemView/ExplanationWidget/__snapshots__/index.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/ExplanationWidget/index.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/ExplanationWidget/index.test.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/ExplanationWidget/index.test.tsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/GeneralFeedback/__snapshots__/index.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/GeneralFeedback/index.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/GeneralFeedback/index.test.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/GeneralFeedback/index.test.tsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/index.test.jsx.snap
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/index.test.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/index.test.tsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/__snapshots__/index.test.jsx.snap
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/index.test.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/index.test.tsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/__snapshots__/index.test.jsx.snap
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/index.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/index.test.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/index.test.tsx
  src/plugin-slots/AdditionalCourseContentPluginSlot/__snapshots__/index.test.jsx.snap
  src/plugin-slots/AdditionalCourseContentPluginSlot/index.test.jsx
  src/plugin-slots/AdditionalCourseContentPluginSlot/index.test.tsx
Labels: open-source-contribution, mao-onboarding

#2228 refactor: remove selected rows when deleting or adding elements
  src/files-and-videos/files-page/FilesPage.test.jsx
  src/files-and-videos/files-page/data/slice.js
  src/files-and-videos/generic/DeleteConfirmationModal.jsx
  src/files-and-videos/generic/FileTable.jsx
  src/files-and-videos/generic/table-components/TableActions.jsx
  src/files-and-videos/generic/table-components/TableActions.test.jsx
Labels: open-source-contribution

#2236 test: replacing snapshot tests with rtl tests part 14
  src/editors/containers/ProblemEditor/components/EditProblemView/QuestionWidget/__snapshots__/index.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/QuestionWidget/index.test.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/QuestionWidget/index.test.tsx
  src/editors/containers/VideoEditor/__snapshots__/index.test.tsx.snap
  src/editors/containers/VideoEditor/index.test.tsx
  src/editors/sharedComponents/ImageUploadModal/SelectImageModal/__snapshots__/index.test.jsx.snap
  src/editors/sharedComponents/ImageUploadModal/SelectImageModal/index.test.tsx
  src/editors/sharedComponents/ImageUploadModal/__snapshots__/index.test.jsx.snap
  src/editors/sharedComponents/ImageUploadModal/index.test.tsx
  src/plugin-slots/CourseOutlineHeaderActionsSlot/__snapshots__/index.test.jsx.snap
  src/plugin-slots/CourseOutlineHeaderActionsSlot/index.test.tsx
Labels: open-source-contribution, mao-onboarding

#2268 Remove unused <EditorContainer> and URL route
  src/CourseAuthoringRoutes.jsx
  src/CourseAuthoringRoutes.test.jsx
  src/editors/EditorContainer.test.tsx
  src/editors/EditorContainer.tsx
  src/editors/example.jsx
Labels: open-source-contribution, mao-onboarding

#2266 Replacing pending no-shallow snapshots with rtl tests part 1
  src/editors/Placeholder.test.jsx
  src/editors/__snapshots__/Placeholder.test.jsx.snap
  src/editors/containers/VideoUploadEditor/VideoUploader.test.jsx
  src/editors/containers/VideoUploadEditor/__snapshots__/VideoUploader.test.jsx.snap
  src/editors/containers/VideoUploadEditor/__snapshots__/index.test.jsx.snap
  src/editors/containers/VideoUploadEditor/index.test.jsx
  src/editors/sharedComponents/FileInput/__snapshots__/index.test.jsx.snap
  src/editors/sharedComponents/FileInput/index.test.jsx
  src/editors/sharedComponents/SelectableBox/tests/SelectableBox.test.jsx
  src/editors/sharedComponents/SelectableBox/tests/__snapshots__/SelectableBox.test.jsx.snap
Labels: open-source-contribution, mao-onboarding

#2267 Replacing pending no-shallow snapshots with rtl tests part 2
  package.json
  src/editors/sharedComponents/SelectableBox/tests/SelectableBoxSet.test.jsx
  src/editors/sharedComponents/SelectableBox/tests/__snapshots__/SelectableBoxSet.test.jsx.snap
  src/studio-home/tabs-section/courses-tab/courses-filters/__snapshots__/index.test.jsx.snap
  src/studio-home/tabs-section/courses-tab/courses-filters/courses-filter-menu/__snapshots__/index.test.jsx.snap
  src/studio-home/tabs-section/courses-tab/courses-filters/courses-filter-menu/index.test.jsx
  src/studio-home/tabs-section/courses-tab/courses-filters/courses-order-filter-menu/__snapshots__/index.test.jsx.snap
  src/studio-home/tabs-section/courses-tab/courses-filters/courses-order-filter-menu/index.test.jsx
  src/studio-home/tabs-section/courses-tab/courses-filters/courses-types-filter-menu/__snapshots__/index.test.jsx.snap
  src/studio-home/tabs-section/courses-tab/courses-filters/courses-types-filter-menu/index.test.jsx
  src/studio-home/tabs-section/courses-tab/courses-filters/index.test.jsx
Labels: open-source-contribution, mao-onboarding

#2291 Fix broken StudioHome tests
  src/course-rerun/CourseRerun.test.jsx
  src/course-rerun/course-rerun-form/CourseRerunForm.test.jsx
  src/generic/create-or-rerun-course/CreateOrRerunCourseForm.test.jsx
  src/generic/create-or-rerun-course/factories/mockApiResponses.jsx
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/add-content/AddContentWorkflow.test.tsx
  src/library-authoring/add-content/PickLibraryContentModal.test.tsx
  src/library-authoring/create-library/CreateLibrary.test.tsx
  src/library-authoring/routes.test.tsx
  src/studio-home/StudioHome.test.jsx
  src/studio-home/StudioHome.test.tsx
  src/studio-home/StudioHome.tsx
  src/studio-home/__mocks__/index.js
  src/studio-home/__mocks__/studioHomeMock.ts
  src/studio-home/card-item/CardItem.test.tsx
  src/studio-home/collapsible-state-with-action/CollapsibleStateWithAction.test.jsx
  src/studio-home/create-new-course-form/CourseNewCourseForm.test.jsx
  src/studio-home/home-sidebar/HomeSidebar.test.jsx
  src/studio-home/processing-courses/ProcessingCourses.test.jsx
  src/studio-home/tabs-section/TabsSection.test.tsx
  src/studio-home/tabs-section/courses-tab/index.test.tsx
Labels: open-source-contribution, core contributor

#2299 Replacing of injectIntl with useIntl() part 2
  src/accessibility-page/AccessibilityForm/AccessibilityForm.jsx
  src/advanced-settings/setting-card/SettingCard.jsx
  src/advanced-settings/setting-card/SettingCard.test.jsx
  src/course-outline/drag-helper/SortableItem.jsx
  src/export-page/export-stepper/ExportStepper.jsx
  src/export-page/export-stepper/ExportStepper.test.jsx
  src/files-and-videos/generic/FileTable.jsx
  src/files-and-videos/generic/InfoModal.jsx
  src/files-and-videos/generic/table-components/table-custom-columns/ActiveColumn.jsx
  src/files-and-videos/videos-page/VideoThumbnail.jsx
  src/generic/configure-modal/AdvancedTab.jsx
  src/generic/configure-modal/PrereqSettings.jsx
  src/grading-settings/assignment-section/assignments/AssignmentTypeName.jsx
  src/pages-and-resources/discussions/app-list/FeaturesTable.jsx
Labels: open-source-contribution, mao-onboarding

#2300 Replacing of injectIntl with useIntl() part 3
  src/accessibility-page/AccessibilityPage.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/components/Feedback/FeedbackBox.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.jsx
  src/editors/containers/TextEditor/index.jsx
  src/editors/containers/TextEditor/index.test.tsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoPreviewWidget/LanguageNamesWidget.jsx
  src/export-page/export-modal-error/ExportModalError.jsx
  src/files-and-videos/files-page/FileValidationModal.jsx
  src/files-and-videos/files-page/FilesPage.jsx
  src/files-and-videos/videos-page/transcript-settings/OrderTranscriptForm.jsx
  src/generic/course-stepper/index.jsx
  src/optimizer-page/CourseOptimizerPage.tsx
  src/pages-and-resources/discussions/app-config-form/apps/shared/AnonymousPostingFields.jsx
  src/pages-and-resources/discussions/app-config-form/apps/shared/InContextDiscussionFields.jsx
Labels: open-source-contribution, mao-onboarding

#2279 feat: library section subsection reuse in course [FC-0097]
  src/course-outline/CourseOutline.test.tsx
  src/course-outline/CourseOutline.tsx
  src/course-outline/OutlineAddChildButtons.test.tsx
  src/course-outline/OutlineAddChildButtons.tsx
  src/course-outline/card-header/CardHeader.test.tsx
  src/course-outline/card-header/CardHeader.tsx
  src/course-outline/data/api.ts
  src/course-outline/data/apiHooks.ts
  src/course-outline/data/selectors.ts
  src/course-outline/data/slice.ts
  src/course-outline/data/thunk.ts
  src/course-outline/data/types.ts
  src/course-outline/empty-placeholder/EmptyPlaceholder.jsx
  src/course-outline/empty-placeholder/EmptyPlaceholder.test.jsx
  src/course-outline/empty-placeholder/EmptyPlaceholder.test.tsx
  src/course-outline/empty-placeholder/EmptyPlaceholder.tsx
  src/course-outline/empty-placeholder/messages.js
  src/course-outline/hooks.jsx
  src/course-outline/messages.js
  src/course-outline/section-card/SectionCard.jsx
  src/course-outline/section-card/SectionCard.test.tsx
  src/course-outline/section-card/SectionCard.tsx
  src/course-outline/section-card/messages.js
  src/course-outline/subsection-card/SubsectionCard.test.tsx
  src/course-outline/subsection-card/SubsectionCard.tsx
  src/course-outline/subsection-card/messages.js
  src/course-outline/unit-card/UnitCard.test.tsx
  src/course-outline/unit-card/UnitCard.tsx
  src/course-outline/utils.jsx
  src/course-outline/xblock-status/StatusMessages.tsx
  src/course-outline/xblock-status/XBlockStatus.tsx
  src/course-unit/xblock-container-iframe/types.ts
  src/data/types.ts
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/index.tsx
  webpack.prod.config.js
Labels: open-source-contribution, core contributor, FC

#2329 feat: navigates subsection breadcrumb to first unit page
  src/CourseAuthoringRoutes.jsx
  src/course-outline/data/apiHooks.ts
  src/course-unit/SubsectionUnitRedirect.test.tsx
  src/course-unit/SubsectionUnitRedirect.tsx
  src/course-unit/__mocks__/courseSectionVertical.js
  src/course-unit/breadcrumbs/Breadcrumbs.test.tsx
  src/course-unit/breadcrumbs/Breadcrumbs.tsx
  src/course-unit/index.js
  src/course-unit/utils.ts
Labels: open-source-contribution, needs test run
