Repository openedx/frontend-app-authoring, pull requests merged in 2025-04, with the labels that each got.

#1766 feat: upgrade to react 18
  package-lock.json
  package.json
  plugins/course-apps/proctoring/Settings.test.jsx
  plugins/course-apps/xpert_unit_summary/Settings.test.jsx
  src/content-tags-drawer/ContentTagsCollapsible.test.jsx
  src/content-tags-drawer/ContentTagsDrawer.test.jsx
  src/content-tags-drawer/ContentTagsDropDownSelector.test.jsx
  src/content-tags-drawer/data/apiHooks.test.jsx
  src/course-libraries/data/apiHooks.test.tsx
  src/course-outline/CourseOutline.test.jsx
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/context/hooks.test.tsx
  src/course-unit/context/iFrameContext.tsx
  src/course-unit/course-sequence/hooks.test.js
  src/course-unit/hooks.test.jsx
  src/course-unit/move-modal/index.tsx
  src/course-unit/xblock-container-iframe/hooks/tests/hooks.test.tsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/index.tsx
  src/editors/containers/VideoGallery/index.test.jsx
  src/editors/containers/VideoUploadEditor/__snapshots__/VideoUploader.test.jsx.snap
  src/editors/containers/VideoUploadEditor/__snapshots__/index.test.jsx.snap
  src/editors/sharedComponents/RawEditor/index.test.jsx
  src/editors/sharedComponents/SelectableBox/tests/SelectableBoxSet.test.jsx
  src/editors/sharedComponents/TypeaheadDropdown/FormGroup.test.jsx
  src/editors/sharedComponents/TypeaheadDropdown/index.test.jsx
  src/generic/clipboard/hooks/useClipboard.test.tsx
  src/generic/data/apiHooks.test.tsx
  src/generic/help-sidebar/HelpSidebarLink.test.jsx
  src/generic/hooks/tests/useEventListener.test.tsx
  src/generic/prompt-if-dirty/PromptIfDirty.test.jsx
  src/generic/promptIfDirty/usePromptIfDirty.test.jsx
  src/grading-settings/credit-section/CreditSection.test.jsx
  src/grading-settings/grading-scale/react-ranger.test.js
  src/group-configurations/GroupConfigurations.test.jsx
  src/group-configurations/hooks.test.jsx
  src/header/hooks.test.js
  src/hooks.test.ts
  src/index.jsx
  src/library-authoring/component-info/ComponentAdvancedInfo.tsx
  src/library-authoring/create-collection/CreateCollectionModal.tsx
  src/library-authoring/data/apiHooks.test.tsx
  src/pages-and-resources/PagesAndResources.jsx
  src/pages-and-resources/SettingsComponent.jsx
  src/pages-and-resources/SettingsComponent.test.jsx
  src/pages-and-resources/discussions/DiscussionsSettings.test.jsx
  src/pages-and-resources/discussions/app-config-form/apps/openedx/OpenedXConfigForm.test.jsx
  src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/TopicItem.test.jsx
  src/search-manager/data/apiHooks.test.tsx
  src/setupTest.js
  src/studio-home/tabs-section/courses-tab/courses-filters/courses-filter-menu/__snapshots__/index.test.jsx.snap
  src/taxonomy/TaxonomyLayout.test.tsx
  src/taxonomy/data/apiHooks.test.jsx
  src/taxonomy/delete-dialog/index.jsx
  src/taxonomy/export-modal/index.jsx
  src/taxonomy/import-tags/ImportTagsWizard.jsx
  src/taxonomy/manage-orgs/ManageOrgsModal.jsx
  src/taxonomy/manage-orgs/data/api.test.jsx
  src/testUtils.tsx
  src/textbooks/textbook-form/TextbookForm.test.jsx
Labels: create-sandbox

#1775 chore: remove husky 🪓🐶
  package-lock.json
  package.json
Labels: open-source-contribution

#1725 feat: adds slots for in-context metrics in studio outline and unit views
  src/course-outline/CourseOutline.jsx
  src/course-outline/CourseOutline.scss
  src/course-outline/card-header/CardHeader.jsx
  src/course-outline/header-navigations/HeaderNavigations.jsx
  src/course-outline/header-navigations/HeaderNavigations.scss
  src/course-outline/subsection-card/SubsectionCard.jsx
  src/course-outline/unit-card/UnitCard.jsx
  src/course-unit/CourseUnit.jsx
  src/plugin-slots/CourseOutlineHeaderActionsSlot/README.md
  src/plugin-slots/CourseOutlineHeaderActionsSlot/__snapshots__/index.test.jsx.snap
  src/plugin-slots/CourseOutlineHeaderActionsSlot/images/mybutton_added_to_the_slot.png
  src/plugin-slots/CourseOutlineHeaderActionsSlot/index.jsx
  src/plugin-slots/CourseOutlineHeaderActionsSlot/index.test.jsx
  src/plugin-slots/CourseOutlineSubsectionCardExtraActionsSlot/README.md
  src/plugin-slots/CourseOutlineSubsectionCardExtraActionsSlot/images/custom_icon_button_inserted.png
  src/plugin-slots/CourseOutlineSubsectionCardExtraActionsSlot/images/default_view.png
  src/plugin-slots/CourseOutlineSubsectionCardExtraActionsSlot/index.jsx
  src/plugin-slots/CourseOutlineUnitCardExtraActionsSlot/README.md
  src/plugin-slots/CourseOutlineUnitCardExtraActionsSlot/images/custom_buttons_added_to_slot.png
  src/plugin-slots/CourseOutlineUnitCardExtraActionsSlot/images/default_view.png
  src/plugin-slots/CourseOutlineUnitCardExtraActionsSlot/index.jsx
  src/plugin-slots/CourseUnitHeaderActionsSlot/README.md
  src/plugin-slots/CourseUnitHeaderActionsSlot/__snapshots__/index.test.jsx.snap
  src/plugin-slots/CourseUnitHeaderActionsSlot/images/mybutton_added_to_slot.png
  src/plugin-slots/CourseUnitHeaderActionsSlot/index.jsx
  src/plugin-slots/CourseUnitHeaderActionsSlot/index.test.jsx
  src/plugin-slots/README.md
Labels: open-source-contribution, opencraft-sandbox

#1762 feat: library unit sidebar [FC-0083]
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/LibraryLayout.tsx
  src/library-authoring/collections/LibraryCollectionPage.tsx
  src/library-authoring/common/context/LibraryContext.tsx
  src/library-authoring/common/context/SidebarContext.tsx
  src/library-authoring/components/ContainerCard.tsx
  src/library-authoring/containers/ContainerInfoHeader.test.tsx
  src/library-authoring/containers/ContainerInfoHeader.tsx
  src/library-authoring/containers/UnitInfo.tsx
  src/library-authoring/containers/index.tsx
  src/library-authoring/containers/messages.ts
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.test.tsx
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/library-sidebar/LibrarySidebar.tsx
  src/library-authoring/routes.test.tsx
  src/library-authoring/routes.ts
Labels: open-source-contribution

#1774 feat: Unit card previews [FC-0083]
  src/library-authoring/components/BaseCard.scss
  src/library-authoring/components/BaseCard.tsx
  src/library-authoring/components/ContainerCard.test.tsx
  src/library-authoring/components/ContainerCard.tsx
  src/library-authoring/components/messages.ts
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.test.tsx
  src/library-authoring/data/apiHooks.ts
Labels: open-source-contribution, FC

#1727 fix: add user partition id when update groups
  plugins/course-apps/teams/Settings.jsx
Labels: open-source-contribution, create-sandbox

#1782 feat: add container tag support [FC-0083]
  src/content-tags-drawer/ContentTagsDrawer.tsx
  src/content-tags-drawer/ContentTagsDrawerHelper.jsx
  src/content-tags-drawer/data/api.js
  src/content-tags-drawer/data/apiHooks.jsx
  src/content-tags-drawer/index.ts
  src/library-authoring/component-info/ComponentManagement.test.tsx
  src/library-authoring/component-info/ComponentManagement.tsx
  src/library-authoring/containers/ContainerOrganize.test.tsx
  src/library-authoring/containers/ContainerOrganize.tsx
  src/library-authoring/containers/UnitInfo.tsx
  src/library-authoring/containers/messages.ts
  src/library-authoring/data/api.mocks.ts
Labels: open-source-contribution, FC

#1773 feat: Delete unit [FC-0083]
  src/generic/delete-modal/DeleteModal.jsx
  src/library-authoring/components/ContainerCard.test.tsx
  src/library-authoring/components/ContainerCard.tsx
  src/library-authoring/components/ContainerDeleter.tsx
  src/library-authoring/components/messages.ts
  src/library-authoring/containers/UnitInfo.test.tsx
  src/library-authoring/containers/UnitInfo.tsx
  src/library-authoring/data/api.test.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.test.tsx
  src/library-authoring/data/apiHooks.ts
Labels: open-source-contribution, FC

#1752 feat: Add plugins slots for sidebars and application
  src/course-outline/CourseOutline.jsx
  src/course-outline/outline-sidebar/OutlineSidebar.jsx
  src/course-unit/CourseUnit.jsx
  src/course-unit/sidebar/index.jsx
  src/course-unit/sidebar/index.tsx
  src/generic/help-sidebar/HelpSidebar.jsx
  src/plugin-slots/CourseAuthoringOutlineSidebarSlot/README.md
  src/plugin-slots/CourseAuthoringOutlineSidebarSlot/images/outline_sidebar_with_border.png
  src/plugin-slots/CourseAuthoringOutlineSidebarSlot/index.tsx
  src/plugin-slots/CourseAuthoringUnitSidebarSlot/README.md
  src/plugin-slots/CourseAuthoringUnitSidebarSlot/images/unit_sidebar_with_border.png
  src/plugin-slots/CourseAuthoringUnitSidebarSlot/index.tsx
Labels: open-source-contribution

#1729 feat: replace StudioFooter with StudioFooterSlot
  package-lock.json
  package.json
  src/CourseAuthoringPage.jsx
  src/accessibility-page/AccessibilityPage.jsx
  src/course-rerun/index.jsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/collections/LibraryCollectionPage.tsx
  src/library-authoring/create-library/CreateLibrary.tsx
  src/plugin-slots/README.md
  src/plugin-slots/StudioFooterSlot/README.md
  src/plugin-slots/StudioFooterSlot/images/custom_footer.png
  src/plugin-slots/StudioFooterSlot/images/default_studio_footer.png
  src/studio-home/StudioHome.tsx
  src/taxonomy/TaxonomyLayout.tsx
Labels: open-source-contribution

#1779 feat: library unit page skeleton [FC-0083]
  src/CourseAuthoringRoutes.jsx
  src/constants.js
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/add-component/AddComponent.jsx
  src/course-unit/add-component/AddComponent.test.jsx
  src/course-unit/constants.js
  src/course-unit/hooks.jsx
  src/course-unit/hooks.test.jsx
  src/course-unit/index.js
  src/course-unit/move-modal/hooks.tsx
  src/course-unit/move-modal/moveModal.test.tsx
  src/course-unit/preview-changes/index.test.tsx
  src/course-unit/preview-changes/index.tsx
  src/course-unit/sidebar/PublishControls.jsx
  src/course-unit/xblock-container-iframe/hooks/index.ts
  src/course-unit/xblock-container-iframe/hooks/tests/hooks.test.tsx
  src/course-unit/xblock-container-iframe/hooks/types.ts
  src/course-unit/xblock-container-iframe/hooks/useIFrameBehavior.tsx
  src/course-unit/xblock-container-iframe/index.tsx
  src/custom-pages/CustomPages.jsx
  src/editors/AdvancedEditor.tsx
  src/editors/sharedComponents/DraggableList/DraggableList.jsx
  src/editors/sharedComponents/DraggableList/SortableItem.jsx
  src/generic/hooks/context/hooks.test.tsx
  src/generic/hooks/context/hooks.tsx
  src/generic/hooks/context/iFrameContext.tsx
  src/generic/hooks/tests/hooks.test.tsx
  src/generic/hooks/useIframeBehavior.tsx
  src/generic/hooks/useIframeContent.tsx
  src/generic/hooks/useIframeMessages.tsx
  src/generic/hooks/useLoadBearingHook.tsx
  src/generic/types.ts
  src/library-authoring/LibraryBlock/LibraryBlock.tsx
  src/library-authoring/LibraryLayout.tsx
  src/library-authoring/collections/LibraryCollectionPage.tsx
  src/library-authoring/common/context/LibraryContext.tsx
  src/library-authoring/common/context/SidebarContext.tsx
  src/library-authoring/component-comparison/CompareChangesWidget.tsx
  src/library-authoring/component-info/ComponentInfo.tsx
  src/library-authoring/component-info/ComponentPreview.tsx
  src/library-authoring/components/ContainerCard.test.tsx
  src/library-authoring/components/ContainerCard.tsx
  src/library-authoring/containers/ContainerInfoHeader.tsx
  src/library-authoring/containers/UnitInfo.tsx
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.test.tsx
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/index.scss
  src/library-authoring/routes.ts
  src/library-authoring/units/LibraryUnitBlocks.tsx
  src/library-authoring/units/LibraryUnitPage.test.tsx
  src/library-authoring/units/LibraryUnitPage.tsx
  src/library-authoring/units/index.scss
  src/library-authoring/units/index.tsx
  src/library-authoring/units/messages.ts
Labels: open-source-contribution, FC

#1784 feat: Add component to Unit [FC-0083]
  src/editors/containers/EditorContainer/index.tsx
  src/generic/key-utils.test.ts
  src/generic/key-utils.ts
  src/library-authoring/LibraryLayout.tsx
  src/library-authoring/add-content/AddContent.test.tsx
  src/library-authoring/add-content/AddContent.tsx
  src/library-authoring/add-content/PickLibraryContentModal.tsx
  src/library-authoring/add-content/index.ts
  src/library-authoring/add-content/messages.ts
  src/library-authoring/common/context/LibraryContext.tsx
  src/library-authoring/create-unit/CreateUnitModal.tsx
  src/library-authoring/data/api.test.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.test.tsx
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/library-sidebar/LibrarySidebar.tsx
  src/library-authoring/units/LibraryUnitBlocks.tsx
  src/library-authoring/units/LibraryUnitPage.tsx
  src/library-authoring/units/messages.ts
Labels: open-source-contribution, FC

#1800 fix: Copy to clipboard would seemingly fail even if it worked [FC-0083]
  src/course-outline/CourseOutline.test.jsx
  src/course-outline/subsection-card/SubsectionCard.test.jsx
  src/course-outline/unit-card/UnitCard.test.jsx
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/sidebar/components/sidebar-footer/ActionButtons.test.jsx
  src/course-unit/xblock-container-iframe/hooks/tests/hooks.test.tsx
  src/generic/clipboard/hooks/useClipboard.test.tsx
  src/generic/clipboard/hooks/useClipboard.ts
  src/generic/data/api.mock.ts
  src/generic/hooks/tests/hooks.test.tsx
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryContent.test.tsx
  src/library-authoring/add-content/AddContent.test.tsx
  src/library-authoring/add-content/AddContentWorkflow.test.tsx
  src/library-authoring/collections/LibraryCollectionPage.test.tsx
  src/library-authoring/component-info/ComponentInfo.test.tsx
  src/library-authoring/components/ComponentCard.test.tsx
  src/library-authoring/units/LibraryUnitPage.test.tsx
Labels: open-source-contribution, FC

#1813 fix: auto adjust min height of xblock previews [FC-0083]
  src/editors/AdvancedEditor.tsx
  src/library-authoring/LibraryBlock/LibraryBlock.tsx
  src/library-authoring/component-comparison/CompareChangesWidget.tsx
  src/library-authoring/component-info/ComponentPreview.tsx
  src/library-authoring/units/LibraryUnitBlocks.tsx
Labels: open-source-contribution, FC

#1797 feat: add collections support for containers [FC-0083]
  src/course-unit/add-component/AddComponent.jsx
  src/index.jsx
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/__mocks__/collection-search.json
  src/library-authoring/add-content/AddContent.test.tsx
  src/library-authoring/add-content/AddContent.tsx
  src/library-authoring/add-content/PickLibraryContentModal.test.tsx
  src/library-authoring/add-content/PickLibraryContentModal.tsx
  src/library-authoring/collections/LibraryCollectionPage.test.tsx
  src/library-authoring/collections/LibraryCollectionPage.tsx
  src/library-authoring/common/context/LibraryContext.tsx
  src/library-authoring/component-info/ComponentManagement.tsx
  src/library-authoring/component-info/messages.ts
  src/library-authoring/component-picker/ComponentPicker.tsx
  src/library-authoring/components/AddComponentWidget.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/ContainerCard.tsx
  src/library-authoring/components/messages.ts
  src/library-authoring/containers/ContainerInfoHeader.tsx
  src/library-authoring/containers/ContainerOrganize.test.tsx
  src/library-authoring/containers/ContainerOrganize.tsx
  src/library-authoring/containers/UnitInfo.tsx
  src/library-authoring/containers/messages.ts
  src/library-authoring/create-unit/CreateUnitModal.tsx
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.test.tsx
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/generic/manage-collections/ManageCollections.test.tsx
  src/library-authoring/generic/manage-collections/ManageCollections.tsx
  src/library-authoring/generic/manage-collections/index.tsx
  src/library-authoring/generic/manage-collections/messages.ts
  src/library-authoring/units/LibraryUnitBlocks.tsx
  src/library-authoring/units/LibraryUnitPage.tsx
Labels: open-source-contribution, FC

#1817 fix: sort Advanced Blocks by default display name [FC-0076]
  src/library-authoring/add-content/AddContent.tsx
Labels: open-source-contribution, FC

#1810 feat: rename unit in LibraryUnitPage [FC-0083]
  src/generic/inplace-text-editor/InplaceTextEditor.test.tsx
  src/generic/inplace-text-editor/index.tsx
  src/generic/inplace-text-editor/messages.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/collections/CollectionInfoHeader.test.tsx
  src/library-authoring/collections/CollectionInfoHeader.tsx
  src/library-authoring/collections/messages.ts
  src/library-authoring/component-info/ComponentInfoHeader.test.tsx
  src/library-authoring/component-info/ComponentInfoHeader.tsx
  src/library-authoring/component-info/messages.ts
  src/library-authoring/containers/ContainerInfoHeader.test.tsx
  src/library-authoring/containers/ContainerInfoHeader.tsx
  src/library-authoring/containers/messages.ts
  src/library-authoring/units/LibraryUnitPage.test.tsx
  src/library-authoring/units/LibraryUnitPage.tsx
  src/library-authoring/units/messages.ts
Labels: open-source-contribution, FC

#1811 feat: add existing components to unit [FC-0083]
  src/library-authoring/add-content/AddContent.tsx
  src/library-authoring/add-content/PickLibraryContentModal.test.tsx
  src/library-authoring/add-content/PickLibraryContentModal.tsx
  src/library-authoring/add-content/index.ts
  src/library-authoring/add-content/messages.ts
  src/library-authoring/containers/UnitInfo.tsx
  src/library-authoring/units/LibraryUnitBlocks.tsx
  src/library-authoring/units/LibraryUnitPage.tsx
Labels: open-source-contribution, FC

#1812 feat: allow pasting units from a course into a library
  src/__mocks__/clipboardSubsection.js
  src/__mocks__/index.js
  src/generic/clipboard/hooks/useClipboard.test.tsx
  src/library-authoring/add-content/AddContent.test.tsx
  src/library-authoring/add-content/AddContent.tsx
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.test.tsx
Labels: open-source-contribution

#1819 fix: merge errors in previous commit
  src/library-authoring/collections/LibraryCollectionPage.test.tsx
  src/library-authoring/create-unit/CreateUnitModal.tsx
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/units/LibraryUnitPage.tsx
Labels: open-source-contribution

#1772 feat: lighter build by rewriting lodash imports
  src/course-libraries/CourseLibraries.tsx
  src/course-libraries/ReviewTabContent.tsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.js
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/GeneralFeedback/hooks.js
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ScoringCard.jsx
  src/editors/containers/ProblemEditor/data/OLXParser.js
  src/editors/containers/ProblemEditor/data/ReactStateOLXParser.js
  src/editors/containers/ProblemEditor/data/ReactStateSettingsParser.js
  src/editors/containers/ProblemEditor/data/SettingsParser.js
  src/editors/data/redux/problem/reducers.ts
  src/editors/data/redux/thunkActions/problem.ts
  src/editors/data/redux/thunkActions/video.js
  src/editors/sharedComponents/TypeaheadDropdown/FormGroup.jsx
  src/files-and-videos/generic/table-components/TableActions.jsx
  src/generic/course-upload-image/index.jsx
  src/pages-and-resources/discussions/app-config-form/apps/shared/DivisionByGroupFields.jsx
  src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-restrictions/DiscussionRestrictionItem.jsx
  src/pages-and-resources/discussions/app-config-form/apps/shared/discussion-topics/DiscussionTopics.jsx
  src/pages-and-resources/discussions/app-config-form/utils.js
  src/pages-and-resources/discussions/app-list/FeaturesTable.jsx
Labels: open-source-contribution

#1816 feat: reorder components in unit page [FC-00083]
  src/course-outline/CourseOutline.jsx
  src/course-outline/CourseOutline.scss
  src/course-outline/CourseOutline.test.jsx
  src/course-outline/drag-helper/DragContextProvider.jsx
  src/course-outline/drag-helper/DraggableList.jsx
  src/course-outline/drag-helper/SortableItem.jsx
  src/course-outline/drag-helper/SortableItem.scss
  src/course-outline/drag-helper/messages.js
  src/course-outline/drag-helper/utils.js
  src/course-outline/section-card/SectionCard.jsx
  src/course-outline/subsection-card/SubsectionCard.jsx
  src/course-outline/unit-card/UnitCard.jsx
  src/custom-pages/CustomPages.jsx
  src/generic/DraggableList/DraggableList.jsx
  src/generic/DraggableList/SortableItem.jsx
  src/generic/DraggableList/index.jsx
  src/generic/DraggableList/messages.js
  src/generic/styles.scss
  src/library-authoring/data/api.test.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.test.tsx
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/units/LibraryUnitBlocks.tsx
  src/library-authoring/units/LibraryUnitPage.test.tsx
  src/library-authoring/units/LibraryUnitPage.tsx
  src/library-authoring/units/messages.ts
Labels: open-source-contribution, FC

#1824 feat: Remove component from unit [FC-0083]
  src/library-authoring/collections/LibraryCollectionPage.test.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/ComponentMenu.tsx
  src/library-authoring/components/ContainerCard.tsx
  src/library-authoring/components/index.ts
  src/library-authoring/components/messages.ts
  src/library-authoring/data/api.test.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.test.tsx
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/units/LibraryUnitPage.test.tsx
Labels: open-source-contribution

#1827 feat: button to publish a container [FC-0083]
  src/library-authoring/containers/UnitInfo.test.tsx
  src/library-authoring/containers/UnitInfo.tsx
  src/library-authoring/containers/messages.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.test.tsx
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/units/LibraryUnitBlocks.tsx
Labels: open-source-contribution, FC

#1842 chore: simplify imports in library-authoring/data/apiHooks.ts
  src/library-authoring/data/apiHooks.ts
Labels: open-source-contribution

#1847 chore: Enable ora2 in libraries by default [FC-0076]
  .env
  .env.test
  src/library-authoring/add-content/AddContent.test.tsx
Labels: open-source-contribution

#1823 feat: rename component on unit page
  src/generic/inplace-text-editor/InplaceTextEditor.test.tsx
  src/generic/inplace-text-editor/index.tsx
  src/library-authoring/collections/CollectionInfoHeader.tsx
  src/library-authoring/component-info/ComponentInfoHeader.test.tsx
  src/library-authoring/component-info/ComponentInfoHeader.tsx
  src/library-authoring/containers/ContainerInfoHeader.tsx
  src/library-authoring/data/apiHooks.test.tsx
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/units/LibraryUnitBlocks.tsx
  src/library-authoring/units/LibraryUnitPage.test.tsx
  src/library-authoring/units/messages.ts
Labels: open-source-contribution

#1845 Enhance Sidebar Slot properties & fix a minor UI bug
  src/course-outline/CourseOutline.jsx
  src/course-unit/CourseUnit.jsx
  src/plugin-slots/CourseAuthoringOutlineSidebarSlot/README.md
  src/plugin-slots/CourseAuthoringOutlineSidebarSlot/index.tsx
  src/plugin-slots/CourseAuthoringUnitSidebarSlot/README.md
  src/plugin-slots/CourseAuthoringUnitSidebarSlot/images/unit_sidebar_with_problem_blocks_list.png
  src/plugin-slots/CourseAuthoringUnitSidebarSlot/index.tsx
Labels: open-source-contribution

#1825 feat: New Transcript widget state on video editors on creation workflow [FC-0076]
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/__snapshots__/index.test.jsx.snap
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/index.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/index.test.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/messages.js
Labels: open-source-contribution

#1805 feat: added markdown editor for editing problems in markdown format
  package-lock.json
  package.json
  src/editors/Editor.tsx
  src/editors/EditorContainer.test.jsx
  src/editors/EditorContainer.tsx
  src/editors/EditorPage.tsx
  src/editors/__snapshots__/EditorContainer.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/__snapshots__/index.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.js
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.test.js
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.test.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/messages.js
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/SwitchEditorCard.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/SwitchEditorCard.test.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/SwitchToAdvancedEditorCard.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/SwitchToAdvancedEditorCard.test.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/SwitchEditorCard.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/SwitchToAdvancedEditorCard.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/__snapshots__/index.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/hooks.js
  src/editors/containers/ProblemEditor/components/EditProblemView/hooks.test.js
  src/editors/containers/ProblemEditor/components/EditProblemView/index.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/index.test.jsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/hooks.js
  src/editors/containers/ProblemEditor/components/SelectTypeModal/hooks.test.js
  src/editors/data/constants/basicOlxTemplates/textInput.js
  src/editors/data/constants/basicProblemTemplates/dropdown.js
  src/editors/data/constants/basicProblemTemplates/index.js
  src/editors/data/constants/basicProblemTemplates/multiSelect.js
  src/editors/data/constants/basicProblemTemplates/numeric.js
  src/editors/data/constants/basicProblemTemplates/singleSelect.js
  src/editors/data/constants/basicProblemTemplates/textInput.js
  src/editors/data/constants/problem.ts
  src/editors/data/redux/app/reducer.test.js
  src/editors/data/redux/app/reducer.ts
  src/editors/data/redux/app/selectors.test.ts
  src/editors/data/redux/app/selectors.ts
  src/editors/data/redux/index.ts
  src/editors/data/redux/problem/reducers.ts
  src/editors/data/redux/problem/selectors.test.ts
  src/editors/data/redux/problem/selectors.ts
  src/editors/data/redux/thunkActions/problem.test.ts
  src/editors/data/redux/thunkActions/problem.ts
  src/editors/data/redux/thunkActions/requests.js
  src/editors/hooks.test.jsx
  src/editors/hooks.ts
  src/editors/sharedComponents/CodeEditor/hooks.js
  src/editors/sharedComponents/CodeEditor/index.jsx
  src/editors/sharedComponents/CodeEditor/index.test.jsx
  src/editors/sharedComponents/RawEditor/index.jsx
  src/editors/utils/convertMarkdownToXML.js
  src/editors/utils/convertMarkdownToXML.test.ts
  src/editors/utils/index.ts
Labels: open-source-contribution

#1854 feat: standardize slot ids
  package-lock.json
  package.json
  src/files-and-videos/videos-page/transcript-settings/TranscriptSettings.jsx
  src/pages-and-resources/PagesAndResources.jsx
  src/pages-and-resources/pages/PageGrid.jsx
  src/plugin-slots/AdditionalCourseContentPluginSlot/README.md
  src/plugin-slots/AdditionalCourseContentPluginSlot/__snapshots__/index.test.jsx.snap
  src/plugin-slots/AdditionalCourseContentPluginSlot/index.test.jsx
  src/plugin-slots/AdditionalCourseContentPluginSlot/index.tsx
  src/plugin-slots/AdditionalCoursePluginSlot/README.md
  src/plugin-slots/AdditionalCoursePluginSlot/__snapshots__/index.test.jsx.snap
  src/plugin-slots/AdditionalCoursePluginSlot/index.test.jsx
  src/plugin-slots/AdditionalCoursePluginSlot/index.tsx
  src/plugin-slots/AdditionalTranslationsComponentSlot/README.md
  src/plugin-slots/AdditionalTranslationsComponentSlot/index.tsx
  src/plugin-slots/CourseAuthoringOutlineSidebarSlot/README.md
  src/plugin-slots/CourseAuthoringOutlineSidebarSlot/index.tsx
  src/plugin-slots/CourseAuthoringUnitSidebarSlot/README.md
  src/plugin-slots/CourseAuthoringUnitSidebarSlot/index.tsx
  src/plugin-slots/CourseOutlineHeaderActionsSlot/README.md
  src/plugin-slots/CourseOutlineHeaderActionsSlot/__snapshots__/index.test.jsx.snap
  src/plugin-slots/CourseOutlineHeaderActionsSlot/index.jsx
  src/plugin-slots/CourseOutlineSubsectionCardExtraActionsSlot/README.md
  src/plugin-slots/CourseOutlineSubsectionCardExtraActionsSlot/index.jsx
  src/plugin-slots/CourseOutlineUnitCardExtraActionsSlot/README.md
  src/plugin-slots/CourseOutlineUnitCardExtraActionsSlot/index.jsx
  src/plugin-slots/CourseUnitHeaderActionsSlot/README.md
  src/plugin-slots/CourseUnitHeaderActionsSlot/__snapshots__/index.test.jsx.snap
  src/plugin-slots/CourseUnitHeaderActionsSlot/index.jsx
  src/plugin-slots/README.md
Labels: create-sandbox

#1832 feat: import `StudioFooterSlot` from component package instead of slot package
  package-lock.json
  package.json
  src/CourseAuthoringPage.jsx
  src/accessibility-page/AccessibilityPage.jsx
  src/course-rerun/index.jsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/collections/LibraryCollectionPage.tsx
  src/library-authoring/create-library/CreateLibrary.tsx
  src/plugin-slots/README.md
  src/plugin-slots/StudioFooterSlot/README.md
  src/studio-home/StudioHome.tsx
  src/taxonomy/TaxonomyLayout.test.tsx
  src/taxonomy/TaxonomyLayout.tsx
Labels: create-sandbox

#1833 feat: disallow edits to units in courses that are sourced from a library
  src/content-tags-drawer/tags-sidebar-controls/TagsSidebarBody.tsx
  src/content-tags-drawer/tags-sidebar-controls/index.tsx
  src/course-outline/card-header/CardHeader.jsx
  src/course-outline/card-header/CardHeader.test.jsx
  src/course-outline/unit-card/UnitCard.jsx
  src/course-unit/CourseUnit.jsx
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/add-component/AddComponent.jsx
  src/course-unit/data/thunk.js
  src/course-unit/data/utils.js
  src/course-unit/header-title/HeaderTitle.jsx
  src/course-unit/header-title/HeaderTitle.test.jsx
  src/course-unit/sidebar/PublishControls.tsx
  src/course-unit/sidebar/components/sidebar-footer/ActionButtons.tsx
  src/course-unit/sidebar/components/sidebar-footer/UnitVisibilityInfo.tsx
  src/course-unit/sidebar/components/sidebar-footer/index.tsx
  src/generic/configure-modal/ConfigureModal.jsx
  src/plugin-slots/CourseAuthoringUnitSidebarSlot/README.md
  src/plugin-slots/CourseAuthoringUnitSidebarSlot/index.tsx
Labels: open-source-contribution

#1850 feat: Sync units in course outline [FC-0083]
  src/course-outline/__mocks__/courseOutlineIndex.js
  src/course-outline/card-header/CardHeader.jsx
  src/course-outline/card-header/CardHeader.scss
  src/course-outline/card-header/CardHeader.test.jsx
  src/course-outline/card-header/messages.js
  src/course-outline/unit-card/UnitCard.jsx
  src/course-outline/unit-card/UnitCard.test.jsx
  src/course-unit/preview-changes/index.test.tsx
  src/course-unit/preview-changes/index.tsx
  src/library-authoring/component-comparison/CompareChangesWidget.tsx
  src/library-authoring/component-comparison/messages.ts
Labels: open-source-contribution

#1863 fix: allow units sourced from libraries to update their settings [FC-0083]
  src/course-unit/header-title/HeaderTitle.jsx
  src/course-unit/header-title/HeaderTitle.test.jsx
Labels: open-source-contribution, FC

#1860 feat: Add 'This unit can only be edited from the library' banner in units that are sourced from a library [FC-0083]
  src/course-unit/CourseUnit.jsx
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/__mocks__/courseUnitIndex.js
  src/course-unit/messages.js
Labels: open-source-contribution, FC

#1864 fix: NaN library components are out of sync [FC-0083]
  src/course-libraries/OutOfSyncAlert.tsx
  src/course-libraries/__mocks__/linkCourseSummary.json
Labels: open-source-contribution

#1838 feat: display editors as modals
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/add-component/AddComponent.jsx
  src/course-unit/add-component/messages.js
  src/course-unit/xblock-container-iframe/hooks/types.ts
  src/course-unit/xblock-container-iframe/hooks/useMessageHandlers.tsx
  src/course-unit/xblock-container-iframe/index.tsx
  src/course-unit/xblock-container-iframe/messages.ts
  src/editors/Editor.tsx
  src/editors/EditorContext.tsx
  src/editors/EditorPage.test.tsx
  src/editors/EditorPage.tsx
  src/editors/containers/EditorContainer/index.test.tsx
  src/editors/containers/EditorContainer/index.tsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/index.test.tsx
  src/editors/containers/VideoEditor/__snapshots__/index.test.tsx.snap
  src/editors/containers/VideoEditor/components/VideoEditorModal.tsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/index.tsx
  src/editors/containers/VideoEditor/index.tsx
  src/library-authoring/components/ComponentEditorModal.tsx
Labels: open-source-contribution

#1865 refactor: remove custom order function from course libraries list
  src/course-libraries/ReviewTabContent.tsx
Labels: open-source-contribution
