Repository openedx/frontend-app-authoring, pull requests merged in 2025-01, with the labels that each got.

#1575 feat: shareable URLs for library components and searches [FC-0076]
  src/content-tags-drawer/ContentTagsDrawer.test.jsx
  src/hooks.ts
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/LibraryContent.tsx
  src/library-authoring/LibraryLayout.tsx
  src/library-authoring/add-content/AddContentContainer.test.tsx
  src/library-authoring/add-content/PickLibraryContentModal.test.tsx
  src/library-authoring/collections/CollectionInfo.tsx
  src/library-authoring/collections/LibraryCollectionComponents.tsx
  src/library-authoring/collections/LibraryCollectionPage.tsx
  src/library-authoring/common/context/LibraryContext.tsx
  src/library-authoring/common/context/SidebarContext.tsx
  src/library-authoring/component-info/ComponentInfo.tsx
  src/library-authoring/component-info/ComponentManagement.tsx
  src/library-authoring/component-info/ManageCollections.test.tsx
  src/library-authoring/component-info/ManageCollections.tsx
  src/library-authoring/component-picker/ComponentPicker.tsx
  src/library-authoring/components/BaseComponentCard.tsx
  src/library-authoring/components/CollectionCard.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/library-info/LibraryInfo.tsx
  src/library-authoring/library-info/LibraryInfoHeader.tsx
  src/library-authoring/routes.test.tsx
  src/library-authoring/routes.ts
  src/search-manager/FilterByBlockType.tsx
  src/search-manager/SearchManager.ts
  src/search-manager/hooks.ts
  src/search-manager/index.ts
  src/search-modal/SearchUI.test.tsx
  src/testUtils.tsx
Labels: open-source-contribution, FC

#1569 feat: Adding human readable 403 error access restricted
  src/course-outline/constants.js
  src/course-outline/data/slice.js
  src/course-outline/data/thunk.js
  src/course-outline/page-alerts/PageAlerts.jsx
  src/course-outline/page-alerts/PageAlerts.test.jsx
  src/course-outline/page-alerts/messages.js
  src/course-outline/utils/getErrorDetails.js
  src/course-outline/utils/getErrorDetails.test.js
Labels: open-source-contribution

#1582 fix: allow user provided value if can auto-create orgs [FC-0076]
  src/library-authoring/create-library/CreateLibrary.test.tsx
  src/library-authoring/create-library/CreateLibrary.tsx
  src/studio-home/__mocks__/studioHomeMock.js
Labels: open-source-contribution, FC

#1431 feat: [FC-0070] listen to xblock interaction events
  src/constants.js
  src/course-unit/CourseUnit.jsx
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/constants.js
  src/course-unit/data/slice.js
  src/course-unit/data/thunk.js
  src/course-unit/header-title/HeaderTitle.jsx
  src/course-unit/header-title/HeaderTitle.test.jsx
  src/course-unit/sidebar/PublishControls.jsx
  src/course-unit/xblock-container-iframe/hooks/index.ts
  src/course-unit/xblock-container-iframe/hooks/tests/hooks.test.tsx
  src/course-unit/xblock-container-iframe/hooks/types.ts
  src/course-unit/xblock-container-iframe/hooks/useIFrameBehavior.tsx
  src/course-unit/xblock-container-iframe/hooks/useIframeContent.tsx
  src/course-unit/xblock-container-iframe/hooks/useIframeMessages.tsx
  src/course-unit/xblock-container-iframe/hooks/useLoadBearingHook.tsx
  src/course-unit/xblock-container-iframe/hooks/useMessageHandlers.tsx
  src/course-unit/xblock-container-iframe/index.tsx
  src/course-unit/xblock-container-iframe/messages.ts
  src/course-unit/xblock-container-iframe/tests/XblockContainerIframe.test.tsx
  src/course-unit/xblock-container-iframe/types.ts
  src/course-unit/xblock-container-iframe/utils.ts
Labels: open-source-contribution, create-sandbox, FC

#1475 feat: [FC-0070] rendering library content in unit page
  src/constants.js
  src/course-unit/CourseUnit.jsx
  src/course-unit/CourseUnit.scss
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/add-component/AddComponent.jsx
  src/course-unit/add-component/add-component-btn/AddComponentIcon.jsx
  src/course-unit/add-component/add-component-modals/ComponentModalView.jsx
  src/course-unit/breadcrumbs/Breadcrumbs.jsx
  src/course-unit/breadcrumbs/Breadcrumbs.test.tsx
  src/course-unit/breadcrumbs/Breadcrumbs.tsx
  src/course-unit/clipboard/paste-notification/components/FileList.jsx
  src/course-unit/clipboard/paste-notification/index.jsx
  src/course-unit/constants.js
  src/course-unit/context/iFrameContext.tsx
  src/course-unit/data/api.js
  src/course-unit/data/thunk.js
  src/course-unit/data/utils.js
  src/course-unit/header-navigations/HeaderNavigations.jsx
  src/course-unit/header-navigations/HeaderNavigations.test.jsx
  src/course-unit/header-navigations/messages.ts
  src/course-unit/header-title/HeaderTitle.jsx
  src/course-unit/header-title/HeaderTitle.test.jsx
  src/course-unit/hooks.jsx
  src/course-unit/move-modal/index.tsx
  src/course-unit/move-modal/moveModal.test.tsx
  src/course-unit/preview-changes/index.tsx
  src/course-unit/sidebar/components/sidebar-footer/index.jsx
  src/course-unit/utils.test.ts
  src/course-unit/utils.ts
  src/generic/configure-modal/ConfigureModal.jsx
  src/generic/configure-modal/UnitTab.jsx
  src/generic/configure-modal/messages.js
  src/setupTest.js
Labels: open-source-contribution, create-sandbox, FC

#1568 feat: Add AdvancedEditors with an iframe [FC-0076]
  src/editors/AdvancedEditor.test.tsx
  src/editors/AdvancedEditor.tsx
  src/editors/Editor.tsx
  src/editors/EditorPage.test.tsx
  src/editors/messages.ts
  src/library-authoring/LibraryBlock/LibraryBlock.tsx
  src/library-authoring/components/ComponentEditorModal.tsx
Labels: open-source-contribution, FC

#1585 feat: add last published date to HistoryWidget [FC-0076]
  src/library-authoring/collections/CollectionDetails.tsx
  src/library-authoring/component-info/ComponentDetails.test.tsx
  src/library-authoring/component-info/ComponentManagement.test.tsx
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/generic/history-widget/index.tsx
  src/library-authoring/generic/history-widget/messages.ts
Labels: open-source-contribution

#1587 Update catalog-info file for release data
  catalog-info.yaml
  openedx.yaml
Labels: open-source-contribution

#1601 feat: hide some settings fields when editing a library problem [FC-0076]
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/__snapshots__/index.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.test.jsx
Labels: open-source-contribution, core contributor, waiting for eng review, FC

#1638 docs: clarify/update a TODO comment about Meilisearch functionality
  src/search-manager/data/api.ts
Labels: open-source-contribution
