Repository openedx/frontend-app-authoring, pull requests merged in 2025-02, with the labels that each got.

#1570 feat: allow filtering library by publish status
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/collections/LibraryCollectionPage.tsx
  src/library-authoring/components/BaseComponentCard.tsx
  src/library-authoring/components/ComponentCard.test.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/messages.ts
  src/search-manager/FilterByPublished.tsx
  src/search-manager/SearchManager.ts
  src/search-manager/data/api.ts
  src/search-manager/data/apiHooks.ts
  src/search-manager/index.ts
  src/search-manager/messages.ts
  src/search-modal/SearchUI.test.tsx
Labels: open-source-contribution

#1651 feat: Add drag and drop to `LIBRARY_SUPPORTED_BLOCKS`
  .env
  .env.development
  .env.test
  src/library-authoring/add-content/AddContentContainer.test.tsx
Labels: open-source-contribution

#1544 chore: iframe rendering optimization
  .gitignore
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/add-component/AddComponent.jsx
  src/course-unit/constants.js
  src/course-unit/data/thunk.js
  src/course-unit/header-title/HeaderTitle.jsx
  src/course-unit/header-title/HeaderTitle.test.jsx
  src/course-unit/hooks.jsx
  src/course-unit/move-modal/hooks.tsx
  src/course-unit/sidebar/PublishControls.jsx
  src/course-unit/xblock-container-iframe/hooks/tests/hooks.test.tsx
  src/course-unit/xblock-container-iframe/hooks/types.ts
  src/course-unit/xblock-container-iframe/hooks/useIframeContent.tsx
  src/course-unit/xblock-container-iframe/hooks/useMessageHandlers.tsx
  src/course-unit/xblock-container-iframe/index.tsx
  src/generic/clipboard/paste-component/components/PasteButton.jsx
  src/generic/configure-modal/ConfigureModal.jsx
  src/generic/configure-modal/UnitTab.jsx
Labels: open-source-contribution, create-sandbox

#1646 Fix problem input [FC-0076]
  src/editors/sharedComponents/TinyMceWidget/hooks.js
  src/editors/sharedComponents/TinyMceWidget/pluginConfig.js
  src/header/Header.tsx
Labels: open-source-contribution

#1649 fix: Height in Advanced Editor [FC-0076]
  src/library-authoring/LibraryBlock/LibraryBlock.tsx
Labels: open-source-contribution, FC

#1445 feat: [FC-0070] handled edit modals from advanced xblocks
  src/constants.js
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/constants.js
  src/course-unit/data/thunk.js
  src/course-unit/xblock-container-iframe/hooks/tests/hooks.test.tsx
  src/course-unit/xblock-container-iframe/hooks/types.ts
  src/course-unit/xblock-container-iframe/hooks/useMessageHandlers.tsx
  src/course-unit/xblock-container-iframe/index.tsx
  src/course-unit/xblock-container-iframe/messages.ts
  src/course-unit/xblock-container-iframe/utils.ts
  src/generic/modal-iframe/ModalIframe.test.tsx
  src/generic/modal-iframe/index.scss
  src/generic/modal-iframe/index.tsx
  src/generic/saving-error-alert/SavingErrorAlert.jsx
  src/generic/styles.scss
Labels: open-source-contribution, create-sandbox, FC

#1672 feat: Add cancel confirmation modal to Advanced editors in libraries [FC-0076]
  src/editors/AdvancedEditor.test.tsx
  src/editors/AdvancedEditor.tsx
  src/editors/containers/EditorContainer/components/CancelConfirmModal.tsx
  src/editors/containers/EditorContainer/index.tsx
Labels: open-source-contribution, FC

#1664 fix: Adjust course import dropzone height to make course import status visible
  src/import-page/file-section/FileSection.jsx
Labels: open-source-contribution

#1596 feat: Enable transcripts for video library [FC-0076]
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/index.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/index.test.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoPreviewWidget/index.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoPreviewWidget/index.test.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/index.tsx
  src/editors/data/constants/requests.ts
  src/editors/data/redux/thunkActions/requests.js
  src/editors/data/redux/thunkActions/requests.test.js
  src/editors/data/redux/thunkActions/video.js
  src/editors/data/redux/thunkActions/video.test.js
  src/editors/data/redux/video/reducer.js
  src/editors/data/redux/video/selectors.js
  src/editors/data/services/cms/api.test.ts
  src/editors/data/services/cms/api.ts
  src/editors/data/services/cms/urls.test.ts
  src/editors/data/services/cms/urls.ts
Labels: open-source-contribution, FC

#1574 feat: block creation in libraries v2
  .env.test
  src/editors/containers/EditorContainer/hooks.test.jsx
  src/editors/containers/EditorContainer/hooks.ts
  src/editors/containers/EditorContainer/index.test.tsx
  src/editors/containers/EditorContainer/index.tsx
  src/editors/containers/ProblemEditor/index.test.tsx
  src/editors/containers/ProblemEditor/index.tsx
  src/editors/containers/TextEditor/index.jsx
  src/editors/containers/TextEditor/index.test.jsx
  src/editors/containers/VideoEditor/index.tsx
  src/editors/data/constants/problem.ts
  src/editors/data/constants/requests.ts
  src/editors/data/redux/app/reducer.ts
  src/editors/data/redux/app/selectors.test.ts
  src/editors/data/redux/app/selectors.ts
  src/editors/data/redux/index.ts
  src/editors/data/redux/requests/reducer.js
  src/editors/data/redux/thunkActions/app.js
  src/editors/data/redux/thunkActions/app.test.js
  src/editors/data/redux/thunkActions/problem.ts
  src/editors/data/redux/thunkActions/requests.js
  src/editors/data/redux/thunkActions/requests.test.js
  src/editors/data/redux/thunkActions/video.js
  src/editors/hooks.test.jsx
  src/editors/hooks.ts
  src/editors/sharedComponents/ImageUploadModal/index.jsx
  src/library-authoring/add-content/AddContentContainer.test.tsx
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/add-content/AddContentWorkflow.test.tsx
  src/library-authoring/common/context/LibraryContext.tsx
  src/library-authoring/components/ComponentEditorModal.tsx
Labels: open-source-contribution, create-sandbox

#1679 fix: parsing text input problems
  src/editors/containers/ProblemEditor/components/EditProblemView/hooks.js
  src/editors/containers/ProblemEditor/data/OLXParser.js
  src/editors/containers/ProblemEditor/data/OLXParser.test.js
  src/editors/containers/ProblemEditor/data/mockData/olxTestData.js
Labels: open-source-contribution

#1678 [sumac] fix: allow user provided value if can auto-create orgs [FC-0076]
  src/generic/create-or-rerun-course/hooks.jsx
  src/library-authoring/create-library/CreateLibrary.test.tsx
  src/library-authoring/create-library/CreateLibrary.tsx
  src/studio-home/__mocks__/studioHomeMock.js
Labels: open-source-contribution, FC

#1650 fix: change ComponentPreview modal size to xl [FC-0076]
  src/library-authoring/component-info/ComponentPreview.tsx
Labels: open-source-contribution, create-sandbox, FC

#1673 [sumac] fix: bugs with ExpandableTextArea toolbars & modals in problem editor [FC-0076]
  src/editors/sharedComponents/TinyMceWidget/hooks.js
  src/editors/sharedComponents/TinyMceWidget/pluginConfig.js
Labels: open-source-contribution, FC
