Repository openedx/frontend-app-authoring, pull requests merged in 2025-06, with the labels that each got.

#2059 fix: set unit preview readonly on sidebar [teak]
  src/generic/inplace-text-editor/index.tsx
  src/library-authoring/containers/UnitInfo.test.tsx
  src/library-authoring/containers/UnitInfo.tsx
  src/library-authoring/units/LibraryUnitBlocks.tsx
Labels: open-source-contribution

#2067 Refactor many test suites to use testUtils/initializeMocks
  jest.config.js
  plugins/course-apps/learning_assistant/Settings.test.jsx
  src/CourseAuthoringPage.test.jsx
  src/CourseAuthoringRoutes.test.jsx
  src/accessibility-page/AccessibilityPage.test.jsx
  src/advanced-settings/AdvancedSettings.test.jsx
  src/certificates/Certificates.test.jsx
  src/certificates/layout/certificates-sidebar/CertificatesSidebar.test.jsx
  src/course-checklist/ChecklistSection/ChecklistSection.test.jsx
  src/course-outline/outline-sidebar/OutlineSidebar.test.jsx
  src/course-rerun/CourseRerun.test.jsx
  src/course-rerun/course-rerun-sidebar/CourseRerunSidebar.test.jsx
  src/course-team/CourseTeam.jsx
  src/course-team/CourseTeam.test.jsx
  src/course-team/course-team-sidebar/CourseTeamSideBar.test.jsx
  src/course-unit/add-component/AddComponent.test.jsx
  src/custom-pages/CustomPages.test.jsx
  src/export-page/CourseExportPage.test.jsx
  src/export-page/export-sidebar/ExportSidebar.test.jsx
  src/generic/help-sidebar/HelpSidebar.test.jsx
  src/group-configurations/GroupConfigurations.test.jsx
  src/group-configurations/group-configuration-sidebar/GroupConfigurationSidebar.test.jsx
  src/import-page/CourseImportPage.test.jsx
  src/import-page/import-sidebar/ImportSidebar.test.jsx
  src/pages-and-resources/PagesAndResources.test.jsx
  src/pages-and-resources/pages/PageCard.test.jsx
  src/pages-and-resources/utils.test.jsx
  src/schedule-and-details/ScheduleAndDetails.test.jsx
  src/studio-home/home-sidebar/HomeSidebar.test.jsx
  src/studio-home/tabs-section/courses-tab/index.test.tsx
  src/studio-home/verify-email-layout/VerifyEmailLayout.test.jsx
  src/textbooks/Textbook.test.jsx
  src/textbooks/textbook-sidebar/TextbookSidebar.test.jsx
Labels: open-source-contribution, core contributor

#2065 fix: backport changes for html button in text component markdown editor
  src/editors/sharedComponents/CodeEditor/hooks.js
  src/editors/sharedComponents/SourceCodeModal/__snapshots__/index.test.jsx.snap
  src/editors/sharedComponents/SourceCodeModal/index.jsx
Labels: open-source-contribution, mao-onboarding

#1998 fix: Expand all now expands subsections
  src/course-outline/CourseOutline.jsx
  src/course-outline/CourseOutline.test.jsx
  src/course-outline/header-navigations/HeaderNavigations.jsx
  src/course-outline/subsection-card/SubsectionCard.jsx
Labels: open-source-contribution, create-sandbox

#2071 Fix Files and Uploads three-dot menu for a file was truncated
  src/files-and-videos/files-page/FilesPage.jsx
  src/files-and-videos/files-page/FilesPage.scss
Labels: open-source-contribution, mao-onboarding

#2038 Fix logic of best practices checklist and remove mobile friendly check
  src/course-checklist/ChecklistSection/messages.js
  src/course-checklist/ChecklistSection/utils/courseChecklistData.jsx
  src/course-checklist/ChecklistSection/utils/courseChecklistValidators.js
  src/course-checklist/ChecklistSection/utils/courseChecklistValidators.test.js
  src/course-checklist/ChecklistSection/utils/getValidatedValue.js
  src/course-checklist/ChecklistSection/utils/getValidatedValue.test.js
  src/course-outline/CourseOutline.test.jsx
  src/course-outline/constants.js
  src/course-outline/utils/courseChecklistValidators.js
  src/course-outline/utils/courseChecklistValidators.test.js
  src/course-outline/utils/getChecklistForStatusBar.test.js
  src/course-outline/utils/getChecklistValues.js
Labels: open-source-contribution, mao-onboarding

#2085 BACKPORT fix: Expand all now expands subsections
  src/course-outline/CourseOutline.jsx
  src/course-outline/CourseOutline.test.jsx
  src/course-outline/header-navigations/HeaderNavigations.jsx
  src/course-outline/subsection-card/SubsectionCard.jsx
Labels: open-source-contribution

#2077 Backport fix: files & uploads menu was truncated due to overflow-x (#2071)
  src/files-and-videos/files-page/FilesPage.jsx
  src/files-and-videos/files-page/FilesPage.scss
Labels: open-source-contribution, mao-onboarding

#2057 feat: Section/Subsection Card Preview [FC-0090]
  src/library-authoring/components/ContainerCard.scss
  src/library-authoring/components/ContainerCard.test.tsx
  src/library-authoring/components/ContainerCard.tsx
  src/library-authoring/components/index.scss
  src/library-authoring/components/messages.ts
  src/library-authoring/index.scss
  src/search-manager/data/api.ts
Labels: open-source-contribution, FC

#2066 refactor: make the unit sidebar code work for any type of container [FC-0090]
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/LibraryLayout.tsx
  src/library-authoring/add-content/AddContent.test.tsx
  src/library-authoring/add-content/AddContent.tsx
  src/library-authoring/add-content/PickLibraryContentModal.test.tsx
  src/library-authoring/add-content/PickLibraryContentModal.tsx
  src/library-authoring/collections/CollectionDetails.test.tsx
  src/library-authoring/collections/CollectionDetails.tsx
  src/library-authoring/collections/CollectionInfo.tsx
  src/library-authoring/collections/CollectionInfoHeader.test.tsx
  src/library-authoring/collections/CollectionInfoHeader.tsx
  src/library-authoring/collections/LibraryCollectionPage.test.tsx
  src/library-authoring/collections/LibraryCollectionPage.tsx
  src/library-authoring/common/context/LibraryContext.tsx
  src/library-authoring/common/context/SidebarContext.tsx
  src/library-authoring/component-info/ComponentAdvancedAssets.tsx
  src/library-authoring/component-info/ComponentAdvancedInfo.test.tsx
  src/library-authoring/component-info/ComponentAdvancedInfo.tsx
  src/library-authoring/component-info/ComponentDetails.test.tsx
  src/library-authoring/component-info/ComponentDetails.tsx
  src/library-authoring/component-info/ComponentInfo.test.tsx
  src/library-authoring/component-info/ComponentInfo.tsx
  src/library-authoring/component-info/ComponentInfoHeader.test.tsx
  src/library-authoring/component-info/ComponentInfoHeader.tsx
  src/library-authoring/component-info/ComponentManagement.test.tsx
  src/library-authoring/component-info/ComponentManagement.tsx
  src/library-authoring/component-info/ComponentPreview.test.tsx
  src/library-authoring/component-info/ComponentPreview.tsx
  src/library-authoring/components/CollectionCard.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/ComponentDeleter.tsx
  src/library-authoring/components/ComponentMenu.tsx
  src/library-authoring/components/ContainerCard.tsx
  src/library-authoring/components/ContainerDeleter.tsx
  src/library-authoring/containers/ContainerInfo.test.tsx
  src/library-authoring/containers/ContainerInfo.tsx
  src/library-authoring/containers/ContainerInfoHeader.test.tsx
  src/library-authoring/containers/ContainerInfoHeader.tsx
  src/library-authoring/containers/ContainerOrganize.test.tsx
  src/library-authoring/containers/ContainerOrganize.tsx
  src/library-authoring/containers/HeaderActions.tsx
  src/library-authoring/containers/UnitInfo.test.tsx
  src/library-authoring/containers/index.tsx
  src/library-authoring/containers/messages.ts
  src/library-authoring/create-container/CreateContainerModal.tsx
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/generic/manage-collections/ManageCollections.test.tsx
  src/library-authoring/library-sidebar/LibrarySidebar.tsx
  src/library-authoring/routes.test.tsx
  src/library-authoring/routes.ts
  src/library-authoring/section-subsections/LibraryContainerChildren.tsx
  src/library-authoring/section-subsections/LibrarySectionPage.tsx
  src/library-authoring/section-subsections/LibrarySectionSubsectionPage.test.tsx
  src/library-authoring/section-subsections/LibrarySubsectionPage.tsx
  src/library-authoring/units/LibraryUnitBlocks.tsx
  src/library-authoring/units/LibraryUnitPage.test.tsx
  src/library-authoring/units/LibraryUnitPage.tsx
Labels: open-source-contribution, core contributor, FC

#2101 fix: Issue on the Inplace editor [FC-0090]
  src/generic/inplace-text-editor/InplaceTextEditor.test.tsx
  src/generic/inplace-text-editor/index.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/data/apiHooks.ts
Labels: open-source-contribution

#2111 fix: remove an extra editing xblock modal on unit page
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/add-component/AddComponent.jsx
  src/course-unit/add-component/messages.js
  src/course-unit/xblock-container-iframe/index.tsx
  src/course-unit/xblock-container-iframe/messages.ts
Labels: open-source-contribution

#2128 fix: show Preview tab in sidebar when container child selected [FC-0090]
  src/library-authoring/common/context/SidebarContext.tsx
  src/library-authoring/section-subsections/LibrarySectionSubsectionPage.test.tsx
  src/library-authoring/units/LibraryUnitPage.test.tsx
Labels: open-source-contribution, core contributor

#2129 Remove icon and empty breadcrumb from libraries component selection
  src/library-authoring/LibraryAuthoringPage.tsx
Labels: open-source-contribution, mao-onboarding

#2132 test: replacing snapshot tests with rtl tests part 2
  src/editors/containers/ProblemEditor/components/EditProblemView/__snapshots__/index.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/index.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/index.test.jsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/content/ProblemTypeSelect.test.tsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/content/__snapshots__/ProblemTypeSelect.test.tsx.snap
  src/editors/sharedComponents/ErrorAlerts/ErrorAlert.test.jsx
  src/editors/sharedComponents/ErrorAlerts/ErrorAlert.test.tsx
  src/editors/sharedComponents/ErrorAlerts/FetchErrorAlert.test.jsx
  src/editors/sharedComponents/ErrorAlerts/FetchErrorAlert.test.tsx
  src/editors/sharedComponents/ErrorAlerts/__snapshots__/ErrorAlert.test.jsx.snap
  src/editors/sharedComponents/ErrorAlerts/__snapshots__/FetchErrorAlert.test.jsx.snap
  src/selectors/VideoSelectorContainer.test.jsx
  src/selectors/VideoSelectorContainer.test.tsx
  src/selectors/__snapshots__/VideoSelectorContainer.test.jsx.snap
Labels: open-source-contribution, mao-onboarding

#2100 fix: show unit published name in sidebar on content picker [FC-0090]
  src/library-authoring/__mocks__/library-search.json
  src/library-authoring/component-picker/ComponentPicker.test.tsx
  src/library-authoring/containers/ContainerEditableTitle.tsx
  src/library-authoring/containers/ContainerInfoHeader.tsx
  src/library-authoring/data/api.mocks.ts
Labels: open-source-contribution

#2098 Backport fix: enable markdown editor in libraries
  src/editors/data/redux/thunkActions/problem.test.ts
  src/editors/data/redux/thunkActions/problem.ts
  src/library-authoring/components/ComponentEditorModal.tsx
Labels: open-source-contribution, core contributor, create-sandbox

#2135 test: replacing snapshot tests with rtl tests part 4
  src/editors/VideoSelector.test.tsx
  src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswersContainer.test.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswersContainer.test.tsx
  src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/__snapshots__/AnswersContainer.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/TypeRow.test.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/TypeRow.test.tsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/TypeRow.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/index.test.jsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/__snapshots__/index.test.tsx.snap
  src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/index.test.tsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/content/Preview.jsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/content/Preview.test.jsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/content/Preview.test.tsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/content/__snapshots__/Preview.test.jsx.snap
  src/editors/containers/ProblemEditor/components/SelectTypeModal/index.test.tsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseDisplay.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseDisplay.test.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseDisplay.test.tsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/LicenseDisplay.test.jsx.snap
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/index.test.jsx.snap
  src/editors/editorTestRender.jsx
Labels: open-source-contribution, mao-onboarding

#2133 Backport: Remove icon and empty breadcrumb from libraries (#2129)
  src/library-authoring/LibraryAuthoringPage.tsx
Labels: open-source-contribution, mao-onboarding

#2134 test: replacing snapshot tests with rtl tests part 3
  src/editors/containers/EditorContainer/components/TitleHeader/EditConfirmationButtons.jsx
  src/editors/containers/EditorContainer/components/TitleHeader/EditConfirmationButtons.test.jsx
  src/editors/containers/EditorContainer/components/TitleHeader/EditConfirmationButtons.test.tsx
  src/editors/containers/EditorContainer/components/TitleHeader/__snapshots__/EditConfirmationButtons.test.jsx.snap
  src/editors/containers/EditorContainer/components/TitleHeader/messages.js
  src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/components/Feedback/FeedbackControl.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/components/Feedback/FeedbackControl.test.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/components/Feedback/FeedbackControl.test.tsx
  src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/components/Feedback/__snapshots__/FeedbackControl.test.jsx.snap
  src/editors/containers/ProblemEditor/components/SelectTypeModal/content/AdvanceTypeSelect.test.tsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/content/__snapshots__/AdvanceTypeSelect.test.tsx.snap
  src/editors/sharedComponents/SelectionModal/GalleryCard.test.jsx
  src/editors/sharedComponents/SelectionModal/GalleryCard.test.tsx
  src/editors/sharedComponents/SelectionModal/__snapshots__/GalleryCard.test.jsx.snap
  src/editors/sharedComponents/SourceCodeModal/__snapshots__/index.test.jsx.snap
  src/editors/sharedComponents/SourceCodeModal/index.jsx
  src/editors/sharedComponents/SourceCodeModal/index.test.jsx
  src/editors/sharedComponents/SourceCodeModal/index.test.tsx
Labels: open-source-contribution, mao-onboarding

#2137 fix: Text truncate issue in the search modal
  src/search-modal/SearchModal.scss
  src/search-modal/SearchResult.tsx
Labels: open-source-contribution

#1581 fix: advanced-settings.api always return exactly what it receives
  src/advanced-settings/data/api.js
  src/advanced-settings/data/api.test.js
Labels: open-source-contribution, release testing

#2143 test: replacing snapshot tests with rtl tests part 5
  jest.config.js
  src/editors/EditorContainer.test.jsx
  src/editors/EditorContainer.test.tsx
  src/editors/__snapshots__/EditorContainer.test.jsx.snap
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/CollapsibleFormWidget.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/CollapsibleFormWidget.test.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/CollapsibleFormWidget.test.tsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/DurationWidget/__snapshots__/index.test.jsx.snap
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/HandoutWidget/__snapshots__/index.test.jsx.snap
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseSelector.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseSelector.test.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseSelector.test.tsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/LicenseSelector.test.jsx.snap
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/index.test.jsx.snap
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/SocialShareWidget/__snapshots__/index.test.jsx.snap
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/__snapshots__/index.test.jsx.snap
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/ImportTranscriptCard.test.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/ImportTranscriptCard.test.tsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/Transcript.test.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/__snapshots__/ImportTranscriptCard.test.jsx.snap
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/__snapshots__/Transcript.test.jsx.snap
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/__snapshots__/index.test.jsx.snap
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/__snapshots__/CollapsibleFormWidget.test.jsx.snap
  tsconfig.json
  webpack.dev.config.js
Labels: open-source-contribution, mao-onboarding

#2173 test: replacing snapshot tests with rtl tests part 6
  src/course-unit/xblock-container-iframe/hooks/tests/hooks.test.tsx
  src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswerOption.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswerOption.test.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswerOption.test.tsx
  src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/__snapshots__/AnswerOption.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/SettingsOption.test.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/SettingsOption.test.tsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/__snapshots__/SettingsOption.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/GroupFeedback/GroupFeedbackRow.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/GroupFeedback/GroupFeedbackRow.test.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/GroupFeedback/GroupFeedbackRow.test.tsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/GroupFeedback/__snapshots__/GroupFeedbackRow.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/GroupFeedback/__snapshots__/index.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/TimerCard.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/TimerCard.test.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/TimerCard.test.tsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/TimerCard.test.jsx.snap
Labels: open-source-contribution, mao-onboarding

#2104 feat: create subsections, units from within containers
  src/library-authoring/add-content/AddContent.test.tsx
  src/library-authoring/add-content/AddContent.tsx
  src/library-authoring/create-container/CreateContainerModal.test.tsx
  src/library-authoring/create-container/CreateContainerModal.tsx
  src/library-authoring/data/api.ts
Labels: open-source-contribution

#2146 fix: Truncated text in InplaceTextEditor [FC-0090]
  src/generic/inplace-text-editor/InplaceTextEditor.scss
  src/generic/inplace-text-editor/index.tsx
  src/generic/styles.scss
  src/library-authoring/section-subsections/LibrarySubsectionPage.tsx
  src/library-authoring/section-subsections/index.scss
Labels: open-source-contribution

#2184 test: replacing snapshot tests with rtl tests part 8
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/HintRow.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/HintRow.test.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/HintRow.test.tsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/HintRow.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/HintsCard.test.jsx.snap
  src/editors/containers/VideoEditor/components/VideoSettingsModal/ErrorSummary.test.tsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/__snapshots__/ErrorSummary.test.tsx.snap
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/LanguageSelector.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/LanguageSelector.test.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/__snapshots__/LanguageSelector.test.jsx.snap
  src/editors/sharedComponents/BaseModal/__snapshots__/index.test.jsx.snap
  src/editors/sharedComponents/BaseModal/index.test.jsx
  src/editors/sharedComponents/BaseModal/index.test.tsx
  src/editors/sharedComponents/ErrorAlerts/UploadErrorAlert.test.jsx
  src/editors/sharedComponents/ErrorAlerts/UploadErrorAlert.test.tsx
  src/editors/sharedComponents/ErrorAlerts/__snapshots__/UploadErrorAlert.test.jsx.snap
Labels: open-source-contribution, mao-onboarding

#2087 fix: advanced-settings api should not camel-case return value (openedx#1581)
  src/advanced-settings/data/api.js
  src/advanced-settings/data/api.test.js
Labels: open-source-contribution

#2141 fix: Rename optimistic update in children containers
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/section-subsections/LibraryContainerChildren.tsx
  src/library-authoring/section-subsections/LibrarySectionSubsectionPage.test.tsx
  src/library-authoring/units/LibraryUnitPage.test.tsx
Labels: open-source-contribution

#2152 Add subsection/unit to section/subsection full-page view within library [FC-0090]
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/add-content/AddContent.test.tsx
  src/library-authoring/add-content/AddContent.tsx
  src/library-authoring/add-content/AddContentHeader.tsx
  src/library-authoring/add-content/PickLibraryContentModal.test.tsx
  src/library-authoring/add-content/PickLibraryContentModal.tsx
  src/library-authoring/add-content/messages.ts
  src/library-authoring/component-picker/ComponentPicker.test.tsx
  src/library-authoring/containers/ContainerInfo.test.tsx
  src/library-authoring/containers/FooterActions.tsx
  src/library-authoring/create-container/CreateContainerModal.test.tsx
  src/library-authoring/create-container/CreateContainerModal.tsx
  src/library-authoring/routes.ts
  src/library-authoring/section-subsections/LibrarySectionPage.tsx
  src/library-authoring/section-subsections/LibrarySectionSubsectionPage.test.tsx
  src/library-authoring/section-subsections/LibrarySubsectionPage.tsx
  src/library-authoring/units/LibraryUnitPage.test.tsx
Labels: open-source-contribution, core contributor, FC

#2056 refactor: remove selected rows when deleting or adding elements
  src/files-and-videos/files-page/FilesPage.test.jsx
  src/files-and-videos/files-page/data/slice.js
  src/files-and-videos/generic/DeleteConfirmationModal.jsx
  src/files-and-videos/generic/FileTable.jsx
  src/files-and-videos/generic/table-components/TableActions.jsx
  src/files-and-videos/generic/table-components/TableActions.test.jsx
Labels: open-source-contribution

#2145 feat: container delete confirmation modal
  src/course-libraries/data/api.ts
  src/course-libraries/data/apiHooks.ts
  src/generic/delete-modal/DeleteModal.tsx
  src/library-authoring/LibraryContent.tsx
  src/library-authoring/components/ComponentMenu.tsx
  src/library-authoring/components/ContainerDeleter.tsx
  src/library-authoring/components/index.scss
  src/library-authoring/components/messages.ts
  src/library-authoring/containers/ContainerCard.scss
  src/library-authoring/containers/ContainerCard.test.tsx
  src/library-authoring/containers/ContainerCard.tsx
  src/library-authoring/containers/ContainerDeleter.test.tsx
  src/library-authoring/containers/ContainerDeleter.tsx
  src/library-authoring/containers/ContainerInfo.test.tsx
  src/library-authoring/containers/ContainerInfo.tsx
  src/library-authoring/containers/index.scss
  src/library-authoring/containers/messages.ts
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/index.scss
  src/library-authoring/section-subsections/LibraryContainerChildren.tsx
Labels: open-source-contribution, core contributor

#2209 fix: open section/unit with keyboard inside section/subsection page
  src/generic/DraggableList/SortableItem.tsx
  src/library-authoring/section-subsections/LibraryContainerChildren.tsx
Labels: open-source-contribution

#2223 feat: add ParentBreadcrumbs component [FC-0090]
  src/library-authoring/__mocks__/unit-single.json
  src/library-authoring/generic/index.scss
  src/library-authoring/generic/parent-breadcrumbs/ParentBreadcrumbs.test.tsx
  src/library-authoring/generic/parent-breadcrumbs/index.scss
  src/library-authoring/generic/parent-breadcrumbs/index.tsx
  src/library-authoring/generic/parent-breadcrumbs/messages.ts
  src/library-authoring/section-subsections/LibrarySubsectionPage.tsx
  src/library-authoring/section-subsections/index.scss
  src/library-authoring/units/LibraryUnitPage.test.tsx
  src/library-authoring/units/LibraryUnitPage.tsx
Labels: open-source-contribution

#2243 fix: delete and remove modals styling
  src/generic/delete-modal/DeleteModal.tsx
  src/library-authoring/containers/ContainerRemover.tsx
Labels: open-source-contribution
