Repository openedx/frontend-app-authoring, pull requests merged in 2025-08, with the labels that each got.

#2343 Clean up editor tests
  src/editors/VideoSelector.test.tsx
  src/editors/containers/ProblemEditor/components/EditProblemView/index.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/index.test.tsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/index.test.tsx
  src/editors/containers/ProblemEditor/components/SelectTypeModal/index.test.tsx
  src/editors/containers/ProblemEditor/index.test.tsx
  src/editors/containers/ProblemEditor/index.tsx
  src/editors/data/store.ts
  src/editors/editorTestRender.tsx
  src/editors/sharedComponents/TinyMceWidget/index.test.tsx
  src/testUtils.tsx
Labels: open-source-contribution, core contributor

#2362 fix: remove interactivity from section/subsection preview in sidebar
  src/library-authoring/containers/ContainerInfo.test.tsx
  src/library-authoring/section-subsections/LibraryContainerChildren.tsx
  src/library-authoring/units/LibraryUnitBlocks.tsx
Labels: open-source-contribution, core contributor

#2363 fix: scroll entire window instead of iframe
  src/constants.js
  src/generic/hooks/tests/hooks.test.tsx
  src/generic/hooks/useIframeBehavior.tsx
Labels: create-sandbox

#2395 refactor: minor typing improvements
  src/course-outline/section-card/SectionCard.test.tsx
  src/course-outline/subsection-card/SubsectionCard.test.tsx
  src/course-outline/unit-card/UnitCard.test.tsx
  src/library-authoring/collections/CollectionDetails.test.tsx
  src/library-authoring/component-info/ComponentPreview.test.tsx
Labels: open-source-contribution, core contributor

#2324 feat: show sync button on section/subsections [FC-0097]
  src/course-libraries/ReviewTabContent.tsx
  src/course-libraries/data/api.ts
  src/course-libraries/data/apiHooks.ts
  src/course-outline/section-card/SectionCard.test.tsx
  src/course-outline/section-card/SectionCard.tsx
  src/course-outline/subsection-card/SubsectionCard.test.tsx
  src/course-outline/subsection-card/SubsectionCard.tsx
  src/course-outline/unit-card/UnitCard.test.tsx
  src/course-outline/unit-card/UnitCard.tsx
Labels: open-source-contribution, FC

#2394 Add TypeScript types to the redux state
  src/constants.ts
  src/data/constants.ts
  src/data/slice.ts
  src/data/thunks.ts
  src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswerOption.test.tsx
  src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswersContainer.test.tsx
  src/group-configurations/data/api.js
  src/group-configurations/data/selectors.js
  src/group-configurations/data/selectors.ts
  src/group-configurations/data/slice.test.ts
  src/group-configurations/data/slice.ts
  src/group-configurations/data/thunk.ts
  src/store.ts
  src/studio-home/StudioHome.tsx
  src/studio-home/__mocks__/studioHomeMock.ts
  src/studio-home/data/selectors.js
  src/studio-home/data/selectors.ts
  src/studio-home/data/slice.ts
  src/studio-home/factories/mockApiResponses.tsx
  src/studio-home/tabs-section/courses-tab/index.test.tsx
  src/studio-home/tabs-section/courses-tab/index.tsx
  src/testUtils.tsx
Labels: open-source-contribution, core contributor

#2385 fix: Restore styling for header title and button
  src/course-outline/card-header/TitleButton.tsx
  src/course-outline/card-header/TitleLink.tsx
Labels: open-source-contribution, core contributor

#2372 feat: add new help section in course teams page
  .env
  .env.development
  .env.test
  src/course-team/course-team-sidebar/CourseTeamSideBar.test.jsx
  src/course-team/course-team-sidebar/CourseTeamSidebar.jsx
  src/course-team/course-team-sidebar/messages.js
  src/index.jsx
  src/setupTest.js
Labels: open-source-contribution

#2319 style: Fixing nits about sync units [FC-0097]
  src/course-libraries/ReviewTabContent.tsx
  src/course-outline/card-header/CardHeader.tsx
  src/course-outline/card-header/messages.js
  src/course-outline/section-card/SectionCard.test.tsx
  src/course-outline/subsection-card/SubsectionCard.test.tsx
  src/course-outline/unit-card/UnitCard.test.tsx
  src/library-authoring/component-comparison/messages.ts
Labels: open-source-contribution, FC

#2320 [Teak] style: Fixing nits about sync units [FC-0097]
  src/course-libraries/CourseLibraries.test.tsx
  src/course-libraries/CourseLibraries.tsx
  src/course-libraries/messages.ts
  src/course-outline/card-header/CardHeader.jsx
  src/course-outline/card-header/CardHeader.scss
  src/course-outline/card-header/messages.js
  src/course-outline/unit-card/UnitCard.test.jsx
  src/library-authoring/component-comparison/messages.ts
Labels: open-source-contribution, backport, FC

#2393 feat: add unlink upstream menu [FC-0097]
  src/course-libraries/index.tsx
  src/course-outline/CourseOutline.test.tsx
  src/course-outline/CourseOutline.tsx
  src/course-outline/card-header/CardHeader.scss
  src/course-outline/card-header/CardHeader.test.tsx
  src/course-outline/card-header/CardHeader.tsx
  src/course-outline/card-header/messages.js
  src/course-outline/data/slice.ts
  src/course-outline/hooks.jsx
  src/course-outline/section-card/SectionCard.test.tsx
  src/course-outline/section-card/SectionCard.tsx
  src/course-outline/subsection-card/SubsectionCard.test.tsx
  src/course-outline/subsection-card/SubsectionCard.tsx
  src/course-outline/unit-card/UnitCard.test.tsx
  src/course-outline/unit-card/UnitCard.tsx
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/constants.js
  src/course-unit/hooks.jsx
  src/course-unit/xblock-container-iframe/hooks/tests/hooks.test.tsx
  src/course-unit/xblock-container-iframe/hooks/types.ts
  src/course-unit/xblock-container-iframe/hooks/useMessageHandlers.tsx
  src/course-unit/xblock-container-iframe/index.tsx
  src/course-unit/xblock-container-iframe/types.ts
  src/data/types.ts
  src/generic/key-utils.ts
  src/generic/unlink-modal/UnlinkModal.test.jsx
  src/generic/unlink-modal/UnlinkModal.tsx
  src/generic/unlink-modal/data/api.ts
  src/generic/unlink-modal/data/apiHooks.ts
  src/generic/unlink-modal/index.tsx
  src/generic/unlink-modal/messages.ts
Labels: open-source-contribution, FC
