Repository openedx/frontend-app-authoring, pull requests merged in 2025-05, with the labels that each got.

#1888 refactor: remove custom order function from course libraries list
  src/course-libraries/ReviewTabContent.tsx
Labels: open-source-contribution, backport

#1868 fix: unit pages ux bugs [FC-0083]
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/add-content/AddContent.test.tsx
  src/library-authoring/add-content/AddContent.tsx
  src/library-authoring/add-content/PickLibraryContentModal.test.tsx
  src/library-authoring/add-content/PickLibraryContentModal.tsx
  src/library-authoring/add-content/messages.ts
  src/library-authoring/common/context/SidebarContext.tsx
  src/library-authoring/components/ContainerCard.tsx
  src/library-authoring/containers/ContainerOrganize.tsx
  src/library-authoring/containers/UnitInfo.tsx
  src/library-authoring/containers/messages.ts
  src/library-authoring/generic/manage-collections/ManageCollections.test.tsx
  src/library-authoring/generic/manage-collections/ManageCollections.tsx
  src/library-authoring/generic/manage-collections/messages.ts
  src/library-authoring/generic/messages.ts
  src/library-authoring/units/LibraryUnitBlocks.tsx
  src/library-authoring/units/LibraryUnitPage.tsx
Labels: open-source-contribution, FC

#1820 fix: use Library search results to populate container card preview [FC-0083]
  src/library-authoring/components/ContainerCard.test.tsx
  src/library-authoring/components/ContainerCard.tsx
  src/search-manager/data/api.ts
Labels: open-source-contribution, FC

#1889 perf: use Library search results to populate container card preview [FC-0083] [TEAK]
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/add-content/AddContent.test.tsx
  src/library-authoring/add-content/AddContent.tsx
  src/library-authoring/add-content/PickLibraryContentModal.test.tsx
  src/library-authoring/add-content/PickLibraryContentModal.tsx
  src/library-authoring/add-content/messages.ts
  src/library-authoring/common/context/SidebarContext.tsx
  src/library-authoring/components/ContainerCard.test.tsx
  src/library-authoring/components/ContainerCard.tsx
  src/library-authoring/containers/ContainerOrganize.tsx
  src/library-authoring/containers/UnitInfo.tsx
  src/library-authoring/containers/messages.ts
  src/library-authoring/generic/manage-collections/ManageCollections.test.tsx
  src/library-authoring/generic/manage-collections/ManageCollections.tsx
  src/library-authoring/generic/manage-collections/messages.ts
  src/library-authoring/generic/messages.ts
  src/library-authoring/units/LibraryUnitBlocks.tsx
  src/library-authoring/units/LibraryUnitPage.tsx
  src/search-manager/data/api.ts
Labels: open-source-contribution

#1884 fix: unit pages ux bugs 2 [FC-0083]
  src/generic/delete-modal/DeleteModal.tsx
  src/generic/delete-modal/messages.ts
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/components/ComponentDeleter.tsx
  src/library-authoring/components/ContainerDeleter.tsx
  src/library-authoring/components/messages.ts
  src/library-authoring/data/apiHooks.ts
Labels: open-source-contribution, FC

#1866 fix: manage access modal on duplicated xblock
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/data/thunk.js
Labels: open-source-contribution, create-sandbox

#1874 fix: manage access modal on duplicated xblock
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/data/thunk.js
Labels: open-source-contribution

#1913 fix: UX issues in unit page
  codecov.yml
  src/content-tags-drawer/ContentTagsDrawer.test.jsx
  src/content-tags-drawer/ContentTagsDrawer.tsx
  src/content-tags-drawer/data/apiHooks.jsx
  src/content-tags-drawer/data/apiHooks.test.jsx
  src/course-outline/CourseOutline.test.jsx
  src/generic/DraggableList/DraggableList.jsx
  src/generic/DraggableList/SortableItem.jsx
  src/generic/DraggableList/verticalSortableList.ts
  src/generic/hooks/tests/hooks.test.tsx
  src/generic/hooks/useIframeBehavior.tsx
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryBlock/LibraryBlock.tsx
  src/library-authoring/common/context/SidebarContext.tsx
  src/library-authoring/component-info/ComponentInfo.tsx
  src/library-authoring/component-info/ComponentManagement.test.tsx
  src/library-authoring/component-info/ComponentManagement.tsx
  src/library-authoring/components/ComponentMenu.tsx
  src/library-authoring/components/ContainerCard.tsx
  src/library-authoring/containers/ContainerOrganize.tsx
  src/library-authoring/containers/UnitInfo.tsx
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/generic/manage-collections/ManageCollections.tsx
  src/library-authoring/library-sidebar/LibrarySidebar.tsx
  src/library-authoring/routes.test.tsx
  src/library-authoring/routes.ts
  src/library-authoring/units/LibraryUnitBlocks.tsx
  src/library-authoring/units/LibraryUnitPage.test.tsx
  src/library-authoring/units/LibraryUnitPage.tsx
  src/library-authoring/units/index.scss
  src/utils.js
Labels: open-source-contribution

#1916 fix: unit pages ux bugs 2 [teak]
  src/generic/delete-modal/DeleteModal.tsx
  src/generic/delete-modal/messages.ts
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/components/ComponentDeleter.tsx
  src/library-authoring/components/ContainerDeleter.tsx
  src/library-authoring/components/messages.ts
  src/library-authoring/data/apiHooks.ts
Labels: open-source-contribution

#1923 fix: UX issues in unit page (#1913)
  codecov.yml
  src/content-tags-drawer/ContentTagsDrawer.test.jsx
  src/content-tags-drawer/ContentTagsDrawer.tsx
  src/content-tags-drawer/data/apiHooks.jsx
  src/content-tags-drawer/data/apiHooks.test.jsx
  src/course-outline/CourseOutline.test.jsx
  src/generic/DraggableList/DraggableList.jsx
  src/generic/DraggableList/SortableItem.jsx
  src/generic/DraggableList/verticalSortableList.ts
  src/generic/hooks/tests/hooks.test.tsx
  src/generic/hooks/useIframeBehavior.tsx
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryBlock/LibraryBlock.tsx
  src/library-authoring/common/context/SidebarContext.tsx
  src/library-authoring/component-info/ComponentInfo.tsx
  src/library-authoring/component-info/ComponentManagement.test.tsx
  src/library-authoring/component-info/ComponentManagement.tsx
  src/library-authoring/components/ComponentMenu.tsx
  src/library-authoring/components/ContainerCard.tsx
  src/library-authoring/containers/ContainerOrganize.tsx
  src/library-authoring/containers/UnitInfo.tsx
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/generic/manage-collections/ManageCollections.tsx
  src/library-authoring/library-sidebar/LibrarySidebar.tsx
  src/library-authoring/routes.test.tsx
  src/library-authoring/routes.ts
  src/library-authoring/units/LibraryUnitBlocks.tsx
  src/library-authoring/units/LibraryUnitPage.test.tsx
  src/library-authoring/units/LibraryUnitPage.tsx
  src/library-authoring/units/index.scss
  src/utils.js
Labels: open-source-contribution

#1925 fix: invalidate search results when publishing all changes in library [FC-0083]
  src/library-authoring/data/apiHooks.ts
Labels: open-source-contribution, FC

#1927 [TEAK] fix: invalidate search results when publishing all changes in library [FC-0083]
  src/library-authoring/data/apiHooks.ts
Labels: open-source-contribution

#1918 fix: improve focus/selected style on library authoring
  src/generic/DraggableList/SortableItem.jsx
  src/library-authoring/components/BaseCard.scss
  src/library-authoring/components/BaseCard.tsx
  src/library-authoring/components/CollectionCard.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/ContainerCard.tsx
  src/library-authoring/units/LibraryUnitBlocks.tsx
  src/library-authoring/units/index.scss
Labels: open-source-contribution

#1926 fix: Issue with read-only units in libraries & published version of units in library units picker [FC-0083]
  src/course-unit/data/api.js
  src/course-unit/data/thunk.js
  src/library-authoring/components/ContainerCard.tsx
  src/library-authoring/containers/UnitInfo.test.tsx
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/units/LibraryUnitBlocks.tsx
Labels: open-source-contribution, FC

#1905 fix: review/sync bugs [FC-0083]
  src/course-libraries/CourseLibraries.test.tsx
  src/course-libraries/CourseLibraries.tsx
  src/course-libraries/OutOfSyncAlert.tsx
  src/course-libraries/ReviewTabContent.tsx
  src/course-libraries/__mocks__/linkCourseSummary.json
  src/course-libraries/__mocks__/publishableEntityLinks.json
  src/course-libraries/data/api.mocks.ts
  src/course-libraries/data/api.ts
  src/course-libraries/data/apiHooks.test.tsx
  src/course-libraries/data/apiHooks.ts
  src/course-libraries/messages.ts
  src/course-outline/unit-card/UnitCard.jsx
  src/course-unit/preview-changes/index.test.tsx
  src/course-unit/preview-changes/index.tsx
  src/course-unit/preview-changes/messages.ts
  src/generic/alert-message/index.scss
  src/generic/styles.scss
  src/library-authoring/component-info/ComponentDetails.test.tsx
  src/library-authoring/component-info/ComponentInfo.test.tsx
  src/library-authoring/component-info/ComponentUsage.tsx
  src/library-authoring/components/PublishConfirmationModal.tsx
  src/library-authoring/data/api.mocks.ts
Labels: open-source-contribution

#1938 fix: search modal refresh on typing
  src/course-outline/CourseOutline.test.jsx
  src/course-outline/subsection-card/SubsectionCard.jsx
  src/course-outline/subsection-card/SubsectionCard.test.jsx
Labels: open-source-contribution

#1921 i18n Issues Mega Issue part 1 (Uncontroversial part)
  src/accessibility-page/AccessibilityPage.jsx
  src/accessibility-page/constants.ts
  src/editors/containers/EditorContainer/components/TitleHeader/EditableHeader.jsx
  src/editors/containers/EditorContainer/components/TitleHeader/messages.js
  src/editors/containers/VideoEditor/components/SelectVideoModal.jsx
  src/editors/containers/VideoEditor/components/SelectVideoModal.test.jsx
  src/editors/containers/VideoEditor/components/messages.ts
  src/generic/configure-modal/AdvancedTab.jsx
  src/generic/configure-modal/messages.js
  src/studio-home/tabs-section/courses-tab/courses-filters/index.jsx
  src/studio-home/tabs-section/courses-tab/courses-filters/messages.js
  src/taxonomy/import-tags/ImportTagsWizard.jsx
  src/taxonomy/import-tags/messages.ts
Labels: open-source-contribution

#1930 fix: improve focus/selected style on library authoring [teak]
  src/generic/DraggableList/SortableItem.jsx
  src/library-authoring/components/BaseCard.scss
  src/library-authoring/components/BaseCard.tsx
  src/library-authoring/components/CollectionCard.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/ContainerCard.tsx
  src/library-authoring/units/LibraryUnitBlocks.tsx
  src/library-authoring/units/index.scss
Labels: open-source-contribution, backport

#1941 fix: review/sync bugs [teak]
  src/course-libraries/CourseLibraries.test.tsx
  src/course-libraries/CourseLibraries.tsx
  src/course-libraries/OutOfSyncAlert.tsx
  src/course-libraries/ReviewTabContent.tsx
  src/course-libraries/__mocks__/linkCourseSummary.json
  src/course-libraries/__mocks__/publishableEntityLinks.json
  src/course-libraries/data/api.mocks.ts
  src/course-libraries/data/api.ts
  src/course-libraries/data/apiHooks.test.tsx
  src/course-libraries/data/apiHooks.ts
  src/course-libraries/messages.ts
  src/course-outline/unit-card/UnitCard.jsx
  src/course-unit/preview-changes/index.test.tsx
  src/course-unit/preview-changes/index.tsx
  src/course-unit/preview-changes/messages.ts
  src/generic/alert-message/index.scss
  src/generic/styles.scss
  src/library-authoring/component-info/ComponentDetails.test.tsx
  src/library-authoring/component-info/ComponentInfo.test.tsx
  src/library-authoring/component-info/ComponentUsage.tsx
  src/library-authoring/components/PublishConfirmationModal.tsx
  src/library-authoring/data/api.mocks.ts
Labels: open-source-contribution, backport, FC

#1931 chore: remove unused dependencies "npm" and "start"
  package-lock.json
  package.json
Labels: open-source-contribution

#1802 fix: include plugins in i18n extraction script
  package-lock.json
  package.json
Labels: open-source-contribution

#1940 [Teak] fix: Issue with read-only units in libraries & published version of units in library units picker [FC-0083] (#1926)
  src/course-unit/data/api.js
  src/course-unit/data/thunk.js
  src/library-authoring/components/ContainerCard.tsx
  src/library-authoring/containers/UnitInfo.test.tsx
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/units/LibraryUnitBlocks.tsx
Labels: open-source-contribution, backport, FC

#1945 chore: add comment to prevent course search reload on type
  src/course-outline/subsection-card/SubsectionCard.jsx
Labels: open-source-contribution

#1946 docs: update maintainer to me in catalog-info.yaml
  catalog-info.yaml
Labels: open-source-contribution

#1922 i18n Issues Mega Issue part 2 (Controversial part)
  src/course-outline/card-header/CardHeader.jsx
  src/course-outline/card-header/messages.js
  src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswerOption.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/messages.js
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseDetails.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/LicenseDetails.test.jsx.snap
  src/files-and-videos/files-page/FilesPage.test.jsx
  src/files-and-videos/generic/FileInput.jsx
  src/files-and-videos/generic/messages.js
  src/files-and-videos/generic/table-components/sort-and-filter-modal/SortAndFilterModal.jsx
  src/files-and-videos/generic/table-components/sort-and-filter-modal/messages.js
  src/files-and-videos/videos-page/VideosPage.test.jsx
  src/files-and-videos/videos-page/info-sidebar/TranscriptTab.test.jsx
  src/files-and-videos/videos-page/transcript-settings/OrderTranscriptForm.jsx
  src/files-and-videos/videos-page/transcript-settings/messages.js
Labels: open-source-contribution, mao-onboarding

#1713 fix: render proper visibility message on self-paced course type
  src/generic/configure-modal/ConfigureModal.jsx
  src/generic/configure-modal/VisibilityTab.jsx
  src/generic/configure-modal/messages.js
Labels: open-source-contribution, backport

#1953 fix: change InplaceTextEditor style and add optimistic update
  src/generic/inplace-text-editor/InplaceTextEditor.test.tsx
  src/generic/inplace-text-editor/index.tsx
  src/library-authoring/collections/CollectionInfoHeader.tsx
  src/library-authoring/component-info/ComponentInfoHeader.tsx
  src/library-authoring/containers/ContainerInfoHeader.tsx
  src/library-authoring/containers/UnitInfo.test.tsx
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/units/LibraryUnitBlocks.tsx
  src/library-authoring/units/LibraryUnitPage.test.tsx
  src/library-authoring/units/LibraryUnitPage.tsx
Labels: open-source-contribution

#1949 feat: select component and show sidebar on edit
  src/library-authoring/components/ComponentCard.test.tsx
  src/library-authoring/components/ComponentMenu.tsx
  src/library-authoring/containers/UnitInfo.test.tsx
  src/library-authoring/data/api.test.ts
  src/library-authoring/units/LibraryUnitBlocks.tsx
Labels: open-source-contribution, core contributor

#1999 fix: search text flickering
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/collections/LibraryCollectionPage.test.tsx
  src/search-manager/SearchKeywordsField.tsx
Labels: open-source-contribution, core contributor

#2002 feat: open collection or unit page on double click only
  src/library-authoring/collections/CollectionInfo.tsx
  src/library-authoring/components/BaseCard.tsx
  src/library-authoring/components/CollectionCard.tsx
  src/library-authoring/components/ContainerCard.tsx
  src/library-authoring/routes.ts
Labels: open-source-contribution, core contributor

#1887 fix: do open editor of new xblock when duplicating
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/add-component/AddComponent.jsx
  src/course-unit/xblock-container-iframe/hooks/types.ts
  src/course-unit/xblock-container-iframe/hooks/useMessageHandlers.tsx
  src/course-unit/xblock-container-iframe/index.tsx
  src/data/slice.js
  src/editors/VideoSelector.jsx
  src/editors/VideoSelectorPage.jsx
  src/editors/containers/VideoGallery/hooks.js
  src/editors/containers/VideoGallery/index.jsx
  src/editors/containers/VideoGallery/index.test.jsx
  src/editors/containers/VideoGallery/messages.js
  src/editors/containers/VideoUploadEditor/VideoUploader.jsx
  src/editors/containers/VideoUploadEditor/hooks.js
  src/editors/containers/VideoUploadEditor/index.jsx
Labels: open-source-contribution

#1993 fix: rename library publish button
  src/library-authoring/generic/status-widget/index.tsx
  src/library-authoring/library-info/LibraryPublishStatus.tsx
  src/library-authoring/library-info/messages.ts
Labels: open-source-contribution

#1906 feat: New delete confirmation modal [FC-0083]
  src/library-authoring/component-info/ComponentUsage.tsx
  src/library-authoring/components/ComponentCard.test.tsx
  src/library-authoring/components/ComponentDeleter.test.tsx
  src/library-authoring/components/ComponentDeleter.tsx
  src/library-authoring/components/ComponentMenu.tsx
  src/library-authoring/components/messages.ts
  src/library-authoring/data/apiHooks.ts
  src/search-manager/data/api.ts
Labels: open-source-contribution, FC

#1966 fix: Inconsistent publish status filter menu placement in Library home page
  src/library-authoring/LibraryAuthoringPage.tsx
Labels: open-source-contribution

#1996 fix: removing edX text reference on video fallback message
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/__snapshots__/index.test.jsx.snap
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/index.test.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/messages.js
Labels: open-source-contribution, mao-onboarding

#2004 Rename in content dropdown updates and libraries
  src/header/hooks.test.js
  src/header/messages.js
Labels: open-source-contribution, mao-onboarding

#2006 [Teak] backport #1949, #1999 and #2002
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/collections/CollectionInfo.tsx
  src/library-authoring/collections/LibraryCollectionPage.test.tsx
  src/library-authoring/components/BaseCard.tsx
  src/library-authoring/components/CollectionCard.tsx
  src/library-authoring/components/ComponentCard.test.tsx
  src/library-authoring/components/ComponentMenu.tsx
  src/library-authoring/components/ContainerCard.tsx
  src/library-authoring/containers/UnitInfo.test.tsx
  src/library-authoring/data/api.test.ts
  src/library-authoring/routes.ts
  src/library-authoring/units/LibraryUnitBlocks.tsx
  src/search-manager/SearchKeywordsField.tsx
Labels: open-source-contribution, core contributor

#2014 fix: change InplaceTextEditor style and add optimistic update [teak]
  src/generic/inplace-text-editor/InplaceTextEditor.test.tsx
  src/generic/inplace-text-editor/index.tsx
  src/library-authoring/collections/CollectionInfoHeader.tsx
  src/library-authoring/component-info/ComponentInfoHeader.tsx
  src/library-authoring/containers/ContainerInfoHeader.tsx
  src/library-authoring/containers/UnitInfo.test.tsx
  src/library-authoring/data/apiHooks.ts
  src/library-authoring/units/LibraryUnitBlocks.tsx
  src/library-authoring/units/LibraryUnitPage.test.tsx
  src/library-authoring/units/LibraryUnitPage.tsx
Labels: open-source-contribution

#2016 fix: rename library publish button to "Publish All"
  src/library-authoring/library-info/messages.ts
Labels: open-source-contribution

#2015 fix: rename library publish button [teak]
  src/library-authoring/generic/status-widget/index.tsx
  src/library-authoring/library-info/LibraryPublishStatus.tsx
  src/library-authoring/library-info/messages.ts
Labels: open-source-contribution

#1947 fix: Remove never published filter from component picker
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/collections/LibraryCollectionPage.tsx
  src/library-authoring/component-picker/ComponentPicker.test.tsx
  src/library-authoring/generic/filter-by-published/index.tsx
  src/search-manager/FilterByPublished.tsx
  src/search-manager/data/api.ts
Labels: open-source-contribution

#2022 fix: refresh xblock inline after accepting/rejecting library sync [FC-0090]
  src/course-unit/preview-changes/index.test.tsx
  src/course-unit/preview-changes/index.tsx
Labels: open-source-contribution, core contributor

#2028 [TEAK] fix: refresh xblock inline after accepting/rejecting library sync [FC-0090]
  src/course-unit/preview-changes/index.test.tsx
  src/course-unit/preview-changes/index.tsx
Labels: open-source-contribution, core contributor

#2030 [TEAK] fix: set maxHeight on TextEditor TinyMce widget [FC-0090]
  src/editors/containers/TextEditor/__snapshots__/index.test.jsx.snap
  src/editors/containers/TextEditor/index.jsx
  src/editors/sharedComponents/TinyMceWidget/hooks.js
Labels: open-source-contribution, core contributor

#1932 chore: bump UUID to v11
  package-lock.json
  package.json
  src/certificates/constants.ts
Labels: open-source-contribution

#2013 feat: create section and subsection in library
  src/generic/block-type-utils/constants.ts
  src/generic/block-type-utils/index.scss
  src/generic/key-utils.ts
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryLayout.tsx
  src/library-authoring/add-content/AddContent.test.tsx
  src/library-authoring/add-content/AddContent.tsx
  src/library-authoring/add-content/messages.ts
  src/library-authoring/collections/LibraryCollectionPage.test.tsx
  src/library-authoring/common/context/LibraryContext.tsx
  src/library-authoring/create-container/CreateContainerModal.tsx
  src/library-authoring/create-container/index.tsx
  src/library-authoring/create-container/messages.ts
  src/library-authoring/create-unit/CreateUnitModal.tsx
  src/library-authoring/create-unit/index.tsx
  src/library-authoring/create-unit/messages.ts
  src/library-authoring/routes.ts
Labels: open-source-contribution, core contributor, FC

#2041 fix: upstreamInfo is not always provided
  src/course-unit/CourseUnit.jsx
Labels: open-source-contribution, core contributor

#2042 [teak] fix: upstreamInfo is not always provided [FC-0090]
  src/course-unit/CourseUnit.jsx
Labels: open-source-contribution, core contributor

#2045 fix: selection card wiggle
  src/library-authoring/components/BaseCard.scss
  src/library-authoring/units/LibraryUnitBlocks.tsx
  src/library-authoring/units/index.scss
Labels: open-source-contribution

#2047 fix: selection card wiggle [teak]
  src/library-authoring/components/BaseCard.scss
  src/library-authoring/units/LibraryUnitBlocks.tsx
  src/library-authoring/units/index.scss
Labels: open-source-contribution

#1611 refactor: remove references of ENABLE_HOME_PAGE_COURSE_API_V2
  .env
  .env.development
  src/index.jsx
  src/studio-home/StudioHome.tsx
  src/studio-home/card-item/CardItem.test.tsx
  src/studio-home/card-item/index.tsx
  src/studio-home/data/api.test.js
  src/studio-home/data/slice.js
  src/studio-home/data/slice.test.js
  src/studio-home/data/thunks.js
  src/studio-home/factories/mockApiResponses.jsx
  src/studio-home/hooks.jsx
  src/studio-home/messages.ts
  src/studio-home/tabs-section/TabsSection.test.tsx
  src/studio-home/tabs-section/archived-tab/index.jsx
  src/studio-home/tabs-section/courses-tab/courses-filters/index.jsx
  src/studio-home/tabs-section/courses-tab/index.test.tsx
  src/studio-home/tabs-section/courses-tab/index.tsx
  src/studio-home/tabs-section/index.tsx
Labels: open-source-contribution
