Repository openedx/frontend-app-authoring, pull requests merged in 2025-03, with the labels that each got.

#1454 feat: [FC-0070] Manage Tags interoperation
  src/content-tags-drawer/data/apiHooks.jsx
  src/course-unit/CourseUnit.jsx
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/add-component/AddComponent.jsx
  src/course-unit/constants.js
  src/course-unit/context/hooks.tsx
  src/course-unit/hooks.jsx
  src/course-unit/hooks.test.jsx
  src/course-unit/xblock-container-iframe/hooks/types.ts
  src/course-unit/xblock-container-iframe/hooks/useMessageHandlers.tsx
  src/course-unit/xblock-container-iframe/index.tsx
Labels: open-source-contribution, create-sandbox, FC

#1457 fix: 500 error after saving empty subsection release date
  src/generic/configure-modal/ConfigureModal.jsx
Labels: bug, open-source-contribution

#1590 fix: broken re-run notification dismiss
  src/course-outline/hooks.jsx
Labels: open-source-contribution

#1269 Fix: some default setting not updating with updated default settings
  src/editors/containers/ProblemEditor/components/EditProblemView/hooks.test.js
  src/editors/containers/ProblemEditor/data/ReactStateSettingsParser.js
  src/editors/containers/ProblemEditor/data/mockData/problemTestData.js
Labels: bug, open-source-contribution

#1700 fix: excessive calls to the clipboard API endpoint [FC-0076]
  src/course-outline/CourseOutline.jsx
  src/course-outline/CourseOutline.test.jsx
  src/course-outline/data/api.js
  src/course-outline/data/thunk.js
  src/course-outline/hooks.jsx
  src/course-outline/subsection-card/SubsectionCard.jsx
  src/course-outline/unit-card/UnitCard.jsx
  src/course-outline/unit-card/UnitCard.test.jsx
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/data/thunk.js
  src/course-unit/hooks.jsx
  src/course-unit/sidebar/components/sidebar-footer/ActionButtons.jsx
  src/course-unit/sidebar/components/sidebar-footer/ActionButtons.test.jsx
  src/course-unit/xblock-container-iframe/hooks/tests/hooks.test.tsx
  src/course-unit/xblock-container-iframe/hooks/useMessageHandlers.tsx
  src/generic/clipboard/hooks/messages.ts
  src/generic/clipboard/hooks/useClipboard.test.tsx
  src/generic/clipboard/hooks/useClipboard.ts
  src/generic/clipboard/hooks/useCopyToClipboard.js
  src/generic/clipboard/hooks/useCopyToClipboard.test.jsx
  src/generic/clipboard/index.js
  src/generic/clipboard/paste-component/components/PasteButton.jsx
  src/generic/clipboard/paste-component/components/PasteButton.tsx
  src/generic/clipboard/paste-component/components/PopoverContent.tsx
  src/generic/clipboard/paste-component/components/WhatsInClipboard.tsx
  src/generic/clipboard/paste-component/components/index.ts
  src/generic/clipboard/paste-component/constants.js
  src/generic/clipboard/paste-component/index.tsx
  src/generic/clipboard/paste-component/messages.ts
  src/generic/data/selectors.js
  src/generic/data/slice.js
  src/generic/data/thunks.js
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/components/ComponentCard.test.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/messages.ts
  src/testUtils.tsx
Labels: open-source-contribution, FC

#1724 fix: paste button on unit outline
  src/course-unit/CourseUnit.jsx
  src/generic/clipboard/paste-component/index.tsx
Labels: open-source-contribution

#1701 refactor: Separate Publish order sort from publish filter [FC-0076]
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/collections/LibraryCollectionPage.test.tsx
  src/search-manager/FilterByPublished.tsx
  src/search-manager/SearchManager.ts
Labels: open-source-contribution, FC

#1665 fix: render proper visibility message on self-paced course type
  src/generic/configure-modal/ConfigureModal.jsx
  src/generic/configure-modal/VisibilityTab.jsx
  src/generic/configure-modal/messages.js
Labels: open-source-contribution

#1677 feat: Add Publish confirmation modal [FC-0076]
  src/library-authoring/component-info/ComponentInfo.test.tsx
  src/library-authoring/component-info/ComponentInfo.tsx
  src/library-authoring/components/PublishConfirmationModal.tsx
  src/library-authoring/components/messages.ts
  src/library-authoring/data/api.mocks.ts
Labels: open-source-contribution, FC

#1699 feat: course libraries review tab [FC-0076]
  src/CourseAuthoringRoutes.jsx
  src/course-libraries/CourseLibraries.test.tsx
  src/course-libraries/CourseLibraries.tsx
  src/course-libraries/OutOfSyncAlert.tsx
  src/course-libraries/ReviewTabContent.tsx
  src/course-libraries/__mocks__/libBlockMetadata.json
  src/course-libraries/__mocks__/linkCourseSummary.json
  src/course-libraries/__mocks__/linkDetailsFromIndex.json
  src/course-libraries/__mocks__/publishableEntityLinks.json
  src/course-libraries/data/api.mocks.ts
  src/course-libraries/data/api.ts
  src/course-libraries/data/apiHooks.test.tsx
  src/course-libraries/data/apiHooks.ts
  src/course-libraries/index.tsx
  src/course-libraries/messages.ts
  src/course-outline/page-alerts/PageAlerts.jsx
  src/course-outline/page-alerts/PageAlerts.test.jsx
  src/course-unit/CourseUnit.jsx
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/preview-changes/index.test.tsx
  src/course-unit/preview-changes/index.tsx
  src/generic/loading-button/index.jsx
  src/library-authoring/component-info/ComponentDetails.test.tsx
  src/library-authoring/component-info/ComponentInfo.test.tsx
  src/library-authoring/component-info/ComponentUsage.tsx
  src/library-authoring/components/PublishConfirmationModal.tsx
  src/library-authoring/data/api.mocks.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
  src/search-manager/SearchSortWidget.tsx
  src/search-manager/data/__mocks__/downstream-links.json
  src/search-manager/data/api.mock.ts
  src/search-manager/data/api.ts
  src/search-manager/data/apiHooks.ts
  src/search-manager/index.ts
  src/testUtils.tsx
Labels: open-source-contribution, FC

#1723 fix: excessive calls to the clipboard API endpoint [sumac]
  src/course-outline/CourseOutline.jsx
  src/course-outline/CourseOutline.test.jsx
  src/course-outline/data/api.js
  src/course-outline/data/thunk.js
  src/course-outline/hooks.jsx
  src/course-outline/subsection-card/SubsectionCard.jsx
  src/course-outline/unit-card/UnitCard.jsx
  src/course-outline/unit-card/UnitCard.test.jsx
  src/course-unit/CourseUnit.jsx
  src/course-unit/CourseUnit.test.jsx
  src/course-unit/course-xblock/CourseXBlock.jsx
  src/course-unit/course-xblock/CourseXBlock.test.jsx
  src/course-unit/data/thunk.js
  src/course-unit/hooks.jsx
  src/course-unit/sidebar/components/sidebar-footer/ActionButtons.jsx
  src/course-unit/sidebar/components/sidebar-footer/ActionButtons.test.jsx
  src/generic/clipboard/hooks/messages.ts
  src/generic/clipboard/hooks/useClipboard.test.tsx
  src/generic/clipboard/hooks/useClipboard.ts
  src/generic/clipboard/hooks/useCopyToClipboard.js
  src/generic/clipboard/hooks/useCopyToClipboard.test.jsx
  src/generic/clipboard/index.js
  src/generic/clipboard/paste-component/components/PasteButton.jsx
  src/generic/clipboard/paste-component/components/PasteButton.tsx
  src/generic/clipboard/paste-component/components/PopoverContent.tsx
  src/generic/clipboard/paste-component/components/WhatsInClipboard.tsx
  src/generic/clipboard/paste-component/components/index.ts
  src/generic/clipboard/paste-component/constants.js
  src/generic/clipboard/paste-component/index.tsx
  src/generic/clipboard/paste-component/messages.ts
  src/generic/data/selectors.js
  src/generic/data/slice.js
  src/generic/data/thunks.js
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/components/ComponentCard.test.tsx
  src/library-authoring/components/ComponentCard.tsx
  src/library-authoring/components/messages.ts
  src/testUtils.tsx
Labels: open-source-contribution, backport, FC

#1731 fix: image rendering in single and multi select problems [FC-0076]
  src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswerOption.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswerOption.test.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/hooks.js
  src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/hooks.test.js
  src/editors/containers/ProblemEditor/components/EditProblemView/ExplanationWidget/index.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/ExplanationWidget/index.test.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/QuestionWidget/index.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/QuestionWidget/index.test.jsx
  src/editors/data/redux/problem/reducers.test.ts
  src/editors/data/redux/problem/reducers.ts
  src/editors/sharedComponents/ExpandableTextArea/__snapshots__/index.test.jsx.snap
  src/editors/sharedComponents/ExpandableTextArea/index.jsx
  src/editors/sharedComponents/ExpandableTextArea/index.scss
  src/editors/sharedComponents/ExpandableTextArea/index.test.jsx
  src/editors/sharedComponents/TinyMceWidget/hooks.js
  src/editors/sharedComponents/TinyMceWidget/hooks.test.js
  src/editors/sharedComponents/TinyMceWidget/pluginConfig.js
Labels: open-source-contribution

#1740 perf: add staleTime to queryClient to avoid excessive calls [sumac]
  src/index.jsx
Labels: open-source-contribution, backport

#1730 fix: show error information when taxonomy import fails [FC-0076]
  src/generic/alert-error/AlertError.test.tsx
  src/generic/alert-error/index.tsx
  src/generic/alert-error/messages.ts
  src/library-authoring/collections/LibraryCollectionPage.test.tsx
  src/library-authoring/create-library/CreateLibrary.test.tsx
  src/taxonomy/TaxonomyLayout.test.tsx
  src/taxonomy/TaxonomyLayout.tsx
  src/taxonomy/TaxonomyListPage.test.tsx
  src/taxonomy/common/context.ts
  src/taxonomy/import-tags/ImportTagsWizard.jsx
  src/taxonomy/import-tags/ImportTagsWizard.test.jsx
  src/taxonomy/messages.ts
  src/taxonomy/taxonomy-menu/TaxonomyMenu.test.tsx
Labels: open-source-contribution, FC

#1743 refactor: open review tab in course libraries if out of sync [FC-0076]
  src/course-libraries/CourseLibraries.test.tsx
  src/course-libraries/CourseLibraries.tsx
Labels: open-source-contribution

#1750 refactor: don't dismiss out of sync alert on review [FC-0076]
  src/course-libraries/CourseLibraries.test.tsx
  src/course-libraries/OutOfSyncAlert.tsx
Labels: open-source-contribution

#1761 fix: prevent editor from loading twice before initialization
  src/editors/Editor.tsx
  src/editors/VideoSelector.jsx
  src/editors/VideoSelector.test.jsx
  src/editors/hooks.test.jsx
  src/editors/hooks.ts
Labels: open-source-contribution

#1741 feat: create unit on libraries workflow [FC-0083]
  src/generic/block-type-utils/constants.ts
  src/generic/key-utils.test.ts
  src/generic/key-utils.ts
  src/generic/loading-button/LoadingButton.test.tsx
  src/generic/loading-button/index.tsx
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryLayout.tsx
  src/library-authoring/add-content/AddContentContainer.tsx
  src/library-authoring/add-content/messages.ts
  src/library-authoring/common/context/LibraryContext.tsx
  src/library-authoring/create-collection/messages.ts
  src/library-authoring/create-library/CreateLibrary.tsx
  src/library-authoring/create-unit/CreateUnitModal.tsx
  src/library-authoring/create-unit/index.tsx
  src/library-authoring/create-unit/messages.ts
  src/library-authoring/data/api.ts
  src/library-authoring/data/apiHooks.ts
Labels: open-source-contribution, FC

#1754 feat: library units tab [FC-0083]
  src/library-authoring/LibraryAuthoringPage.test.tsx
  src/library-authoring/LibraryAuthoringPage.tsx
  src/library-authoring/LibraryLayout.tsx
  src/library-authoring/__mocks__/library-search.json
  src/library-authoring/messages.ts
  src/library-authoring/routes.test.tsx
  src/library-authoring/routes.ts
Labels: open-source-contribution, FC
